### ISSUE TITLE
Scalars needs to be simpled

### ISSUE THREAD

**Issue by BingBlog** [PaddlePaddle/VisualDL#10]
目前Scalars中，如果图的数据量过大，会出现卡顿。
可以在sdk里面加一些自动的设置。

**Comment by varunarora** [comment]
@jetfuel Could use some help here too :)

**Comment by jetfuel** [comment]
@varunarora The Scalar page will experience some delay when loading excess amount of data. 
The SDK should implement some algorithm to avoid this case.

**Comment by ShenYuhan** [comment]
此问题在VisualDL 2.0.0已经得到解决和优化，目前后台数据增大不会增加采样负荷，采用蓄水池算法避免了重复采样。
