### ISSUE TITLE
关于平滑度的问题

### ISSUE THREAD

**Issue by 237035848** [PaddlePaddle/VisualDL#1007]
visualdl 采用的平滑函数是什么？在源码中的哪一部分？
如果想在origin中实现相似的平滑 因采用哪种平滑方法 且平滑度的参数对应分别是什么？
感谢回复！

**Comment by PeterPanZH** [comment]
使用的是移动平均
https://github.com/PaddlePaddle/VisualDL/blob/733cd4eb32fa6f128ba0901492e3613de7bd62b3/frontend/packages/wasm/src/scalar.rs#L43
https://github.com/PaddlePaddle/VisualDL/blob/733cd4eb32fa6f128ba0901492e3613de7bd62b3/frontend/packages/core/src/resource/scalar/data.ts#L28
上述两个实现是一样的
