### ISSUE TITLE
本地使用VDL无法同时显示两个log，单独一个文件的都可以正常可视化

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/VisualDL#1024]
VDL版本：2.2.1

```
conda activate torch1.9
visualdl --logdir C:/Users/1/Desktop/103072/output/ppoc_2596878_103072/output_vdl/
```

**Comment by YixinKristy** [comment]
请问是在AIStudio中使用么？

**Comment by gaorui999** [comment]
本地使用的，AIStudio也试过了，也是同样问题

**Comment by rainyfly** [comment]
请问两个log都是放在C:/Users/1/Desktop/103072/output/ppoc_2596878_103072/output_vdl/中么，我们对于一个文件夹只读取解析一个日志文件，如果想要显示两个，应该分别放到不同的子目录里，比如一个在C:/Users/1/Desktop/103072/output/ppoc_2596878_103072/output_vdl/train1/中，一个日志文件在C:/Users/1/Desktop/103072/output/ppoc_2596878_103072/output_vdl/train2/中。
如果两个日志文件确实在两个不同子目录中，那么还有一种可能性，在写日志文件的时候，LogWriter的display参数被设置了，并且设置为了同一个值，导致前端解析的时候，只能认出一个文件，默认初始化LogWriter，可以不需要设置display参数的哦，如果以上两个问题都排除了，还出现这个问题，可以进一步提供错误信息或者测试日志供我们分析。

**Comment by gaorui999** [comment]
感谢回复，解决了我的问题~
