### ISSUE TITLE
同一个目录下有多个.log文件，不应该是所有的一起输出吗？为什么只输出一个

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/VisualDL#1027]
![image](https://user-images.githubusercontent.com/40875421/142201012-79d3bd51-5ba2-425b-b787-7b541a4e7a8c.png)
这句话的意思，是同一个目录底下所有的.log文件都会绘制出来吧？可是我的不行
![YU$B~XU%AS)@QXUEET)20MA](https://user-images.githubusercontent.com/40875421/142201487-6f1e2a22-6650-4586-a5df-c72a03558fcb.png)
![I7@0IM0V N38C}X8![image](https://user-images.githubusercontent.com/40875421/142201012-79d3bd51-5ba2-425b-b787-7b541a4e7a8c.png)

**Comment by zmdcs** [comment]
![I7@0IM0V N38C}X8RGIT5](https://user-images.githubusercontent.com/40875421/142201631-fbbbef12-923f-46d2-bf13-6ab4a02c8803.png)
最后一张图放错了

**Comment by zmdcs** [comment]
你看他显示的就只有一条线了，为什么？

**Comment by zmdcs** [comment]
我用的命令行语句就是最简单的visualdl --logdir  vdl_dir/scalar

**Comment by rainyfly** [comment]
不是啊，VisualDL对于一个目录下所有日志只会读取最新的日志进行显示，但是会递归读取所有子目录。比如说test/vdlrecords.log1.log , test/vdlrecords.log2.log,  test/subtest/vdlrecords.log1.log , test/subtest1/vdlrecords.log1.log, 这样一共会显示3个日志，test/目录下只会显示test/vdlrecords.log2.log，但是会递归的找子目录subtest和subtest1里面的日志。

**Comment by rainyfly** [comment]
每一次跑新的实验，应该指定一个新的目录，如果指定的目录不存在，VDL是会自动帮忙创建的，因为我们假定的是一个目录就代表一次实验，如果一个目录有两个日志文件，只读取最新的那个，可能老的那个是不想要了的。
