### ISSUE TITLE
给出的指定多个文件夹的语句报错

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/VisualDL#1028]
visualdl --logdir <vdl_dir/scalar1,vdl_dir/scalar_v3,vdl_dir/scalar_v3s>
语句就是上面这样，然后
![{ZS9GF}Z{%%{IDA%WVDZ2%0](https://user-images.githubusercontent.com/40875421/142205874-cdcae919-a76f-495a-aaeb-7ae75b04ca34.png)

**Comment by rainyfly** [comment]
你只需要 visualdl --logdir vdl_dir/ 就可以了，会自动找vdl_dir下的所有子目录

**Comment by zmdcs** [comment]
为什么我的VisualDL没法选择绘画的曲线呢？只有全选




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月18日(星期四) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/VisualDL] 给出的指定多个文件夹的语句报错 (Issue #1028)





 
你只需要 visualdl --logdir vdl_dir/ 就可以了，会自动找vdl_dir下的所有子目录
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmdcs** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/VisualDL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月18日(星期四) 上午9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/VisualDL] 给出的指定多个文件夹的语句报错 (Issue #1028)





 
你只需要 visualdl --logdir vdl_dir/ 就可以了，会自动找vdl_dir下的所有子目录
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmdcs** [comment]
![image](https://user-images.githubusercontent.com/40875421/142336709-686016e1-e03b-47d6-984e-86e8ec7e899e.png)

**Comment by rainyfly** [comment]
可以把浏览器窗口的底部向下拉点，然后那个拉动框就能显现出来啦

**Comment by zmdcs** [comment]
拉了，没有，你看那个滚动条已经到底了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月18日(星期四) 上午10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/VisualDL] 给出的指定多个文件夹的语句报错 (Issue #1028)





 
可以把浏览器窗口的底部向下拉点，然后那个拉动框就能显现出来啦
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rainyfly** [comment]
可以试试把浏览器缩小到窗口模式，不全屏，然后滚动到页面最底部后，再试着把浏览器的窗口的底部向下拉，看看滚动条那个位置是不是就显现出来了更多内容了

**Comment by zmdcs** [comment]
![image](https://user-images.githubusercontent.com/40875421/142526772-fe16135d-f3aa-43c0-aecb-c3f5faa33ae1.png)
不行

**Comment by zmdcs** [comment]
两个滚动条都是灰的了 ,我已经拉到最底下了

**Comment by rainyfly** [comment]
是浏览器底部拉长试试哈，浏览器的窗口的边缘不是可以拉嘛，来拉长，拉高浏览器的窗口，你试试把浏览器的窗口向下拉长

**Comment by zmdcs** [comment]
已经到底了呀,
![29120E15](https://user-images.githubusercontent.com/40875421/142537726-97bbf209-5970-4588-8c1e-904473059b84.png)

**Comment by zmdcs** [comment]
截图看不出已经到屏幕底了吗

**Comment by rainyfly** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/22424850/142548298-38402ead-971e-4160-bdfc-03667c717967.png">
我这边拉了可以显示一定区域出来，然后滚动诶，不过这个地方显示区域确实有点小，你要不换个浏览器试试，我会将这一问题进行记录和反馈的，感谢你的使用哈

**Comment by zmdcs** [comment]
我这个是压根没有呀,滚动条都到底了

**Comment by zmdcs** [comment]
我用谷歌一样的情况,只有全选没有单选,不是滚动条拉不下去,是压根没有单选选项.是不是对文件的名字或者文件结构有要求?

**Comment by rainyfly** [comment]
不是，我看你的图应该是有多个数据流，应该就是这一块的显示出现问题了,正常这一块显示是下图这样的，可以单独勾选数据流
![image](https://user-images.githubusercontent.com/22424850/142552170-323b4429-c32f-452b-b485-e693583dc251.png)

**Comment by zmdcs** [comment]
所以你的意思是我的电脑显示问题吗?还是后台程序显示问题?

**Comment by zmdcs** [comment]
我刚刚检查了一下代码,单选是存在的,但是没显示出来

**Comment by zmdcs** [comment]
![image](https://user-images.githubusercontent.com/40875421/142552970-0a076187-d0d9-4a85-9d95-08f804c12b35.png)

**Comment by zmdcs** [comment]
emmmmm,对不起,确实是电脑的问题,我换了个电脑,就能显示了

**Comment by rainyfly** [comment]
之前我也遇到过这个情况，但是我这里通过那种方式拉出来了，可能是前端相关代码设置的显示方式有点问题，待我们先check一下该问题发生的原因，感谢你的反馈。

**Comment by lazyn1997** [comment]
如何指定特定的多个文件夹啊，比如我不想显示vdl_dir下的所有子目录怎么指定呢？因为如果全显示了再在页面中勾选的话颜色不够分配，导致选择的曲线颜色区分度不够。
