### ISSUE TITLE
this is a development server

### ISSUE THREAD

**Issue by 4ls4mi** [PaddlePaddle/VisualDL#1031]
hi,
i am having an issue that tells me WARNING: This is a development server. Do not use it in a production deployment.
what am i doing wrong and how to fix it?
thanks
![Screenshot 2021-11-22 130833](https://user-images.githubusercontent.com/65548420/142851175-1c843d80-3fc2-489a-b961-1542894f2b92.png)

**Comment by rainyfly** [comment]
Hi, is the warning threw by Visualdl?
