### ISSUE TITLE
运行过程中发生错误

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/VisualDL#1034]
模型训练时过一段时间就发生错误不显示图了，
![image](https://user-images.githubusercontent.com/34644177/145177955-59e34101-cf7a-4c95-8057-507dd1a01a26.png)
有人提问过相同问题，工程师说更新版本可以解决，
![image](https://user-images.githubusercontent.com/34644177/145178150-167f52a5-27a7-410a-8a16-3b4de9c12c0c.png)
但是我按照图中命令进行安装，版本还是旧版本，如何更新到最新版本呢？

**Comment by rainyfly** [comment]
您好，2.2.2版本中修复了点击侧边栏的数据流选项时发生的报错问题，可以使用pip install visualdl==2.2.2进行更新。如果是一边训练一边进行可视化的时候，发生过一段时间产生发生错误的页面，这一问题我们的工程师还在修复中，等修复完成会通知您。

**Comment by lazyn1997** [comment]
好的，辛苦了。

**Comment by rainyfly** [comment]
您好，新版本已经修复了这一问题，可以安装最新的2.2.3版本https://pypi.org/project/visualdl/

**Comment by cs-xiao** [comment]
> 您好，新版本已经修复了这一问题，可以安装最新的2.2.3版本https://pypi.org/project/visualdl/

坏消息，2.2.3版本也会出现这个问题（已退回2.0.0版本使用无问题

**Comment by rainyfly** [comment]
你好，2.2.3版本还有这个问题么，因为我们的测试目前还没有发现这一问题，请问有没有报错的截图和环境描述，方便我们进一步定位问题。

**Comment by cs-xiao** [comment]
> 你好，2.2.3版本还有这个问题么，因为我们的测试目前还没有发现这一问题，请问有没有报错的截图和环境描述，方便我们进一步定位问题。

你好，已退回2.0.0版本，所以报错信息没有，[数据日志](https://wwi.lanzouo.com/ijsCE0018oqf)倒是有一份可以提供，有望复现问题

**Comment by lazyn1997** [comment]
我更新后不会出现该问题了，需要使用pip install visualdl==2.2.3命令进行更新
