### ISSUE TITLE
源码方式安装VisualDL踩坑记录——npm依赖问题（待解决）

### ISSUE THREAD

**Issue by KevinPang180** [PaddlePaddle/VisualDL#1036]
【前提】已安装nodejs，npm版本8.1.2![image](https://user-images.githubusercontent.com/36781990/145706583-0d43a7d1-9dfa-4c2c-aa76-8ce3358141f5.png)

【问题】按流程安装提示找不到`package.json`文件

【尝试的方案】尝试将VisualDL目录下的`package-lock.json`文件修改为`package.json`后，可正常执行`npm install`，但是执行安装命令`python setup.py bdist_wheel`依旧提示`npm should be installed.`

![image](https://user-images.githubusercontent.com/36781990/145706905-8f0e8f33-6278-471b-8a92-2f5dbfbc84dc.png)

据此可推断，按流程执行无法正常生成`package.json`文件，烦请开发同学看到留言后抽空给予帮助解答，谢谢~

**Comment by PeterPanZH** [comment]
目前暂时不支持在Windows下进行源码编译。
抱歉~

**Comment by KevinPang180** [comment]
您好，您的邮件我已经收到。我会尽快进行给您回复的，感谢您的来信！
