### ISSUE TITLE
visual dl 只显示最新生成的日志文件

### ISSUE THREAD

**Issue by zhuangh7** [PaddlePaddle/VisualDL#1068]
![image](https://user-images.githubusercontent.com/16149477/166624451-3c8d5cca-0281-4a20-8cf2-63a8a44292af.png)
![image](https://user-images.githubusercontent.com/16149477/166624457-eead632a-10aa-4a32-b475-d8bf37f0ffb8.png)
![image](https://user-images.githubusercontent.com/16149477/166624464-74b9858f-74af-4830-a183-27a4995e1a88.png)
![image](https://user-images.githubusercontent.com/16149477/166624480-af8b6457-687a-4e14-93c9-92186fd74661.png)

如图所示，我跑了蛮多次，但是最后在 visualdl 网页中只能看到最新的日志，重启 visualdl 也没用。

**Comment by rainyfly** [comment]
visualdl对于一个目录下只会显示最新的日志，像你想要显示不同setting下的日志，可以把不同日志放到不同文件夹。一般来说，可以在跑的时候设置logdir不同

**Comment by zhuangh7** [comment]
> 

……感觉略脏呀，这样子 writer 的 FILENAME_SUFFIX 感觉没有任何作用了？

**Comment by rainyfly** [comment]
目前FILENAME_SUFFIX应该只是用于自己区分文件吧。 我觉得不把文件名作为数据流来源的区分而把logdir作为数据流来源的区分主要是设计想法上的原因吧，目前一个目录代表一个setting下的实验，其实你在这个setting下不一定只会保存日志文件，而且还可能保存graph结构的文件，甚至是我们正在开发的profiler文件，把文件夹作为单位，这种情况文件下的所有不同类型的文件也都知道是来自哪个setting下跑的了。 而且有时候同一个setting，出于某些原因重跑了，产生的日志在同一个目录下，大多数情况下都是想看最近一次重跑产生的日志。

**Comment by zhuangh7** [comment]
> 目前FILENAME_SUFFIX应该只是用于自己区分文件吧。 我觉得不把文件名作为数据流来源的区分而把logdir作为数据流来源的区分主要是设计想法上的原因吧，目前一个目录代表一个setting下的实验，其实你在这个setting下不一定只会保存日志文件，而且还可能保存graph结构的文件，甚至是我们正在开发的profiler文件，把文件夹作为单位，这种情况文件下的所有不同类型的文件也都知道是来自哪个setting下跑的了。 而且有时候同一个setting，出于某些原因重跑了，产生的日志在同一个目录下，大多数情况下都是想看最近一次重跑产生的日志。

好的，感谢解答
