### ISSUE TITLE
复现时无法在BML中成功解析数据

### ISSUE THREAD

**Issue by DentistCode** [PaddlePaddle/VisualDL#1129]
使用功能：降维
环境：BML CodeLab beta，paddle2.3.2；
复现链接：https://aistudio.baidu.com/aistudio/projectdetail/1535355
尝试过：等待完成（10分钟）但无果；STFW，RTFM；重新fork了原项目*5；更换logdir保存路径；从其他的功能（eg标量数据）切换到降维

但是保持在数据解析中这个loading无法推进下一步
复现原教程为旧版的juypter，但是旧版的已经不支持数据可视化这个功能

**Comment by rainyfly** [comment]
Hi, 你要不试下把那个代码放到本地跑一下，然后本地开启VisualDL进行可视化能不能看到先。

**Comment by DentistCode** [comment]
感谢！在本地终于跑出来了。之前试过本地跑但是有问题，现在删了虚拟环境重新安装之后就正常了
