### ISSUE TITLE
Fail to pip install visualdl

### ISSUE THREAD

**Issue by fxd0122** [PaddlePaddle/VisualDL#1131]
python3 -m pip install visualdl -i https://mirror.baidu.com/pypi/simple

There will always be character encoding issues. how to solve?
![image](https://user-images.githubusercontent.com/54058611/189892410-08a39542-f938-48f6-8e30-ee1d545c732d.png)

**Comment by rainyfly** [comment]
What if use python3.7? I am not sure if it is due to some resource files are named by chinese characters. We will fix it in next version 2.4.1, which will be released after two days.

**Comment by fxd0122** [comment]
OK. Let me try to use python3.7.
