### ISSUE TITLE
add image最多只显示10张图？

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/VisualDL#1139]
你好我每100步保存图片，运行到4000步的时候，网页只显示10张图片
<img width="431" alt="image" src="https://user-images.githubusercontent.com/50394665/192997130-58b1c941-ba85-4539-a989-4e8d3f6b700b.png">

**Comment by JunnYu** [comment]
必须这样才可以看到所有的图片
```python
from visualdl import LogReader
from PIL import Image
import io
import base64

log_reader = LogReader(file_path="vdlrecords.1664437796.log")

img_b64 = log_reader._log_data["image"][r'train%images']

for img in img_b64:
    image = Image.open(io.BytesIO(img.image.encoded_image_string))
    display(image)

```

**Comment by rainyfly** [comment]
在图像发送到前端之前，经过了一个蓄水池，那个蓄水池对于image的大小只设置成了10，你可以改一下VisualDL/visualdl/server/data_manager.py里这个值的大小
<img width="420" alt="image" src="https://user-images.githubusercontent.com/22424850/193017687-fbc09fec-1082-4fe9-ac59-959f1b9ba0fd.png">

**Comment by JunnYu** [comment]
好的，谢谢大佬

**Comment by FANG-MING** [comment]
> 在图像发送到前端之前，经过了一个蓄水池，那个蓄水池对于image的大小只设置成了10，你可以改一下VisualDL/visualdl/server/data_manager.py里这个值的大小 <img alt="image" width="420" src="https://user-images.githubusercontent.com/22424850/193017687-fbc09fec-1082-4fe9-ac59-959f1b9ba0fd.png">

为什么不给个参数命令行进行调整呢
