### ISSUE TITLE
加载log文件报MemoryError

### ISSUE THREAD

**Issue by maidangdang1** [PaddlePaddle/VisualDL#1144]
想问问visualdl加载单个log文件是否有大小限制？如果有，大概是多少呢？
我在本地加载了两个log文件，单个大小约为18M，提示MemoryError，多次重试均如此。
原始log文件已删除，但我上传了一份，网址为`https://www.paddlepaddle.org.cn/paddle/visualdl/service/app/index?id=5ca0fac96d623460ce33375b3704fec8`，麻烦看看是什么原因，谢谢。

**Comment by rainyfly** [comment]
正常来说不应该呀，能不能造一个数据发给我们进行本地复现一下看看

**Comment by maidangdang1** [comment]
本地即使是造出大一倍的数据也没问题，有点奇怪。今晚再跑一次模型看看能不能复现🥲

**Comment by maidangdang1** [comment]
现在又没法复现了🥲不知道是不是偶发事件 下次再发现的时候再来提一嘴吧
