### ISSUE TITLE
Failed to save model graph, error: ''

### ISSUE THREAD

**Issue by CaoChensy** [PaddlePaddle/VisualDL#1147]
import paddle
import paddle.nn as nn
import paddle.nn.functional as F

from visualdl import LogWriter

class MyNet(nn.Layer):
    def __init__(self):
        super(MyNet, self).__init__()
        self.conv1 = nn.Conv2D(
            in_channels=1, out_channels=20, kernel_size=5, stride=1, padding=2)
        self.max_pool1 = nn.MaxPool2D(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2D(
            in_channels=20,
            out_channels=20,
            kernel_size=5,
            stride=1,
            padding=2)
        self.max_pool2 = nn.MaxPool2D(kernel_size=2, stride=2)
        self.fc = nn.Linear(in_features=980, out_features=10)

    def forward(self, inputs):
        x = self.conv1(inputs)
        x = F.relu(x)
        x = self.max_pool1(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = self.max_pool2(x)
        x = paddle.reshape(x, [x.shape[0], -1])
        x = self.fc(x)
        return x

net = MyNet()
with LogWriter(logdir="./log/graph_test/") as writer:
    writer.add_graph(
        model=net,
        input_spec=[paddle.static.InputSpec([-1, 1, 28, 28], 'float32')],
        verbose=True)

>>> Failed to save model graph, error: ''

Name: paddlepaddle
Version: 2.3.2

Name: visualdl
Version: 2.3.0

**Comment by CaoChensy** [comment]
Windows jupyter notebook 环境

**Comment by rainyfly** [comment]
收到您的反馈，这边复现一下看看原因

**Comment by rainyfly** [comment]
我们在下一个小版本如果add_graph失败会raise出异常，不好意思

**Comment by ZYNORl** [comment]
> 我们在下一个小版本如果add_graph失败会raise出异常，不好意思

我也遇到了这种情况，请问那个版本是可以的，paddle_cpu和visualDL版本是多少

**Comment by rainyfly** [comment]
你好，这边发现windows机器会报错主要还是代码里有一个小bug，没有测试跨平台的兼容性问题，可以考虑改一下这行代码，https://github.com/PaddlePaddle/VisualDL/pull/1244 。 这个修复会在下一个小版本发布。

**Comment by rainyfly** [comment]
可以通过 import visualdl, visuadl.__path__ 查看pacakage的安装路径，然后修改对应的文件就行。

**Comment by rainyfly** [comment]
已修复。
