### ISSUE TITLE
visualdl --logdir=log --host=0.0.0.0 'visualdl' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 这个怎么解决？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/VisualDL#1167]
visualdl --logdir=log --host=0.0.0.0
'visualdl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rainyfly** [comment]
这个是由于找不到visualdl的执行文件导致的，请先看看使用python能不能 import 进行，import visualdl没有问题的话，说明visualdl这个package已经装上了，再看看which visualdl，如果没有这个可执行文件，说明visualdl这个执行脚本由于某种原因没有进入bin目录，或者那个bin目录没有再环境变量PATH中。试试用pip卸载再重装一下

**Comment by MurrayHubert** [comment]
估计VisualDL应该是**百度外包**的，做的质量太low了，和TensorBoard可靠性没法比。

**Comment by nissansz** [comment]
pip uninstall visualdl
pip install --upgrade --pre visualdl  -i https://mirror.baidu.com/pypi/simple
卸载visualdl,再次安装可以用了
