### ISSUE TITLE
用网页版启动，浏览器分别报490和493错误

### ISSUE THREAD

**Issue by abcdefghHIM** [PaddlePaddle/VisualDL#1184]
用Edge打开页面后，报服务器错误，控制台显示490
![QQ截图20221211135825](https://user-images.githubusercontent.com/55306203/206888900-f3bce8c9-2fcc-4111-b914-78924a3100fa.png)
![QQ截图20221211135836](https://user-images.githubusercontent.com/55306203/206888907-8d7f0982-87f0-43f2-b702-20a5834cd1ce.png)
用谷歌打开后，页面空白，控制台显示493
![QQ截图20221211135815](https://user-images.githubusercontent.com/55306203/206888929-d1632bef-9635-4a2e-a983-e7bf8747d4c0.png)

**Comment by rainyfly** [comment]
后端服务器控制台有报错么，读取的日志文件是什么内容呢

**Comment by abcdefghHIM** [comment]
![BaiduShurufa_2022-12-12_22-26-51](https://user-images.githubusercontent.com/55306203/207072199-c23c9259-bd44-49d5-b271-a15721834b9a.png)
![BaiduShurufa_2022-12-12_22-27-17](https://user-images.githubusercontent.com/55306203/207072310-d4ca9a90-736f-40dd-bc17-19b1307bd51d.png)
日记里存的训练中的loss，前几次能正常打开，日记也没有问题
![BaiduShurufa_2022-12-12_22-48-53](https://user-images.githubusercontent.com/55306203/207076103-b17aea45-0d09-49ee-b56d-e307def5b209.png)

**Comment by abcdefghHIM** [comment]
> 后端服务器控制台有报错么，读取的日志文件是什么内容呢

![BaiduShurufa_2022-12-12_22-26-51](https://user-images.githubusercontent.com/55306203/207078360-947e2669-f837-4514-a45f-19bd6ef19cdf.png)
![BaiduShurufa_2022-12-12_22-27-17](https://user-images.githubusercontent.com/55306203/207078430-8d62d3c7-aeda-427d-9261-77c2d8520351.png)
![BaiduShurufa_2022-12-12_22-48-53](https://user-images.githubusercontent.com/55306203/207078534-95966e11-bfeb-46d3-beac-6224db00b1ae.png)
前一次可以正常打开，后面就不行了

**Comment by rainyfly** [comment]
如果一个目录里有多个日志文件，默认只会解析目录里那个最新的文件的

**Comment by abcdefghHIM** [comment]
好的，问题解决了
