### ISSUE TITLE
Scalar need to check different data ranges

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#12]
some negative value.

**Comment by varunarora** [comment]
@Superjomn So it needs to render negative values?

**Comment by Superjomn** [comment]
yes, I think scalar just draw a line, no matter negative or positive.

There seem some bugs originally, haven't tested negative value on the current SDK.

**Comment by jetfuel** [comment]
![screen shot 2018-02-06 at 11 11 08 am](https://user-images.githubusercontent.com/1093725/35878865-7556ba42-0b2e-11e8-9a68-fa3e9525fab7.png)

@Superjomn Don't we already show the negative value?
