### ISSUE TITLE
Python3.10版本以后对requests库进行调整，collections中不能直接调用方法Mapping，MutableMapping

### ISSUE THREAD

**Issue by mrcangye** [PaddlePaddle/VisualDL#1227]
由于Python3.10版本以后对requests库进行调整，collections中不能直接调用方法Mapping，MutableMapping。所以是否可以针对其进行更新？否则需要修改相应代码才能在高版本python上使用visualdl

**Comment by rainyfly** [comment]
已收到反馈，谢谢

**Comment by mrcangye** [comment]
> 已收到反馈，谢谢

要是没空，等后面我有空来整一个？

**Comment by rainyfly** [comment]
估计得等到发下个小版本的时候看看能不能支持一下，还需要考虑一下对python3.7等版本的兼容问题，如果您愿意帮忙的话，也欢迎提个PR，我们这边review没问题的话，会进行合入

**Comment by mrcangye** [comment]
报错日志记录：

Traceback (most recent call last)
  File CUsersChenLoong.condaenvsvisualDLfixlibrunpy.py, line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File CUsersChenLoong.condaenvsvisualDLfixlibrunpy.py, line 86, in _run_code
    exec(code, run_globals)
  File CUsersChenLoong.condaenvsvisualDLfixScriptsvisualdl.exe__main__.py, line 4, in module
  File CUsersChenLoong.condaenvsvisualDLfixlibsite-packagesvisualdlserverapp.py, line 39, in module
    from visualdl.component.inference.fastdeploy_server import create_fastdeploy_api_call
  File CUsersChenLoong.condaenvsvisualDLfixlibsite-packagesvisualdlcomponentinferencefastdeploy_server.py, line
 27, in module
    from .fastdeploy_client.client_app import create_gradio_client_app
  File CUsersChenLoong.condaenvsvisualDLfixlibsite-packagesvisualdlcomponentinferencefastdeploy_clientclient_ap
p.py, line 18, in module
    from .http_client_manager import get_metric_data
  File CUsersChenLoong.condaenvsvisualDLfixlibsite-packagesvisualdlcomponentinferencefastdeploy_clienthttp_client_manager.py, line 21, in module
nt_manager.py, line 21, in module
    from attrdict import AttrDict
  File CUsersChenLoong.condaenvsvisualDLfixlibsite-packagesattrdict__init__.py, line 5, in module
    from attrdict.mapping import AttrMap
  File CUsersChenLoong.condaenvsvisualDLfixlibsite-packagesattrdictmapping.py, line 4, in module
    from collections import Mapping
ImportError cannot import name 'Mapping' from 'collections' (CUsersChenLoong.condaenvsvisualDLfixlibcollections__in
it__.py)

**Comment by rainyfly** [comment]
已修复。
