### ISSUE TITLE
VisualDL在FastDeploy 客户端请求时报错

### ISSUE THREAD

**Issue by LouisHeck** [PaddlePaddle/VisualDL#1240]
1. 环境
【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-1.0.5
【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.4 CUDNN 8.3
【编译语言】： C++ / Python(3.7或3.8等）
2. 问题日志及出现问题的操作流程
fastdeploy容器中模型服务启动正常，容器内调用正常
![image](https://user-images.githubusercontent.com/38588261/227822434-c337ae2e-7d1a-4a41-983f-d4e3e5b7ffcd.png)
![image](https://user-images.githubusercontent.com/38588261/227822453-b933ae91-7d1e-451f-8d8b-0ca6ed5d48bf.png)

3.【VisualDL打开客户端时，提交服务请求报错】
![image](https://user-images.githubusercontent.com/38588261/227822477-9612b40c-1486-48d3-a2aa-90005807cd11.png)

**Comment by rainyfly** [comment]
你好，我感觉是gradio的版本太高了导致的，这边写客户端时为了能够实现自动在gradio的客户端页面上帮助用户进行填写server,port等信息，有点和gradio耦合的太深了，现在gradio升级了可能导致出了点问题，你先试下降级一下gradio到3.11.0试试，pip install gradio == 3.11.0  。由于fastdeployserver那边模型经常升级，返回的数据格式可能会偶尔有更新，VisualDL只有一个小版本才更新一次，目前这个client的鲁棒性和适用性可能不是很好，之后我会想办法怎么解决一下这个问题

**Comment by LouisHeck** [comment]
> 你好，我感觉是gradio的版本太高了导致的，这边写客户端时为了能够实现自动在gradio的客户端页面上帮助用户进行填写server,port等信息，有点和gradio耦合的太深了，现在gradio升级了可能导致出了点问题，你先试下降级一下gradio到3.11.0试试，pip install gradio == 3.11.0 。由于fastdeployserver那边模型经常升级，返回的数据格式可能会偶尔有更新，VisualDL只有一个小版本才更新一次，目前这个client的鲁棒性和适用性可能不是很好，之后我会想办法怎么解决一下这个问题

降低版本后可以使用
