### ISSUE TITLE
启动服务，使用curl请求报302问题，请问正常吗？

### ISSUE THREAD

**Issue by Dinglq23** [PaddlePaddle/VisualDL#1241]
![image](https://user-images.githubusercontent.com/29702683/228421446-cc4cbb4e-8276-4da9-ba44-ea4f84bf98a0.png)
![image](https://user-images.githubusercontent.com/29702683/228421591-e96f58c0-8c13-46ae-8cbc-665b98d9bc30.png)
![image](https://user-images.githubusercontent.com/29702683/228421626-e1b649b5-eb98-448c-804d-fc2b9ed7f97b.png)

**Comment by rainyfly** [comment]
302应该是正常的，后面访问出现500不太正常，可以用浏览器访问一下看看能打开么，然后打开一下浏览器的调试模式，看看网络的请求看看

**Comment by Dinglq23** [comment]
因为是远程服务器，并且那台是内网服务器，公网跳板机是另一台，所以配了nginx转发服务，浏览器访问调试模式情况如下，visualDL的图标出来了，但是页面是空白页面，有报错信息，麻烦帮忙再看看
![p1](https://user-images.githubusercontent.com/29702683/228448677-0ad7601d-2c60-4f7c-8488-6ac22e55cfff.png)

**Comment by Difers** [comment]
> 因为是远程服务器，并且那台是内网服务器，公网跳板机是另一台，所以配了nginx转发服务，浏览器访问调试模式情况如下，visualDL的图标出来了，但是页面是空白页面，有报错信息，麻烦帮忙再看看 ![p1](https://user-images.githubusercontent.com/29702683/228448677-0ad7601d-2c60-4f7c-8488-6ac22e55cfff.png)

同样出现了500的问题，可以问下怎么解决的吗？

**Comment by Dinglq23** [comment]
最终问题还是nginx配置的问题；在浏览器上访问，重定向是由浏览器执行的，配置nginx的时候注意一定要是nginx能拦截的状态，否则浏览器重定向之后，相当于是一个无效请求，nginx没有拦截到，也就无法往后面转。
不需要去管服务器上curl请求的返回，302就表示重定向，500这个可能也是手动拼路径有问题，实际服务是正常的，只要nginx配置正确就可以正常访问

**Comment by Difers** [comment]
> 最终问题还是nginx配置的问题；在浏览器上访问，重定向是由浏览器执行的，配置nginx的时候注意一定要是nginx能拦截的状态，否则浏览器重定向之后，相当于是一个无效请求，nginx没有拦截到，也就无法往后面转。 不需要去管服务器上curl请求的返回，302就表示重定向，500这个可能也是手动拼路径有问题，实际服务是正常的，只要nginx配置正确就可以正常访问

谢谢解答~
