### ISSUE TITLE
FASTDEPLOY_CLIENT加载不出来

### ISSUE THREAD

**Issue by Cheng-x-c** [PaddlePaddle/VisualDL#1247]
## 我是在docker中搭建的VisualDL，不能使用127.0.0.1访问，想过用nginx代理过去，但是FASTDEPLOY_CLIENT端口是变化的
如图：
![image](https://user-images.githubusercontent.com/59717369/232723759-c0ecd6a9-ca3d-4d48-9e90-9d34513bdf9e.png)

![image](https://user-images.githubusercontent.com/59717369/232723651-8f345cdf-03c3-4c3e-bb8e-6eeee4407801.png)

**Comment by rainyfly** [comment]
不是变化的，可以升级一下visualdl，然后访问visualdl时候，使用你启动的--host所指定的ip， --port所指定的端口，这个变化的链接可以不用管。
