### ISSUE TITLE
2.5.3版本不指定--logdir参数只显示‘static_graph’组件，不显示'x2paddle', 'fastdeploy_server', 'fastdeploy_client'这三个名称代表的组件

### ISSUE THREAD

**Issue by BingerOne** [PaddlePaddle/VisualDL#1259]

**Comment by rainyfly** [comment]
符合预期的，因为2.5.0版本加入了上述功能之后，默认开起的状态下会严重影响启动速度，而且对于macos并不支持x2paddle的功能，而绝大多数用户只是希望使用VDL来查看图表，基于上述考虑，2.5.3默认不开启这些功能。

**Comment by BingerOne** [comment]
文档没有更新，代码里面也没有说明
![image](https://github.com/PaddlePaddle/VisualDL/assets/32097973/967e366f-4a3d-4b39-a79a-5388e7ecfe45)
