### ISSUE TITLE
mode list is error when have two mode and mode have same prefix

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/VisualDL#128]
### pass_name
- trainbatch
- trainpass

![image](https://user-images.githubusercontent.com/3048612/34906076-9819b08e-f8a0-11e7-96ef-f281ea5a3bd9.png)

**Comment by varunarora** [comment]
@Superjomn Was this resolved?

**Comment by Superjomn** [comment]
It is fixed.
