### ISSUE TITLE
Add support for Python 3 

### ISSUE THREAD

**Issue by aa12356jm** [PaddlePaddle/VisualDL#175]
看了一下https://pypi.python.org的轮子，发现只有python2.7，作者可否支持python3?非常感谢提供这么好的工具

**Comment by Superjomn** [comment]
恩，python3在后面会支持，应该只是打包的工作

**Comment by Superjomn** [comment]
@daming-lu 可否帮看下这个python3打包

**Comment by jacquesqiao** [comment]
应该是用Python3的环境打个包就行了

**Comment by Superjomn** [comment]
因为 Pybind 的缘故，比想像中要复杂，周末再试试

**Comment by aa12356jm** [comment]
@Superjomn python3可以了吗？可以的话，麻烦您提醒一下哈，非常感谢

**Comment by Superjomn** [comment]
抱歉，python3支持应该要等到下一个小版本了。

pip+pybind 有一些麻烦。

**Comment by TuXiaokang** [comment]
@Superjomn 下个版本大致时间能透露吗，期待 ing

**Comment by thatdevin** [comment]
也在期待中

**Comment by nbcc** [comment]
同，工具链用 python 3 方便些。

**Comment by oraoto** [comment]
我改了一个[Python 3版本的](https://github.com/oraoto/visualDL/tree/feature-py3)，已经可以跑起keras的demo，再完善一下就发个PR。

**Comment by Superjomn** [comment]
@daming-lu @jetfuel  可以帮看下

**Comment by jacquesqiao** [comment]
@oraoto 太赞了，期待
