### ISSUE TITLE
time subtitle has a  wrong showing format

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/VisualDL#176]
when showing the scalar graph, the x-axis time label show in the wrong format. Even the vl_stratch demo.

**Comment by Superjomn** [comment]
Can you give a screenshot? and highlight the bug? @dzhwinter

**Comment by dzhwinter** [comment]
![image](https://user-images.githubusercontent.com/6687176/35046834-264f37cc-fbd3-11e7-8e89-20a5dc97255b.png)
