### ISSUE TITLE
Hope to support chainer framework

### ISSUE THREAD

**Issue by machanic** [PaddlePaddle/VisualDL#177]
chainer is excellent framework which is built on pure python and is share the same idea with PyTorch, (actually , pytorch copy chainer's idea).
Hope to support chainer framework, Thanks.

**Comment by Superjomn** [comment]
It supports any pure python framework, just use the python SDK.

In fact, it is not bound to the deep learning tasks, any python/C++ application with a `for-loop` can use it.

for example, the `scalar` component, `add_record(x, y)` simply draw a scalar on `(x,y)` in European space.

```python
lw = LogWriter('./somedir', sync_cycle=30)
# create a scalar component called `xxx` in "default" mode
with lw.mode("default") as logger:
     scalar0 = logger.scalar("xxx")

# draw 100 scalars
for x in range(100):
    scalar0.add_record(x, 2*x)
```

It should draw a straight line.
