### ISSUE TITLE
failed to import at pyenv's user

### ISSUE THREAD

**Issue by Qero** [PaddlePaddle/VisualDL#179]
I install vissualdl by pip, but I get the fatal error when import it in my pyenv local environment
```Python 2.7.14 (default, Jan 18 2018, 14:53:56)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import visualdl
Fatal Python error: PyThreadState_Get: no current thread
[1]    60591 abort      python
```

Then, I found the core.so in versions/2.7.14/lib/python2.7/site-packages/visualdl, and it is depends on the /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python, it isn't match my  python environment.
```
➜  visualdl git:(master) otool -L core.so
core.so:
	@rpath/core.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

Now it works, but I must change dependence by hand.
```
➜  visualdl git:(master) install_name_tool -change /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python /Users/*****/.pyenv/versions/2.7.14/lib/libpython2.7.dylib core.so
```
-------------------------------------------------------------------------------
Moreover, u may not find .pyenv/versions/2.7.14/lib/libpython2.7.dylib, u should rebuild ur python environment with "--enable-shared". For example
```
export PYTHON_CONFIGURE_OPTS="--enable-shared"
pyenv install 2.7.14
```

**Comment by jacquesqiao** [comment]
can you try to clone the code and build it locally?

**Comment by Qero** [comment]
Yes, I have tried to build visualdl with my local python environment, but I encountered the same problem as https://github.com/PaddlePaddle/VisualDL/issues/170.
macOS High Sierra 10.13.2
GNU Make 3.81
cmake 3.10.1
python 2.7.14

**Comment by jacquesqiao** [comment]
Ok, I will try to fix this problem, thank you~

**Comment by Superjomn** [comment]
We will try to add CMake flags to specify the paths of python lib and header files. 

Most include errors are due to the Pybind compiling with an incompatible python environment. 

Will try later in the weekend and update on this issue.

**Comment by cs2be** [comment]
One possible reason is when you run cmake, it locates the incorrect python library for your python interpeter.  You can see this in the console:

```
> cmake ..
...
-- Found PythonInterp: /Users/thuan/baiduResearch/cs2be/VisualDL/vevn/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2.7") 
```

Default macOS python is different from those supplied by brew or macports.  A work around to this issue is to configure the PYTHON_LIBRARY and PYTHON_INCLUDE_DIR when running CMAKE:

```
cmake -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7 ..
```

**Comment by PeterPanZH** [comment]
close outdated issue.
