### ISSUE TITLE
图表的刷新间隔可以自己修改吗？

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/VisualDL#181]
当前是15s
如何修改为5s呢

**Comment by BingBlog** [comment]
Thanks for the feedback. This feature is in our plan. 
However, we found in development, if you want to render a large amount of data in the map, refresh too fast, the browser response will be slower. 
We will still provide this function as soon as possible.

**Comment by BingBlog** [comment]
duplicate width #9. This one close.
