### ISSUE TITLE
支持LogWriter的加载与续写

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/VisualDL#185]
因为当前只支持一个logdir的展现，遇到多个独立的训练进程想往一个log写需要展现的数据时，后启动的会覆盖之前的logdir下的storage.meta。如果在初始化logWriter时，发现下面有storage.meta的话不覆盖，而是在基础上续写就好了。

**Comment by Superjomn** [comment]
嗯，可以考虑在第二版上加这个功能
