### ISSUE TITLE
[ERROR 2018-01-18 22:56:20,830 lib.py:212] Unexpected error: <type 'exceptions.RuntimeError'>

### ISSUE THREAD

**Issue by burness** [PaddlePaddle/VisualDL#186]
Hi Paddler:

During the train parse of the DeepFM, I add the LOSS and AUC to the logwriter and I load them to visualdl. 
![image](https://user-images.githubusercontent.com/3112825/35104591-3f83c542-fca4-11e7-81c2-64256da4969a.png)

But I see the log here, it get an error "CHECK failed: (index) < (current_size_)":
![image](https://user-images.githubusercontent.com/3112825/35104044-a43223b4-fca2-11e7-9361-7f5fc587386a.png)

**Comment by jacquesqiao** [comment]
Are you opening multiple browser pages for this service at the seem time? If so, we have some bugs and will be fixed soon. 

On the other way, the wrong time format in the scalar window has been fixed, will upload a new version today~

**Comment by Superjomn** [comment]
That's OK for this kind of runtime exception.  The server will have some Read/Write IO conflicts with the Writer (which write to the same ProtoBuf file) and will retry several times and recover service latter.

Just a temporary runtime error and can be ignored.

**Comment by burness** [comment]
Ok, Thanks chunwei and longfei.

2018-01-19 13:16 GMT+08:00 Yan Chunwei <notifications@github.com>:
