### ISSUE TITLE
Job flow chart like ray webui

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#187]
- draw the computation information of kernals
- draw the schedule of distributed system.

**Comment by jacquesqiao** [comment]
![image](https://user-images.githubusercontent.com/3048612/35138995-15de1642-fd2c-11e7-9137-6017342e9e0c.png)
http://ray.readthedocs.io/en/latest/webui.html
do you mean this one?

**Comment by Superjomn** [comment]
yes
