### ISSUE TITLE
Segmentation fault on using LogWriter to MNIST (GPU) example on Docker

### ISSUE THREAD

**Issue by leanna62** [PaddlePaddle/VisualDL#190]
原始代码路径：https://github.com/dzhwinter/benchmark/blob/master/fluid/mnist.py
参考vdl_scratch.py中scalar部分进行添加。
问题如下：
*** Aborted at 1516348104 (unix time) try "date -d @1516348104" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x180) received by PID 1285 (TID 0x7fb467080700) from PID 384; stack trace: ***
    @     0x7fb466c5f390 (unknown)
    @     0x7fb441027930 std::_Hashtable<>::_M_find_before_node()
    @     0x7fb441012e18 std::_Hashtable<>::_M_find_node()
    @     0x7fb44100a8a6 std::_Hashtable<>::find()
    @     0x7fb440ffefbd std::unordered_map<>::find()
    @     0x7fb440ff6ca0 pybind11::detail::internals::get_base()
    @     0x7fb440ff7645 pybind11::detail::make_new_python_type()
    @     0x7fb440ffb037 pybind11::detail::generic_type::initialize()
    @     0x7fb44100028c _ZN8pybind116class_IN8visualdl9LogReaderEJEEC2IJEEENS_6handleEPKcDpRKT_
    @     0x7fb440fdea81 pybind11_init()
    @     0x7fb440fddd85 pybind11_init_wrapper()
    @     0x7fb440fddcdf initcore
    @           0x52218c _PyImport_LoadDynamicModule
    @           0x4afbdd (unknown)
    @           0x4af7e8 PyImport_ImportModuleLevel
    @           0x4b0f58 (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4ce540 PyEval_CallObjectWithKeywords
    @           0x4c73a6 PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4c24a9 PyEval_EvalCode
    @           0x4c05bb PyImport_ExecCodeModuleEx
    @           0x4bd68e (unknown)
    @           0x4afbdd (unknown)
    @           0x4af361 PyImport_ImportModuleLevel
    @           0x4b0f58 (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4ce540 PyEval_CallObjectWithKeywords
    @           0x4c73a6 PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4c24a9 PyEval_EvalCode
    @           0x4c05bb PyImport_ExecCodeModuleEx
Segmentation fault

**Comment by Superjomn** [comment]
是自己搭建的docker吗？　ubuntu么，系统版本和python版本是啥？

**Comment by leanna62** [comment]
不好意思回复晚了
系统版本：Ubuntu 16.04.3 LTS
python版本：Python 2.7.3  [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2

**Comment by Superjomn** [comment]
应该还是 pip 打包的问题。 

可以试下源码编译安装，应该是自动化的。

**Comment by varunarora** [comment]
@jetfuel Could you kindly give us an English description of this issue?

**Comment by jetfuel** [comment]
@varunarora 
Title: Running mnist gpu version through docker, Will get error when adding log writing module.

source code: https://github.com/dzhwinter/benchmark/blob/master/fluid/mnist.py
Use vdl_scratch.py as the reference to add Scalar log.

**Comment by varunarora** [comment]
Thank you @jetfuel!

**Comment by ZeyuChen** [comment]
We use pure python to refactor VisualDL, so there is no such C++ issues.
