### ISSUE TITLE
add 3-D to Scalar

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/VisualDL#197]
After talking to Yibing from DeepSpeech team, it would be better if VisualDL could support 3-D real-time rendering like below:

<img width="1792" alt="screen shot 2018-01-22 at 4 58 14 pm" src="https://user-images.githubusercontent.com/5635322/35212585-98f4ebda-ff95-11e7-94f9-c01688dda484.png">

**Comment by varunarora** [comment]
@daming-lu That's not scalar then anymore, now is it? Bringing up an old suggestion, but are you open to an alternative set of header tab names, to not exactly mimic you-know-what

Also, link to the page whose reference you have mentioned is here: https://github.com/PaddlePaddle/DeepSpeech

**Comment by PeterPanZH** [comment]
close outdated issue.
