### ISSUE TITLE
用PIP安装VisualDL遇到问题

### ISSUE THREAD

**Issue by KeyKy** [PaddlePaddle/VisualDL#198]
visualDL: command not found

**Comment by jacquesqiao** [comment]
try to start Python and run
```python
import visualdl
```

**Comment by KeyKy** [comment]
我已经安装成功了，import visualdl没有问题，好像就是没有visualDL这个可执行文件。

**Comment by Superjomn** [comment]
pip 打包目前只适配了 mac 和 ubuntu，还没有全环境测试。 

如果还有问题，可以试下源码编译安装，依赖环境应该会自动下载。

**Comment by KeyKy** [comment]
OK
