### ISSUE TITLE
Graph Design

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/VisualDL#2]
- [x] add onnx to VisualDL #34 
- [x] add edge in Graph data format design https://github.com/PaddlePaddle/VisualDL/pull/32
- [x] impl edge in Graph API

**Comment by varunarora** [comment]
@jacquesqiao Can you give us an update on the status of this and what needs work (apart from the click interactions stuff)?

**Comment by jetfuel** [comment]
Close the ticket. This is implemented.
