### ISSUE TITLE
STOPPED but still send request to backend

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#201]
- need more test
- in my task, it will refresh the data even after STOPING, every 30s.

**Comment by varunarora** [comment]
@Superjomn Could you kindly provide some more clarity / context for this issue?

**Comment by jetfuel** [comment]
@Superjomn @varunarora  I used the scratch_log as my testing log. I do see extra request sent to the backend server. But I don't see any other requests afterward. Is this expected?

**Comment by Superjomn** [comment]
yes, that should be the right logic.
