### ISSUE TITLE
Scalar graph inconsistencies

### ISSUE THREAD

**Issue by reminisce** [PaddlePaddle/VisualDL#202]
感谢开发者提供这个工具，编译安装方便快捷，简单易用，就是前端还有不少可以改进用户体验的地方。比如下面这个图，有时候accuracy曲线会下降到零，过一会儿又恢复正常。
这是我的code，请看一下是不是有用错的地方。
我是从source编译安装，在MacOS上运行的。
```python
logdir = "./tmp"
logger = LogWriter(logdir, sync_cycle=10)

# mark the components with 'train' label.
with logger.mode("train"):
    train_acc = logger.scalar("accuracy")

with logger.mode('valid'):
    valid_acc = logger.scalar("accuracy")

# training code 此处省略一万字

train_acc.add_record(epoch, train_acc)
valid_acc.add_record(epoch, valid_acc)
```
![image](https://user-images.githubusercontent.com/4978794/35317769-2cff5192-008d-11e8-91a0-6608dba90376.png)

**Comment by varunarora** [comment]
@jetfuel Could you kindly help me here with a translation? Or @reminisce, if you see this before.

**Comment by jetfuel** [comment]
@varunarora The translation goes
Thank you for the tool, It's simple and easy to run. There are just some frontend improvements we can work on. 
Take the following graph as an example, sometimes the accuracy curve would drop to zero, and back to normal after a while.
Here is my code snippet, Please take a look if there is any miss-configuration. 
I compiled the source code and installed from there. Ran on MacOS

**Comment by varunarora** [comment]
Thank you very much, @jetfuel!

**Comment by PeterPanZH** [comment]
close outdated issue.
