### ISSUE TITLE
Scalar graphs can't render both 0 records and very large # of records

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#203]
- 0 records will result in a blank tablet, that's ok, but frontend will yield an error
- to0 many records(10000 for example) will make this scalar dead
   - TODO add reservoir sample in storage
   - TODO frontend should tolerate 0 records

**Comment by nickyfantasy** [comment]
Empty records issue resolved in https://github.com/PaddlePaddle/VisualDL/pull/298

**Comment by ZeyuChen** [comment]
We upgrade the sampling algorithm to avoid frontend dead caused by large amount scalar data.
