### ISSUE TITLE
Smooth line shows in wrong fromat

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/VisualDL#208]
![image](https://user-images.githubusercontent.com/6687176/35341118-e018d834-015f-11e8-9bf4-29ec4cf711df.png)

**Comment by Superjomn** [comment]
you can try to turn off the "smooth", check whether the scalar gets normal, and update the screenshot here.

It is hard to reproduce the bug in my environment.

**Comment by varunarora** [comment]
@dzhwinter Do you happen to have the logs for this training so we could reproduce? Or perhaps tell us if this is from a known tutorial-ish example?

**Comment by PeterPanZH** [comment]
close outdated issue.
