### ISSUE TITLE
how to generate a ONNX proto or the network graph

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/VisualDL#209]
In demo` vdl_scratch.py`  writed:
```
    '''
    This is a scratch demo, it do not generate a ONNX proto, but just download an image
    that generated before to show how the graph frontend works.

    For real cases, just refer to README.
    '''
```
but I do not find in README, is there any specific examples ?

**Comment by Superjomn** [comment]
Sorry, we forget to add the document.

Translate the model to ONNX proto, and set the argument `--model_pb` to the Protobuf file.

for exmple:

```
visualDL --logdir xxx --model_pb xxx.pb
```

that should work.

**Comment by veridone** [comment]
I want to know how to create the xxx.pb in paddle

**Comment by Superjomn** [comment]
Paddle to ONNX tool is on the way~ 

Currently the graph component only supports ONNX format.

**Comment by Superjomn** [comment]
reference #212

**Comment by qinghuasun** [comment]
@Superjomn After run the demo pytorch_cifar10.ipynb, and generate a graph using dummpy, but can not display graph in the browser.   How can i  solve the problem? Thanks

onnx as following:
graph(%1 : Float(8, 3, 32, 32)
      %2 : Float(6, 3, 5, 5)
      %3 : Float(6)
      %4 : Float(16, 6, 5, 5)
      %5 : Float(16)
      %6 : Float(120, 400)
      %7 : Float(120)
      %8 : Float(84, 120)
      %9 : Float(84)
      %10 : Float(10, 84)
      %11 : Float(10)) {
  %13 : UNKNOWN_TYPE = Conv[kernel_shape=[5, 5], strides=[1, 1], pads=[0, 0, 0, 0], dilations=[1, 1], group=1](%1, %2), uses = [[%14.i0]], scope: Net/Conv2d[conv1];
  %14 : Float(8, 6, 28, 28) = Add[broadcast=1, axis=1](%13, %3), uses = [%15.i0], scope: Net/Conv2d[conv1];
  %15 : Float(8, 6, 28, 28) = Relu(%14), uses = [%16.i0], scope: Net;
  %16 : Float(8, 6, 14, 14) = MaxPool[kernel_shape=[2, 2], pads=[0, 0], strides=[2, 2]](%15), uses = [%17.i0], scope: Net;
  %18 : UNKNOWN_TYPE = Conv[kernel_shape=[5, 5], strides=[1, 1], pads=[0, 0, 0, 0], dilations=[1, 1], group=1](%16, %4), uses = [[%19.i0]], scope: Net/Conv2d[conv2];
  %19 : Float(8, 16, 10, 10) = Add[broadcast=1, axis=1](%18, %5), uses = [%20.i0], scope: Net/Conv2d[conv2];
  %20 : Float(8, 16, 10, 10) = Relu(%19), uses = [%21.i0], scope: Net;
  %21 : Float(8, 16, 5, 5) = MaxPool[kernel_shape=[2, 2], pads=[0, 0], strides=[2, 2]](%20), uses = [%22.i0], scope: Net;
  %22 : Float(8, 400) = Reshape[shape=[-1, 400]](%21), uses = [%25.i0], scope: Net;
  %25 : Float(8, 120) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%22, %6, %7), uses = [%26.i0], scope: Net/Linear[fc1];
  %26 : Float(8, 120) = Relu(%25), uses = [%29.i0], scope: Net;
  %29 : Float(8, 84) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%26, %8, %9), uses = [%30.i0], scope: Net/Linear[fc2];
  %30 : Float(8, 84) = Relu(%29), uses = [%33.i0], scope: Net;
  %33 : Float(8, 10) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%30, %10, %11), uses = [%0.i0], scope: Net/Linear[fc3];
  return (%33);
}

**Comment by ArtyZe** [comment]
@Superjomn 
If I got paddle model from paddlehub so I don't have log, now what can I do to visualise the paddle model?
