### ISSUE TITLE
CMakeLists doesn't compile tests on release

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/VisualDL#213]
In the CMakeLists.txt, line 55
it says ```# compile test only in release mode```. So it seems we do want to compile tests in release mode.

However, the actual flow shows
``` 
if (NOT ON_RELEASE)
add_executable(vl_test
```
Looks like we only compile tests during development. It doesn't match the description. 

Which one is the correct behavior? Tests on release or tests on development?

**Comment by Superjomn** [comment]
yes, it seems that test is also needed when release.

so this flag can be removed.

**Comment by jetfuel** [comment]
@Superjomn In the CMakefile, the test requires GLOG and GFLAG. But we only include the GLOG and GFLAG in Debug Mode.  

Is there a reason why we only include the GLOG and GFLAG in the Debug Mode?

**Comment by ZeyuChen** [comment]
VisualDL 2.0 is builted by pure python3, so there is no more CMakeList and such compile issues from now on. Issues closed
