### ISSUE TITLE
Histogram styling improvements when very few records

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#226]
reference the screenshot from https://github.com/PaddlePaddle/VisualDL/issues/216

**Comment by varunarora** [comment]
Can you describe what you mean by ugly here and the specific improvement you envision? Just some general pointers in the right direction would be useful.

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/35761384-c9b23fd0-08c2-11e8-988d-82d5048060ce.png)

- the height is fixed, so large margin between three patternings, if relative height, it will be more compact.

**Comment by varunarora** [comment]
Much clearer, thanks for this.

**Comment by PeterPanZH** [comment]
close outdated issue.
