### ISSUE TITLE
the colors of scalar are too similar, hard to distinuish

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#227]
need to carefully tuned.

**Comment by varunarora** [comment]
@Superjomn Do you mean the colors of different curves on a scalar graph and too similar?

**Comment by Superjomn** [comment]
yes.  With four lines in a single scalar, there will be two `red` lines, very hard to distinguish.

**Comment by varunarora** [comment]
Got it - thanks for the clarity @Superjomn!

**Comment by nickyfantasy** [comment]
This is the list we have now:
![pasted image at 2018_03_12 06_05 pm](https://user-images.githubusercontent.com/985199/37377187-adb9aa3e-26e5-11e8-8b90-3b00cdb170fb.png)

**Comment by nickyfantasy** [comment]
The original list does not have a sequence of different Hue contrast, also saturation and brightness level are not consistent, it will be very difficult to distinguish.

**Comment by nickyfantasy** [comment]
Proposed change:

The idea is following:
-keep contrast of Hue level
-alternate between warm/cold colors
-keep saturation and brightness similar
-avoid neutral color like black/gray/white
-avoid color too bright like yellow that obscures by background

<img width="275" alt="screen shot 2018-03-13 at 5 37 31 pm" src="https://user-images.githubusercontent.com/985199/37377261-0e39bcc8-26e6-11e8-83fb-fab6b5f61b18.png">
