### ISSUE TITLE
need a whl package script to build whl on mac/ubuntu

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#231]
currently, the WHL package is built manually, quite trivial and easy to make mistake.

Recently, much bugfix is merged, but no new WHL is updated.

We'd better have a script, to build WHL in the different environments, it seems that the Travis-CI has mac env, but not sure whether it can be used to build WHL.

**Comment by jetfuel** [comment]
@Superjomn Can you share what's our current WHL package build process? I can take the commands and see if we can turn it into a script. I am not familiar with the Pipy. It's best if I can do a dry run with manual commands first.

**Comment by ZeyuChen** [comment]
Now VisualDL 2.0 can install from pypi easily with `pip install visualdl==2.0.0b`, pure python3 so no need to build with difference environments.
