### ISSUE TITLE
Custom scalar graphs layout / order

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#237]
[title: idea from some users: configure the exact position(group) of the components. for example, two scalars(one called train, another is called valid), one can place them side by side. Currently, the components are mixed.]

the four components are split into different HTML pages.

But it is boring to see just one kind of the component in a page.

we can configure different components on a page, and that is much informative and beautiful.

This might be a big improvement compared to TB.

**Comment by PeterPanZH** [comment]
close outdated issue.
