### ISSUE TITLE
Let VDL generate static webpage to publish metrics

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/VisualDL#239]

**Comment by varunarora** [comment]
@daming-lu Should the contents of this static page be identical to a dynamically pooling VDL page, just that the data is loaded non dynamically? What other differences from the regular VDL dashboard should this have? Please share clarity.

@dzhwinter

**Comment by dzhwinter** [comment]
Our needs come out from the status:
1. The flask server web page can only response a few request simultaneously. Use flask as the backend is fragile.
2. Our training dashboard can be shown after the training job is finished, means that we can only provide the static web page without dynamic load or refresh logic.

@cs2be  suggested that we can provide a static web page feature, is it a visible way to solve the two problems above? @daming-lu @varunarora 
Thanks!

**Comment by PeterPanZH** [comment]
close outdated issue.
