### ISSUE TITLE
Interactive ONNX Graphs

### ISSUE THREAD

**Issue by cs2be** [PaddlePaddle/VisualDL#241]
- Make Graph component clickable. Clicking at a node should collapse/expand its internal content

**Comment by varunarora** [comment]
@Superjomn @daming-lu Could you provide more clarity on what this interaction should looks like and what it should enable? Either a reference to another computation graph visualization OR a rough drawing made with Paint-like tools with some text explaining it should suffice.

**Comment by Superjomn** [comment]
I think @daming-lu means that the graph should have some interactions, just like TensorBoard's.

**Comment by varunarora** [comment]
Got it - thanks. If you guys had some unique ideas apart from TensorBoards, do share! We could still use TensorBoard as a baseline.

**Comment by jetfuel** [comment]
@daming-lu I think you are most ahead in this field so I assigned the issue to you at the moment. We can all help.
