### ISSUE TITLE
Audio preview component

### ISSUE THREAD

**Issue by cs2be** [PaddlePaddle/VisualDL#245]

**Comment by varunarora** [comment]
@daming-lu Could you write a few sentences here on what this feature means? So we know what the need is? You could provide links from other frameworks if you have them.

**Comment by jetfuel** [comment]
Currently, I envision that users can use this to evaluate their TTS neural-network. 
After certain steps/iterations, a user can save an "audio message"  generated by the network from a "specified text". Then VisualDL can display those audios accordingly to the steps so the user can listen to the generated audio to determine the performance of the NN.

**Comment by PeterPanZH** [comment]
close outdated issue.
