### ISSUE TITLE
Support Mxnet in R

### ISSUE THREAD

**Issue by harryprince** [PaddlePaddle/VisualDL#252]

**Comment by varunarora** [comment]
@harryprince First of all, it's an honor! Very excited about you and Meghan Markle.

Second, are you asking for a logging integration for when mxnet is written in R? That doesn't seem to be on our current near future plans, unless there is a bigger need from more people.

Everyone else: please respond here with a comment if you are looking for an R API too.

**Comment by PeterPanZH** [comment]
close outdated issue.
