### ISSUE TITLE
On doc for build locally, specify correct path for scratch program

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/VisualDL#255]
`vdl_scratch.py` -> `demo/vdl_scratch.py`

**Comment by jetfuel** [comment]
@varunarora The VisualDL package will install the command `vdl_scratch.py`.
Therefore, a user can execute the `vdl_scratch.py` anywhere. 

I agree with you, this seems confusing. any suggestion?

**Comment by varunarora** [comment]
Ahaa!! Makes sense now.

Yes, well, we should probably not place /visualdl/server in the path, but instead have a symbolic link to `visualDL.py` (note the rename) from a link `visualDL`.

And if the user is expected to run a Python script, it doesn't make sense the have them execute a .py from a dir that's not where they are. Either a linked command approach (`visualDL generate_scratch_data`) or actually copying contents of the demo file from a repo and running it locally.
