### ISSUE TITLE
The image graph demo gif in README is showing Scalar demo as well.

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/VisualDL#257]
The gif of image-demo also shows scalar on the top. This is confusing to the users. They might think the Image graph should display scalar charts as well. 

This is the link to the troubled gif
<img src="https://raw.githubusercontent.com/daming-lu/large_files/master/loss_image.gif" width="60%"/>

**Comment by varunarora** [comment]
Agreed.

**Comment by jetfuel** [comment]
@daming-lu Do you have the original image gif?

**Comment by llxxxll** [comment]
I have the same doubts before running localdemo.

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/VisualDL#image
