### ISSUE TITLE
Binary Record sometimes gets saved with an empty filename

### ISSUE THREAD

**Issue by cs2be** [PaddlePaddle/VisualDL#261]
If user stops a training abruptly (by SIGHUP or SIGKILL), then the binary record filename maybe empty.

**Comment by jetfuel** [comment]
@cs2be What do you mean empty filename? Is the log file created but with a broken filename or the file is not even created?

VisualDL should create the log file associated with log entry upon initializing the log type
For example,  `scalar0 = loggerWriter.scalar("scalars/scalar0")` will create a file `<run_name>%scalars%scalar0` with zero entry right away.

**Comment by PeterPanZH** [comment]
close outdated issue.
