### ISSUE TITLE
VisualDL installation issue in Windows

### ISSUE THREAD

**Issue by ismailadjimera** [PaddlePaddle/VisualDL#269]
Hi guys 
I have an issue when trying to install VisualDL in anaconda. After cloning the git, when I run this code:
pip install --upgrade dist/visualdl-*.whl

I got this error: Requirement dist/visualdl-*.whl looks like a filename, but the file does not exist

**Comment by varunarora** [comment]
Thanks for letting us know, @ismailadjimera. Have you built VDL from source? You need to do that only if you are building VDL locally - if not, you should just use the standard pip package.

May I ask what framework / project you are working on here?

**Comment by ismailadjimera** [comment]
Thanks for answering.
I try to use the standard pip package but I get issues like this one:
TypeError: parse() got an unexpected keyword argument 'transport_encoding' that's why I try to clone the git.

I 'm not working yet on a particulary project here

**Comment by varunarora** [comment]
Ahaa. That's a real bug. Could you perhaps paste some info on what system you are working on? And if you still have a stack trace on you, if you could paste that, it would be awesome!

**Comment by jetfuel** [comment]
`pip install --upgrade dist/visualdl-*.whl` is an example command. The setup.py should create an wheel file under the dist folder. for example: `visualdl-0.0.1a2-cp27-cp27m-macosx_10_13_intel.whl`. Please try to install the wheel with your generated file.

**Comment by ismailadjimera** [comment]
I try to generate the wheel using the setup.py, but it said that I have to install nmp, bash, cmake, unzip which i have done, but I still got the error telling me that I should install unzip.

![capture](https://user-images.githubusercontent.com/20044937/36730806-f78944e4-1bc8-11e8-95cd-e6d20d784da5.PNG)

**Comment by varunarora** [comment]
@ismailadjimera Sorry about that - let us try to replicate this is on Windows and get back to you.
cc: @jetfuel

**Comment by Feywell** [comment]
I have met the same issue.
I try to use Visual DL on windows 10. But there is not pip package in pypi. And I try to build from source.
I need to install cmake, unzip, bash. 
And then , here is another trouble:

>  E:\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\setuptools\dist.py:331: UserWarning: Normalizing '0.0.2
' to '0.0.2'
running bdist_wheel
running build
running build_py
++ pwd
+ TOP_DIR='/mnt/e/集群/文件/Visual DL/VisualDL-develop'
+ FRONTEND_DIR='/mnt/e/集群/文件/Visual DL/VisualDL-develop/frontend'
+ BACKEND_DIR='/mnt/e/集群/文件/Visual DL/VisualDL-develop/visualdl'
+ BUILD_DIR='/mnt/e/集群/文件/Visual DL/VisualDL-develop/build'
+ mkdir -p /mnt/e/集群/文件/Visual DL/VisualDL-develop/build
+ ARG=
+ echo 'ARG: '
ARG:
+ '[' '' = travis-CI ']'
+ build_frontend
+ cd /mnt/e/集群/文件/Visual DL/VisualDL-develop/frontend
+ npm install
: not found/nodejs/npm: 3: /mnt/f/node/nodejs/npm:
: not found/nodejs/npm: 5: /mnt/f/node/nodejs/npm:
/mnt/f/node/nodejs/npm: 6: /mnt/f/node/nodejs/npm: Syntax error: word unexpected (expecting "in")
Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    cmdclass=cmdclass)
  File "E:\Anaconda2\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "E:\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "E:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "E:\Anaconda2\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "E:\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "E:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "E:\Anaconda2\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "E:\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "E:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 66, in run
    subprocess.check_call(cmd, env=env)
  File "E:\Anaconda2\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'build.sh']' returned non-zero exit status 2  

So, how can I fix this trouble?
Thank you!

**Comment by oraoto** [comment]
Currently the build script is tailored for Linux / macOS, you have to run the the commands (cmake, msbuild) manually to build the project. I have tried and failed :(

**Comment by Feywell** [comment]
@oraoto  Thanks for your reply. So, what is the step to build this project manually.
Can you tell me detail?
Thank you again !

**Comment by oraoto** [comment]
```
pip install -r requirements.txt
mkdir build
cd build
cmake -T v141 -DON_RELEASE=ON -DWITH_PYTHON3=ON -DWITH_TESTING=OFF ..
cmake --build .
```

This builds all third-party dependencies except gtest, and fails on VisualDL：

```
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018: “CustomBuild”任务意外失败。 [D:\Projects\VisualDL\build\visualdl\storage\binary_record.vc
xproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018: System.NotSupportedException: 不支持给定路径的格式。 [D:\Projects\VisualDL\build\visualdl\s
torage\bin
ary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String ful

lPath) [D:\Projects\VisualDL\build\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess acces

s, String fullPath, Boolean checkForDuplicates, Boolean needFullPath) [D:\Projects\VisualDL\build\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.CPPTasks.CustomBuild.GetInputs(ITaskItem item) [D:\Projects\VisualDL\

build\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.CPPTasks.CustomBuild.BuildExecutionGraph() [D:\Projects\VisualDL\buil

d\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.CPPTasks.CustomBuild.GenerateCommandLineCommands(CommandLineFormat fo

rmat, EscapeFormat escapeFormat) [D:\Projects\VisualDL\build\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.CPPTasks.VCToolTask.GenerateCommandLineCommands() [D:\Projects\Visual

DL\build\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.Utilities.ToolTask.Execute() [D:\Projects\VisualDL\build\visualdl\sto

rage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute() [D:\Projects\VisualDL\build\visu

aldl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.

Execute() [D:\Projects\VisualDL\build\visualdl\storage\binary_record.vcxproj]
D:\bin\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB4018:    在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\Pro

jects\VisualDL\build\visualdl\storage\binary_record.vcxproj]
```

**Comment by Feywell** [comment]
I try to use VS2015 build like what you said. Also failed as follow:

> 12>------ start build: project: storage, configuration: Debug Win32 ------
12>  Building Custom Rule E:/Visual DL/VisualDL-develop/visualdl/storage/CMakeLists.txt
12>  CMake does not need to re-run because E:/Visual DL/Visual_dl_build/visualdl/storage/CMakeFiles/generate.stamp is up-to-date.
12>  Running C++ protocol buffer compiler on storage.proto
12>E:/Visual DL/VisualDL-develop/visualdl/storage : warning : directory does not exist.
12>  E:/Visual DL/VisualDL-develop/visualdl/storage/storage.proto: No such file or directory
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 1。
13>  sdk.cc
13>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: 
13>E:\Visual DL\VisualDL-develop\visualdl/storage/storage.h(23): fatal error C1083:  cannot open include file: “visualdl/storage/storage.pb.h”: No such file or directory

> 
> 14>cl : 命令行 warning D9002: Ignore the unknown option“-fPIC”
> 14>  pybind.cc
> 14>E:\Visual DL\VisualDL-develop\visualdl/storage/storage.h(23): fatal error C1083: cannot open include file: “visualdl/storage/storage.pb.h”: No such file or directory
> 15>------ skip build: project: ALL_BUILD, configuration: Debug Win32 ------

**Comment by oraoto** [comment]
[Windows support](https://github.com/oraoto/VisualDL/releases) is comming, feel free to provide feedbacks😃.

**Comment by varunarora** [comment]
@oraoto We love your contributions! Thank you so much. Kindly let me know if you wish to connect with us to discuss ideas for VisualDL.

**Comment by oraoto** [comment]
@varunarora I'm not proficient in C++ or Python, just a little contribution to make VisualDL works in my env.

**Comment by nickyfantasy** [comment]
We just released VisualDL for Windows for pip install --upgrade visualdl ! Make sure you have Python 3.6 or above. Thanks @oraoto for contributing
