### ISSUE TITLE
Tensorflow or Keras support / examples

### ISSUE THREAD

**Issue by Chakri-V-V** [PaddlePaddle/VisualDL#291]
Hey , Am trying to install VisualDL but the following message pops up

Collecting visualdl
  Could not find a version that satisfies the requirement visualdl (from versions: )
No matching distribution found for visualdl

When does your support with Tensorflow or Keras start ?

**Comment by varunarora** [comment]
Hey @Chakri-V-V, can you tell us what pip command you used to install `visualdl`?

As far as TF, we don't have anything planned for now. Have you tried TensorBoard?
As far as Keras, @daming-lu, do we have an examples?

**Comment by Chakri-V-V** [comment]
pip install --upgrade visualdl 
is the command am using . Neither is it working on virtual env , not even with the steps mentioned to install locally . 
No , I shall have a look with TensorBoard . Can you help me out with the same .

**Comment by varunarora** [comment]
@Chakri-V-V Are you using Windows? We don't seem to support Windows and old versions of MacOS yet (before 10.12). BUT we should (a) add that note to our documentation, (b) support windows!! Sorry about that.

Here is info on TensorBoard: https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard. Should be easy to get started with `pip install tensorboard`

**Comment by daming-lu** [comment]
@Chakri-V-V : Thanks for your interest in VisualDL. We do support Keras. Please find the tutorial [here](https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/keras/TUTORIAL_CN.md)

**Comment by varunarora** [comment]
@daming-lu Could we have an English version of that tutorial please?

**Comment by jetfuel** [comment]
@varunarora This PR will expose the English version of the Keras tutorial. https://github.com/PaddlePaddle/VisualDL/pull/300

**Comment by varunarora** [comment]
@jetfuel Oh man that is amazing. Here you go @Chakri-V-V: https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/keras/TUTORIAL_EN.md
