### ISSUE TITLE
mac 直接报错

### ISSUE THREAD

**Issue by leaf918** [PaddlePaddle/VisualDL#301]
百度人，本想试用下deep learning visualization的强大（pytorch ），结果 一装，直接报错，先不说什么原因,直接删除了，第三方库兼容问题不想找什么原因。

**Comment by varunarora** [comment]
@jetfuel Translate please?

**Comment by leaf918** [comment]
@varunarora Once I install visualDL on my mac book,and try it ,while Got an error.
I dont wanna paste the error info,I almost cannot error for the first time while try other 3rd part python lib .

**Comment by jetfuel** [comment]
Thank you for trying out the VisualDL and sorry to hear you had some difficulties. If you are willing to help us to improve the user experience. Please kindly let us know what issue you ran into and the error log so we can triage it.
