### ISSUE TITLE
Build error on standard ubuntu

### ISSUE THREAD

**Issue by beleev** [PaddlePaddle/VisualDL#305]
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
![2018-03-09 2 17 42](https://user-images.githubusercontent.com/3471605/37193402-aa17956a-23a4-11e8-9c59-cc1286740962.png)

**Comment by jetfuel** [comment]
Hi @beleev, 
  Thank you for the feedback. It seems that the compiler is not able to parse the pybind sphinx documentation syntax. One way to fix is to switch the C compiler and  CXX compiler to  Clang. That should resolve the error. Sorry for the inconvenience.

**Comment by beleev** [comment]
Thanks, it works
