### ISSUE TITLE
Python fluid import error

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#307]
I import fluid is this line, This is new Fluid:
```python
import paddle.fluid as fluid
```
No error info,only this line:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by varunarora** [comment]
@yeyupiaoling We shall look at this. Is #308 identical?

**Comment by varunarora** [comment]
Hey @yeyupiaoling, have you followed the instructions to install PaddlePaddle on your computer before running this script? VisualDL unfortunately won't install this for you automatically.

These instructions are available on the PaddlePaddle website paddlepaddle.org.

**Comment by yeyupiaoling** [comment]
@varunarora 
Hi, I tried this demo, no problem.
```
visualDL --logdir=scratch_log --port=8080
# visit http://127.0.0.1:8080
```
And my PaddlePaddle is no problem too. 

I think the problem is an new Fluid can't ues in VisualDL,

**Comment by varunarora** [comment]
@yeyupiaoling Got it - we are looking into it!

**Comment by yeyupiaoling** [comment]
@varunarora 
I got newest PaddlePaddle in this doc:http://paddlepaddle.org/docs/develop/documentation/en/build_and_install/build_from_source_en.html

**Comment by varunarora** [comment]
@yeyupiaoling Yeah your probably right, we are talking to the core team right now to see what happened

**Comment by yeyupiaoling** [comment]
@varunarora 
I found import different order will happen different error, like:
```
import paddle.fluid as fluid
from visualdl import LogWriter
```
and
```
from visualdl import LogWriter
import paddle.fluid as fluid
```

**Comment by varunarora** [comment]
That is really strange... @jetfuel probably has some views on this

**Comment by yeyupiaoling** [comment]
@varunarora @jetfuel 
You can try my code:https://github.com/yeyupiaoling/TestVisualDL/blob/master/code/TestVisualDL.py
And you should see these log:
```
*** Aborted at 1521003152 (unix time) try "date -d @1521003152" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x180) received by PID 7134 (TID 0x7f1d5e68a700) from PID 384; stack trace: ***
    @     0x7f1d5e276390 (unknown)
    @     0x7f1d35d07930 std::_Hashtable<>::_M_find_before_node()
    @     0x7f1d35cf2e18 std::_Hashtable<>::_M_find_node()
    @     0x7f1d35cea8a6 std::_Hashtable<>::find()
    @     0x7f1d35cdefbd std::unordered_map<>::find()
    @     0x7f1d35cd6ca0 pybind11::detail::internals::get_base()
    @     0x7f1d35cd7645 pybind11::detail::make_new_python_type()
    @     0x7f1d35cdb037 pybind11::detail::generic_type::initialize()
    @     0x7f1d35ce028c _ZN8pybind116class_IN8visualdl9LogReaderEJEEC2IJEEENS_6handleEPKcDpRKT_
    @     0x7f1d35cbea81 pybind11_init()
    @     0x7f1d35cbdd85 pybind11_init_wrapper()
    @     0x7f1d35cbdcdf initcore
    @           0x51a911 _PyImport_LoadDynamicModule
    @           0x4a4ae1 (unknown)
    @           0x4a7fd5 (unknown)
    @           0x4a3f38 PyImport_ImportModuleLevel
    @           0x4a59e4 (unknown)
    @           0x4a577e PyObject_Call
    @           0x4c5e10 PyEval_CallObjectWithKeywords
    @           0x4be6d7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4b97a6 PyEval_EvalCode
    @           0x4b96df PyImport_ExecCodeModuleEx
    @           0x4b2b06 (unknown)
    @           0x4a4ae1 (unknown)
    @           0x4a4513 PyImport_ImportModuleLevel
    @           0x4a59e4 (unknown)
    @           0x4a577e PyObject_Call
    @           0x4c5e10 PyEval_CallObjectWithKeywords
    @           0x4be6d7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4b97a6 PyEval_EvalCode
```

**Comment by yeyupiaoling** [comment]
@varunarora @jetfuel 
I need help.

**Comment by varunarora** [comment]
@yeyupiaoling We understand and can promise we are on it. Sorry for the delays - we are trying to do what we can.

**Comment by varunarora** [comment]
@yeyupiaoling I think there is some issue with your environment / Paddle build. We have tried it on Mac OSXs 10.12s and Python 2.7 and it seems to be fine, including your script.

Can you give us a little info on your environment? Anything other than the air pollution ;)

**Comment by yeyupiaoling** [comment]
@varunarora 
Mac? My environment is `64 bit Ubuntu 16.04`

**Comment by varunarora** [comment]
@yeyupiaoling Ubuntu is the primary environment in which most people work on Paddle - so you should be fine. Have you tried using it on Docker?

**Comment by varunarora** [comment]
Again, I think something mainly went wrong during the build process.

**Comment by yeyupiaoling** [comment]
@varunarora 
I not use Docker. And I install VisualDL with this command：
```
pip install --upgrade visualdl
```

**Comment by yeyupiaoling** [comment]
@varunarora 
Maybe the problem of my paddlepaddle. Can you get me your paddlepaddle's whl

**Comment by yeyupiaoling** [comment]
@varunarora 
When I build and install locally. I run it successfully. Thank you.
