### ISSUE TITLE
RuntimeError: [/build/VisualDL/visualdl/storage/storage.cc:43] 

### ISSUE THREAD

**Issue by zhangguangzhi** [PaddlePaddle/VisualDL#315]
I am using VisualDL and I get the following error. How should I troubleshoot

 File "/usr/local/lib/python2.7/dist-packages/visualdl/python/storage.py", line 141, in scalar
    return type2scalar[type](tag)
RuntimeError: [/build/VisualDL/visualdl/storage/storage.cc:43]

**Comment by jetfuel** [comment]
@zhangguangzhi Looking at the code history. I think storage.cc:43 is as following
```
Tablet Storage::AddTablet(const std::string& x) {
  CHECK(tablets_->count(x) == 0) << "tablet [" << x << "] has existed";
```
Maybe you were trying to create a new Scalar Writer with the same `tag` name within the same `mode`
Try change the  `mode` name like this
```
logw = LogWriter(logdir, 200000)

# create scalars in mode train and test.
with logw.mode('train') as logger:
    scalar0 = logger.scalar("scratch/scalar")

with logw.mode('test') as logger:
    scalar1 = logger.scalar("scratch/scalar")
```
Hope this helps

**Comment by zhangguangzhi** [comment]
@jetfuel Thank you, this is the reason.
