### ISSUE TITLE
Mac run error info

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/VisualDL#316]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/visualdl/__init__.py", line 5, in <module>
    from .python.storage import *
  File "/Library/Python/2.7/site-packages/visualdl/python/storage.py", line 3, in <module>
    from visualdl import core
ImportError: dlopen(/Library/Python/2.7/site-packages/visualdl/core.so, 2): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python
  Referenced from: /Library/Python/2.7/site-packages/visualdl/core.so
  Reason: image not found

I think it may because cannot find the default python path.

**Comment by jetfuel** [comment]
@realsnake Thank you for the feedback. Is this within the Virtualenv ? Using Virtualenv should help to isolate the environment.

**Comment by realsnake** [comment]
@jetfuel No, it's normal environment. Do you have any suggestion to solve my problem?

**Comment by jetfuel** [comment]
@realsnake Try to use Virtualenv to create an environment first. and then install the visualdl again. Hopefully, that will help.

**Comment by bveliqi** [comment]
Running into the same issue.
I've tried it within two newly created conda python 3.6 and python 2.7 environments.
Any idea?

**Comment by jetfuel** [comment]
@bveliqi This is a daunting issue to deal with. In OP's case, OP has the following error 
```
ImportError: dlopen(/Library/Python/2.7/site-packages/visualdl/core.so, 2): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python
Referenced from: /Library/Python/2.7/site-packages/visualdl/core.so
Reason: image not found
``` 
We can see that the first line and the second line points to two different python. Usually creating a virtualenv will solve this issue. 

Another way to approach this issue if to build your own wheel and install that. 
```
git clone https://github.com/PaddlePaddle/VisualDL.git
cd VisualDL

python setup.py bdist_wheel
pip install --upgrade dist/visualdl-*.whl
```

Please note the following printout created by camke. All the Python related variables should use the same 'Python'. I also suffer the error when my system found different version of pythons. 
```
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PY_pip: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip  
-- Found PY_numpy: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy  
-- Found PY_wheel: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wheel  
```

Hope this helps

**Comment by bveliqi** [comment]
Thanks @jetfuel for the reply.

Tried installing it myself, failed with the following error:

```
+ cmake -DWITH_PYTHON3=ON ..
-- Protobuf protoc executable: /Users/bveliqi/repos/VisualDL/build/third_party/install/protobuf/bin/protoc
-- Protobuf library: /Users/bveliqi/repos/VisualDL/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protobuf version: 3.5
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bveliqi/repos/VisualDL/build
+ make -j2
[ 23%] Built target zlib
[ 23%] Built target extern_eigen3
[ 46%] Built target extern_gtest
[ 47%] Built target extern_pybind
visualdl/storage/CMakeFiles/binary_record.dir/build.make:61: *** target pattern contains no `%'.  Stop.
make[1]: *** [visualdl/storage/CMakeFiles/binary_record.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 115, in <module>
    cmdclass=cmdclass)
  File "/Users/bveliqi/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/bveliqi/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 81, in run
    subprocess.check_call(cmd, env=env)
  File "/Users/bveliqi/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'build.sh']' returned non-zero exit status 2.
```
Any idea?

I don't use virtualenv. I only work with conda environments. As I said creating totally new conda environments for both python 2 as well as 3 did not help.

**Comment by qbx2** [comment]
I think the issue comes from: https://github.com/PaddlePaddle/VisualDL/blob/9ad1e5a2eac9b0c6f9f2c1820bd8ec00e9cf1779/docs/release/build.sh#L52-L60
core.so in VisualDL tries to load /Library/Frameworks/Python.framework/Versions/3.6/Python which does not exist In my environment.
The path of python should be set properly somehow.

**Comment by nickyfantasy** [comment]
Fixed by https://github.com/PaddlePaddle/VisualDL/pull/466.

**Comment by yxfGrace** [comment]
> Thanks @jetfuel for the reply.
> 
> Tried installing it myself, failed with the following error:
> 
> ```
> + cmake -DWITH_PYTHON3=ON ..
> -- Protobuf protoc executable: /Users/bveliqi/repos/VisualDL/build/third_party/install/protobuf/bin/protoc
> -- Protobuf library: /Users/bveliqi/repos/VisualDL/build/third_party/install/protobuf/lib/libprotobuf.a
> -- Protobuf version: 3.5
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/bveliqi/repos/VisualDL/build
> + make -j2
> [ 23%] Built target zlib
> [ 23%] Built target extern_eigen3
> [ 46%] Built target extern_gtest
> [ 47%] Built target extern_pybind
> visualdl/storage/CMakeFiles/binary_record.dir/build.make:61: *** target pattern contains no `%'.  Stop.
> make[1]: *** [visualdl/storage/CMakeFiles/binary_record.dir/all] Error 2
> make: *** [all] Error 2
> Traceback (most recent call last):
>   File "setup.py", line 115, in <module>
>     cmdclass=cmdclass)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/Users/bveliqi/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
>     self.run_command('build')
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 81, in run
>     subprocess.check_call(cmd, env=env)
>   File "/Users/bveliqi/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['bash', 'build.sh']' returned non-zero exit status 2.
> ```
> Any idea?
> 
> I don't use virtualenv. I only work with conda environments. As I said creating totally new conda environments for both python 2 as well as 3 did not help.

Hi, has this problem been solved? I have the same problem. Thank you.
