### ISSUE TITLE
I run demo vdl_create_scratch_log happen error

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#319]
I install VisualDL 
```
pip install --upgrade visualdl
```
And then run 
```
vdl_create_scratch_log
```
error log:
```
vdl_create_scratch_log: command not found
```

**Comment by jetfuel** [comment]
@yeyupiaoling Sorry for the inconvenience. Try simply typing `vdl_scratch.py` or `vdl_scratch`. 
We changed the script name and update the documentation, but the pip version still uses the old code.

**Comment by yeyupiaoling** [comment]
@jetfuel 
OK! Thank you~
