### ISSUE TITLE
How to cancel smoothed in scalar

### ISSUE THREAD

**Issue by zhangguangzhi** [PaddlePaddle/VisualDL#321]
![image](https://user-images.githubusercontent.com/29686413/37387203-7e020802-2796-11e8-8de3-8742dbf523a9.png)
As shown, the smoothed curve affects my reading. How should I cancel it
@jetfuel 
@varunarora

**Comment by zhangguangzhi** [comment]
I found a way to not display "smoothed" on the web page, but I still don't understand how this "smoothed" is generated.

**Comment by nickyfantasy** [comment]
@zhangguangzhi There is a slider in the config panel where you can adjust the smoothing value. But right now there is a bug that if you make the smoothing value to be 0, it just uses the default one. Will fix the bug, but meanwhile you can adjust it to like 0.01
