### ISSUE TITLE
mac 上安装 VisualDL 总是装不上

### ISSUE THREAD

**Issue by deqingli** [PaddlePaddle/VisualDL#346]
OS：macOS 10.13
python 环境：
![image](https://user-images.githubusercontent.com/13548221/38072227-ff761d2a-3357-11e8-8b7d-a74a38539af8.png)
安装方式：
![image](https://user-images.githubusercontent.com/13548221/38072257-17d30cac-3358-11e8-9f2b-f731ea79c23b.png)
报的错误：
![image](https://user-images.githubusercontent.com/13548221/38072285-28823280-3358-11e8-8f45-aee8670372f6.png)
后来我又选择如下的这种方式安装：
![image](https://user-images.githubusercontent.com/13548221/38072463-ee664de2-3358-11e8-8d9f-c1451d6a6be3.png)
在最后一步还是会报错误，如下：
![image](https://user-images.githubusercontent.com/13548221/38072494-1f15c030-3359-11e8-963e-2152cd5838ca.png)

**Comment by oraoto** [comment]
Permission denied和Operation not permitted，是不是当前用户权限不够？

**Comment by daming-lu** [comment]
Jeff will work on proper installation for Mac users via brew.

**Comment by deqingli** [comment]
跟权限没有关系，试了 sudo 也没用

**Comment by jetfuel** [comment]
Should be solved by the steps in https://github.com/PaddlePaddle/VisualDL/issues/347

**Comment by daming-lu** [comment]
@deqingli 我们今天尝试了新的版本的安装。在虚拟环境下安装没有问题。具体步骤如下：
(vdl_venv is the virtual environment name of your choice)

`virtualenv vdl_venv`
`source vdl_venv/bin/activate`
`pip install visualdl`
`visualdl --logdir=./`

**Comment by deqingli** [comment]
@daming-lu @jetfuel  I have tested install with Anaconda and it works well, thanks for your work.
