### ISSUE TITLE
smooth 参数设为0，依然会有 smooth 效果

### ISSUE THREAD

**Issue by deqingli** [PaddlePaddle/VisualDL#374]
如下图：
<img width="850" alt="smooth" src="https://user-images.githubusercontent.com/13548221/38467184-4660d632-3b67-11e8-9d72-8bed2915d67c.png">

问题描述：当 smooth 参数拖成 0 的时候，依然带有 smooth 效果。

期望结果：
1.  smooth 参数拖成 0 的时候，不再有 smooth 效果。
2. 默认显示原始数据，即 smooth 为0。

**Comment by jetfuel** [comment]
https://github.com/PaddlePaddle/VisualDL/pull/375 fixes this issue.
