### ISSUE TITLE
Choose download folder; Reuse log data

### ISSUE THREAD

**Issue by zchrissirhcz** [PaddlePaddle/VisualDL#396]
First I like VisualDL as a visualization tool during deep learning training and really appreciate your work. As a caffe user, it helps me.

By referring different training schemes, I mean on same dataset and network but different hyperparameters.
In some cases, I would like to compare between different training schemes, so hopes to choose download folder for each scheme's plotted images, thus they won't be with duplicated names, like loss.png and loss(1).png. Will this feature be supported?

My second question: for precise comparison between different training schemes, I would like to reuse the save scalar data for (my own) plotting. Is there any example for reading saved scalar data for own plot, especially for python interface?

Thanks.

**Comment by jetfuel** [comment]
Hi @zchrissirhcz Thank you for using the tool. 
I am not too familiar with HTML5.  But based on the tiny research I done,  at the moment, HTML5 doesn't really allow Javascript to trigger "save as dialog" for security reason. Usually the "save as dialog" is a browser feature. 

The good news is, Google Chrome browser supports this feature. In the `Setting` -> `Show advanced` -> `download`. You can toggle this feature.
<img width="824" alt="screen shot 2018-04-16 at 11 30 44 am" src="https://user-images.githubusercontent.com/1093725/38829578-5ff1a9a2-416e-11e8-961a-d776f784d0a0.png">

I don't quite understand the second question. Do you mean you would like to re-create the graph elsewhere using the saved JSON data? If yes, we currently don't offer any example on how to do that. Sorry about that.

**Comment by zchrissirhcz** [comment]
@jetfuel Thanks for your concrete reply. My question means to re-load the scalar data that saved in my specified log folder, thus I can load different log folders' data for a summary plot and comparison.
