### ISSUE TITLE
Cannot download large graph

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/VisualDL#397]
MNIST is OK

`src.src.length
59942`

SQUEEZE_NET is NOT GOOD

`src.src.length
312462`

PS: MNIST.png

![graph 10](https://user-images.githubusercontent.com/5635322/38800003-e3574e54-411a-11e8-8e9f-634478cc9fec.png)

**Comment by jetfuel** [comment]
Can't reproduce it at the moment. might be browser memory issue.
