### ISSUE TITLE
Adjust the gif animations to make them slower

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/VisualDL#403]
The Gif files on the README.md move too quick. I usually can't stare at them over couple seconds. 

We need to tune them down by reduce the frame-rate or make the animations slower.

**Comment by daming-lu** [comment]
https://github.com/daming-lu/large_files/commit/83af221846583efc02743b9acc387681994feffb
https://github.com/daming-lu/large_files/commit/d914a95a86ab53cd33997f6255c0e95db9202993
