### ISSUE TITLE
Improve Histogram chart

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/VisualDL#406]
Improve ECharts Histogram chart. 

This is based on the conversation the other day.

**Comment by jetfuel** [comment]
@deqingli Hi. You mentioned before that you would like to improve the ECHART Histogram. Please use this issue to track the progress. Thank you

**Comment by PeterPanZH** [comment]
New histogram chart is coming out. Open a new issue if there are other problems or improvement.
