### ISSUE TITLE
how to install VisualDL in windows?

### ISSUE THREAD

**Issue by marsggbo** [PaddlePaddle/VisualDL#414]
I've tried `pip install --upgrade visualdl`, but got such error

> Collecting visualdl
  Could not find a version that satisfies the requirement visualdl (from versions: )
No matching distribution found for visualdl

Then I tried to build from source, but when I run this code: `python setup.py bdist_wheel`, I got such info:

> npm should be installed.

and then 

` pip install --upgrade dist/visualdl-*.whl` also faied, the error info is

> Requirement 'dist/visualdl-*.whl' looks like a filename, but the file does not exist
visualdl-*.whl is not a valid wheel filename.

**Comment by daming-lu** [comment]
@marsggbo : Thanks for your interest in VisualDL. Sorry that we currently do not support Windows. We now only support Mac and Linux (Ubuntu). In Windows, you can create a virtual environment of Ubuntu inside Windows using tools such as VirtualBox. That way you can install our Linux version. Let me know if I can help in any aspect. Thank you again 😄

**Comment by Fankbai** [comment]
为什么不在readme中指出来不支持Windows。这和平台有关吗

**Comment by nickyfantasy** [comment]
We just released VisualDL for Windows for `pip install --upgrade visualdl` ! Make sure you have Python 3.6 or above
