### ISSUE TITLE
 'from visualdl import core' ImportError

### ISSUE THREAD

**Issue by Xander23333** [PaddlePaddle/VisualDL#418]
<img width="657" alt="2018-04-21 13 16 08" src="https://user-images.githubusercontent.com/23695541/39080670-2da72eee-4566-11e8-9b61-78f1115ea52a.png">

python3导入visualdl模块。
报错说，visualdl中的storage模块导入cure库的时候出错。原因是 image not find。

请问是什么原因?

**Comment by daming-lu** [comment]
@XanderXu1998 感谢对VisualDL的兴趣。请问您是否在 conda 的虚拟环境下安装的 VisualDL ？ 看到您的 /usr/local/lib，感觉您应该是在Mac上用 brew 安装的 python。不知道您是否能试试 Anaconda？流程在这里：

https://github.com/PaddlePaddle/VisualDL#install-with-anaconda

**Comment by WangXin93** [comment]
@XanderXu1998 我也遇到这个问题，然后装完xcode就好了。

**Comment by xinpingwang** [comment]
@XanderXu1998 Is there any plan to upload `visualdl` to conda, as the env is created by conda, and using pip to manage packages under conda seems not very good. I see there are `paddlepaddle` and `paddlepaddle-gpu` available on the [paddle channel](https://anaconda.org/paddle)
