### ISSUE TITLE
do not work with pytorch 0.4

### ISSUE THREAD

**Issue by zkdfbb** [PaddlePaddle/VisualDL#423]
when using pytorch 0.4 (python3.6.4)

>>>import torch
>>>from visualdl import LogWriter
[1]    3893 segmentation fault (core dumped)  python

**Comment by daming-lu** [comment]
@zkdfbb 感谢您对VisualDL的兴趣。请问您是在Anaconda的Python虚拟环境下安装的VisualDL和PyTorch吗？segmentation fault 大多数是环境不匹配造成的。能否贴一下您的 stack trace？谢谢啦

PS: 我更喜欢韩菱纱 😀

**Comment by zkdfbb** [comment]
是的，Anaconda3，用pytorch 0.3的时候还正常，0.4 import的时候就直接退出了。

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/kai.zhang1/.anaconda3/lib/python3.6/site-packages/numpy/../../../libiomp5.so
Detaching after fork from child process 22368.
Missing separate debuginfo for /home/kai.zhang1/.anaconda3/lib/python3.6/site-packages/torch/lib/libgomp-c0d7b783.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/12/64ed044ad4ae70bae2eb380f5d83b0bf1e0815.debug

Program received signal SIGSEGV, Segmentation fault.
0x00007fffb0fd5690 in pybind11::detail::make_new_python_type(pybind11::detail::type_record const&) () from /home/kai.zhang1/.anaconda3/lib/python3.6/site-packages/visualdl/core.so
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64

**Comment by hackiey** [comment]
同样遇到了这个问题，torch和visualdl单独import都可以成功，一旦先import其中一个，再import另一个就会报segmentation fault的错误，0.3.1的时候是没有问题的，升级完0.4就不能行了

**Comment by hyfvincent** [comment]
Is there any update for this issue?

**Comment by ValedL** [comment]
Same issue under Virtualenv and Python 2.7..

**Comment by oraoto** [comment]
Python 3.6.5, PyTorch 0.4 cpu + VisualDL master, 跑了[pytorch_word2vec.py](https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/pytorch/pytorch_word2vec.py)， 没出现 segmentation fault.

看上面的错误信息，好像和openmp有关？

**Comment by oraoto** [comment]
测试了conda安装pytorch然后安装visualdl，会出现segmentation fault.

```
conda create -n visualdl
source activate visualdl
conda install pytorch-cpu -c pytorch
pip install --upgrade visualdl
```

**Comment by oraoto** [comment]
在测试了在conda环境下编译visualdl，没出现segfault。推测原因是conda的numpy默认使用了mkl，而visualdl的pypi包编译时用的是普通的numpy，所以导致了segfault.

**Comment by oraoto** [comment]
搞错了，不关numpy、mkl的事，用同一台PC上的virtualenv里编译的visualdl，和conda环境的pytorch一起用是没问题的。

**Comment by oraoto** [comment]
因为segfault出现在pybind11::detail::make_new_python_type，可能和https://github.com/pybind/pybind11/issues/1262 有关

**Comment by findmyway** [comment]
Any update?

**Comment by zzuberi** [comment]
Not sure if this is useful but the latest version of visualdl that works with pytorch is 0.0.1a2.

**Comment by wdcxc** [comment]
I have encountered the same problem. Is there any solution like downgrade the version of packages except pytorch(0.4)?

**Comment by PeterPanZH** [comment]
close outdated issue.
