### ISSUE TITLE
Webpack: why it does not compile the whole thing?

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/VisualDL#435]
When running webpack, the `index.<hashcode>.js` is only partially built in the first run (`388 kB`)

![screen shot 2018-04-27 at 11 47 07 am](https://user-images.githubusercontent.com/5635322/39379775-34d285d8-4a11-11e8-8bcc-4d422e7d4507.png)

and later fully compiled (`24.9 MB`) 

<img width="797" alt="screen shot 2018-04-27 at 11 47 26 am" src="https://user-images.githubusercontent.com/5635322/39379786-3be255ba-4a11-11e8-9f39-c4a674b05171.png">

Is this some optimization that webpack implements? Is there any way to force a complete build at the first run?

**Comment by PeterPanZH** [comment]
close outdated issue.
