### ISSUE TITLE
Build fail with error 'google/protobuf/stubs/common.h' file not found  on MacOS

### ISSUE THREAD

**Issue by higis927** [PaddlePaddle/VisualDL#439]
OS version:
System Version: macOS 10.13.2 (17C88)
Kernel Version: Darwin 17.3.0
Python version: 2.7.10
cmake version: 3.11.0
protoc version: 3.5.1
gcc version: Apple LLVM version 9.0.0 (clang-900.0.39.2)
It failed with the error during running 'python setup.py build as following. It seemes it does not find google/protobuf/text_format.h. However, there is indeed google/protobuf/text_format.h in gcc system include library.
==============
**Errors:**
Building CXX object visualdl/storage/CMakeFiles/binary_record.dir/binary_record.cc.o
In file included from /Users/amy.sy/code/VisualDL/visualdl/storage/binary_record.cc:15:
In file included from /Users/amy.sy/code/VisualDL/visualdl/storage/binary_record.h:22:
/Users/amy.sy/code/VisualDL/visualdl/utils/filesystem.h:18:10: fatal error: 'google/protobuf/text_format.h' file not found
#include <google/protobuf/text_format.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [visualdl/storage/CMakeFiles/binary_record.dir/binary_record.cc.o] Error 1
make[1]: *** [visualdl/storage/CMakeFiles/binary_record.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^Cinterrupted
make[2]: *** [third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download] Interrupt: 2
make[1]: *** [CMakeFiles/extern_eigen3.dir/all] Interrupt: 2
make: *** [all] Interrupt: 2

my gcc system library:
ls -alt /usr/local/include/google/protobuf/text_format.h
-rw-r--r--@ 1 root  admin  24051  4 28 17:48 /usr/local/include/google/protobuf/text_format.h

**Comment by daming-lu** [comment]
Hi, @higis927 ! Can u try installing VisualDL using Anaconda ? It provides a unified Python environment.

**Comment by higis927** [comment]
@daming-lu  I tried it with Anaconda. The error is as following. 
+ build_backend
+ cd /Users/amy.sy/code/VisualDL/build
+ [[ -n '' ]]
+ cmake ..
-- Protobuf protoc executable: /Users/amy.sy/code/VisualDL/third_party/install/protobuf/bin/protoc
-- Protobuf library: /Users/amy.sy/code/VisualDL/third_party/install/protobuf/lib/libprotobuf.a
-- Protobuf version: 3.5
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/amy.sy/code/VisualDL
+ make -j2
[  4%] Performing download step (git clone) for 'extern_eigen3'
[ 12%] Built target zlib
Cloning into 'extern_eigen3'...
[ 25%] Built target extern_pybind
[ 36%] Built target extern_gtest
[ 38%] Building CXX object visualdl/storage/CMakeFiles/binary_record.dir/binary_record.cc.o
In file included from /Users/amy.sy/code/VisualDL/visualdl/storage/binary_record.cc:15:
In file included from /Users/amy.sy/code/VisualDL/visualdl/storage/binary_record.h:22:
/Users/amy.sy/code/VisualDL/visualdl/utils/filesystem.h:18:10: fatal error: 'google/protobuf/text_format.h' file not found
#include <google/protobuf/text_format.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [visualdl/storage/CMakeFiles/binary_record.dir/binary_record.cc.o] Error 1
make[1]: *** [visualdl/storage/CMakeFiles/binary_record.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by jetfuel** [comment]
@higis927 Hi, thanks for pasting the trace. I think the Cmake is not using the protobuf under your 
`/usr/local` and that's why it couldn't find the `text_format.h`. Usually the VisualDL should download the protobuf as an external library and compile it from scratch. I am not sure why it is not doing that in this case.

**Comment by higis927** [comment]
@jetfuel Thanks for your response. Do you mean that I do not need to install protobuf before I install VisualDL? I uninstalled protobuf, and run python setup.py bdist_wheel. The following error is fired:
==========
+ check_duplicated 'vendor.*.js'
+ filename_format='vendor.*.js'
++ ls dist/vendor.5a194f30e1079311fad3.js
++ wc -l
++ awk '{$1=$1;print}'
+ file_num=1
+ '[' 1 '!=' 1 ']'
+ clean_env
+ rm -rf /Users/amy.sy/code/VisualDL/visualdl/server/dist
+ rm -rf '/Users/amy.sy/code/VisualDL/build/bdist*'
+ rm -rf '/Users/amy.sy/code/VisualDL/build/lib*'
+ rm -rf '/Users/amy.sy/code/VisualDL/build/temp*'
+ rm -rf '/Users/amy.sy/code/VisualDL/build/scripts*'
+ build_backend
+ cd /Users/amy.sy/code/VisualDL/build
+ [[ -n '' ]]
+ cmake ..
CMake Error at /Users/amy.sy/anaconda2/envs/vdl/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.11/Modules/FindProtobuf.cmake:425 (file):
  file STRINGS file "/usr/local/include/google/protobuf/stubs/common.h"
  cannot be read.
Call Stack (most recent call first):
  cmake/external/protobuf.cmake:17 (FIND_PACKAGE)
  CMakeLists.txt:47 (include)


CMake Error at /Users/amy.sy/anaconda2/envs/vdl/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.11/Modules/FindProtobuf.cmake:431 (math):
  math cannot parse the expression: " / 1000000": syntax error, unexpected
  exp_DIVIDE, expecting exp_PLUS or exp_MINUS or exp_OPENPARENT or exp_NUMBER
  (2)
Call Stack (most recent call first):
  cmake/external/protobuf.cmake:17 (FIND_PACKAGE)
  CMakeLists.txt:47 (include)

**Comment by ZeyuChen** [comment]
VisualDL 2.0-beta use pure Python 3 to build, easy to install with high compatibility, so  there is no C++ compile issues from now on.
