### ISSUE TITLE
找不到 visualDL命令

### ISSUE THREAD

**Issue by yanyan-li** [PaddlePaddle/VisualDL#440]
大家好，请教一个问题。
ubuntu 16.04. 源码编译， 但是 pip install 成功之后，仍然 找不到 visualDL。
visualDL: command not found

另外，readme上相关的link ”you can still start Visual DL by starting the dev server _here_“失效。

**Comment by jetfuel** [comment]
Hi @yanyan-li Thank you for using VisualDL. and sorry for the issue your ran into. 

Please try `visualdl` with lower case. If that didn't help with the issue, please try to install the visualdl within a virtualenv or anaconda environment. That will ensure the pip to install the executable on your PATH. Thanks

**Comment by ujsyehao** [comment]
you can 
`cd /usr/local/bin`
`./visualDL`
