### ISSUE TITLE
How to configure in PyCharm

### ISSUE THREAD

**Issue by tengerye** [PaddlePaddle/VisualDL#441]
Hi,
I have successfully installed VisualDL and could import it from shell, however, when I import it from PyCharm:
`from visualdl import LogWriter`

I still get this:
`ModuleNotFoundError: No module named 'visualdl'`.

Any idea how to configure it from PyCharm please?

**Comment by daming-lu** [comment]
Hey, @tengerye ! Can u try `python -c 'import visualdl'` in your terminal? Integrating into PyCharm could be problematic.

**Comment by tengerye** [comment]
Thank you for your reply@daming-lu.

It works fine on the Terminal but remains a problem for PyCharm.

**Comment by daming-lu** [comment]
@tengerye 👍  I think the problem is the integration between your Python environment and PyCharm. I use PyCharm but have not integrated into the environment yet. I use PyCharm simply as an editor 😄

**Comment by jetfuel** [comment]
@tengerye Typically I would setup my PyCharm by visiting
Preferences-> Project -> Project Interpreter 
And then to confirm if the selected interpreter is installed with the package you need. If this doesn't help, I would recommend moving the question to PyCharm community. They can provide more in-depth help.
