### ISSUE TITLE
Build fail with error 'visualdl/storage/CMakeFiles/binary_record.dir/build.make:61: *** target pattern contains no `%'.  Stop.'  on Linux

### ISSUE THREAD

**Issue by higis927** [PaddlePaddle/VisualDL#447]
OS version:
System Version: Linux e18f05531.et15sqa 2.6.32-220.23.2.ali1089.el5.x86_64 #1 SMP Fri Jun 14 10:52:15 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
Python version: 2.7.14
cmake version: 3.11.0
protoc version: I do not installed protoc by myself
gcc version: gcc (GCC) 4.9.2 20150212
The errors are as following:
-- Installing: /tmp/rnn/VisualDL/build/third_party/install/gtest/include/gtest/gtest-param-test.h.pump
-- Installing: /tmp/rnn/VisualDL/build/third_party/install/gtest/include/gtest/gtest-death-test.h
[ 38%] Completed 'extern_gtest'
[ 38%] Built target extern_gtest
visualdl/storage/CMakeFiles/binary_record.dir/build.make:61: *** target pattern contains no `%'.  Stop.
make[1]: *** [visualdl/storage/CMakeFiles/binary_record.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^Cinterrupted
make[2]: *** [third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download] Interrupt
make[1]: *** [CMakeFiles/extern_eigen3.dir/all] Interrupt
make: *** [all] Interrupt

**Comment by daming-lu** [comment]
@higis927 Thanks for your interest in VisualDL. 'protoc' is installed automatically by VisualDL. May I know if you use Anaconda or not? Anaconda is suggested to prevent environment conflicts.

**Comment by higis927** [comment]
@daming-lu I am installing it on Linux docker.   
On Mac os, I install it by Anancoda, but the issue is documented as following:
https://github.com/PaddlePaddle/VisualDL/issues/439

**Comment by jetfuel** [comment]
@higis927 Sorry for the trouble. It took us a while to debug this. The Cmake version is too new for the protobuf build script. Try downgrading the cmake to version 3.9. and that should resolve the issue for you. 

The team will also try to update the protobuf build script asap to be compatible with latest cmake.

**Comment by ZeyuChen** [comment]
VisualDL 2.0 use pure python 3 to build, so there is no C++ compile issues from now on, easy to install with high compatibility, so issues closed.
