### ISSUE TITLE
Review the whole network states for a single predicted value after a trained model

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/VisualDL#452]

**Comment by ghost** [comment]
We are always not very clear that if the every part/layer of a model is worked well as our original designing purpose. To give a weight related picture is very important after training or in the step of prediction. It is like to classify a single sample in a trained/known model. a weighted map/picture instead of a black box will be more help to understand the model and the input sample. The map/picture is a history to reflect of a life for the sample to be input, selected, classified in the model. So the user can update their model with the help of a weighted map/picture, to enhance the weak part or delete the useless part in the model for optimization, easily and rapidly.

**Comment by daming-lu** [comment]
@chaostree Thank you Chaostree for your interest in VisualDL. Your suggestion is really valuable to us. You know besides Graph we also provide other components like Histogram, which is really useful at pinpointing gradients exploding/vanishing. Histogram can show weight changes from every iteration/epoch. We will of course consider adding a global network viewer after each prediction.

**Comment by PeterPanZH** [comment]
close inactive issue.
