### ISSUE TITLE
Why is there no Graph in PaddlePaddle?

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#453]
Graph in all the other dome. like：https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/pytorch/TUTORIAL_EN.md

But no Graph in PaddlePaddle dome. like:https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/paddle/TUTORIAL_EN.md

Can paddlepaddles generate a Graph? Thanks

**Comment by daming-lu** [comment]
@yeyupiaoling We are working on generating genuine PaddlePaddle graph so that it can be used directly in VisualDL. Right now the solution is to use [paddle->onnx](https://github.com/PaddlePaddle/paddle-onnx) converter.

BTW: I am a big fan of your CSDN blog 🤗

**Comment by yeyupiaoling** [comment]
@daming-lu 
Woo，vey lucky. Looking forward to the emergence of paddlepaddle graph. And paddle->onnx is a little bit complicated. Thank you for your reply.
