### ISSUE TITLE
how to use visualDL with caffe

### ISSUE THREAD

**Issue by ujsyehao** [PaddlePaddle/VisualDL#463]
I have two problems:
1. I can not run C++ SDK demo, I have git clone visualDL and make, then I try to compile c++ sdk example, below is my compile command:
 `g++ a.cpp --std=c++11 -I /home/yehao/VisualDL -L /home/yehao/VisualDL/visualdl/core.so`
But I get errors:
![152](https://user-images.githubusercontent.com/17454232/41755508-5ffecf08-760a-11e8-8f7d-1dd660a6cf27.png)
Can anyone give me some advice?
2. How to use visualDL with caffe? Should I modify solver.cpp?

**Comment by Superjomn** [comment]
https://github.com/PaddlePaddle/VisualDL/blob/develop/CMakeLists.txt#L81

core.so 里没有打包进所有的 c++的 lib，需要额外链接相关的静态链接库

@daming-lu C++ 的库需要单独发布出来

**Comment by ujsyehao** [comment]
用g++编译：
`g++ -o out test.cpp --std=c++11 -I/home/yehao/VisualDL/ -I/home/yehao/VisualDL/build/ -L/home/yehao/VisualDL/tmp/ -lsdk -lstorage -lbinary_record -lentry -ltablet -lim -lgtest -lglog -lprotobuf -lgflags -lpthread`
**把所有生成的静态库复制到tmp文件夹下**，用这条命令可以编译成功。

**Comment by ujsyehao** [comment]
在编译visualDL的时候，**遇到protoc版本的问题**，我本机上的protoc版本是2.6和3.6，其中protoc 3.6是默认版本，g++ test.cpp报错：
`_this file was generated by an older version of protoc, please regenerate this file with a newer version of protoc._ `
又去查看cmake，发现它默认去下载protoc 3.5版本，在**cmake/external/protobuf.cmake**中，我修改了protobuf版本
![154](https://user-images.githubusercontent.com/17454232/42078428-04a9888c-7baf-11e8-853a-fd7f1247554c.png)
建议在protobuf.cmake中，**先去检查本机的protobuf版本**，如果本机上有protobuf3.0以上版本，就直接去调本机的protobuf，不用再去下载，不然本机已有protobuf版本，再下载protobuf3.5版本，**编译完的pb.c和本机的protobuf冲突**。

**Comment by daming-lu** [comment]
@ujsyehao 谢谢您的提议。我们会马上把protoc的问题改好~

**Comment by ujsyehao** [comment]
@daming-lu thank you

**Comment by songkq** [comment]
@ujsyehao 请问你那儿还有支持c++ sdk的visualDL源码嘛，方便分享下嘛
