### ISSUE TITLE
`tags` of `LogReader` return empty if `mode` is not set

### ISSUE THREAD

**Issue by findmyway** [PaddlePaddle/VisualDL#464]
Recently I wrote a [Julia wrapper](https://github.com/findmyway/VisualDL.jl) above VisualDL.

When writing tests, I find that the `tags` method of `LogReader` always returns empty if `mode` is not set.

Just open this issue in case someone else also encounter it.

**Comment by daming-lu** [comment]
@findmyway : Thanks for your interest in VisualDL. `mode` is required for `tags`. Let me know if you find this requirement improper.
