### ISSUE TITLE
执行quickstart中python代码报错，TypeError: urlopen() got an unexpected keyword argument 'context'

### ISSUE THREAD

**Issue by alfredyule78** [PaddlePaddle/VisualDL#472]
![default](https://user-images.githubusercontent.com/12423715/42871806-cedcc472-8aad-11e8-8be0-f0587ddcb714.png)

**Comment by nickyfantasy** [comment]
This problem is already fixed in next release version 1.1. Please upgrade end of this week!

**Comment by nickyfantasy** [comment]
Fixed by https://github.com/PaddlePaddle/VisualDL/pull/473

**Comment by alfredyule78** [comment]
![default](https://user-images.githubusercontent.com/12423715/43179408-5c53fa58-9005-11e8-9370-0e0173f62167.png)
还是没有解决

**Comment by alfredyule78** [comment]
weekend，ok
