### ISSUE TITLE
ResNet50 v2 model cannot be shown

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/VisualDL#485]
https://github.com/tensorflow/models/tree/master/official/resnet

ResNet-50 v2 (Accuracy 76.05%)

<img width="1242" alt="vdl" src="https://user-images.githubusercontent.com/5635322/43804916-a472d186-9a52-11e8-8e5a-bf5c3b605bb3.png">

**Comment by ZeyuChen** [comment]
Now VisualDL 2.0 Graph can visualize tensorflow model correctly.
