### ISSUE TITLE
无法成功运行官网命令

### ISSUE THREAD

**Issue by leochen86** [PaddlePaddle/VisualDL#490]
我使用的是paddle 0.14.0的docker镜像，运行在mac环境，按照官网pip成功安装后，运行vdl_create_scratch_log，visualdl --logdir=scratch_log --port=8080 均以失败告终，请求指导

[root@d1dae57a567d paddleprogram]# vdl_create_scratch_log
[WARNING 2018-08-23 11:44:43,299 vdl_create_scratch_log:221] download ONNX file from https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/mnist_model.onnx?raw=true
Traceback (most recent call last):
  File "/usr/bin/vdl_create_scratch_log", line 228, in <module>
    download_onnx()
  File "/usr/bin/vdl_create_scratch_log", line 222, in download_onnx
    onnx_model = ur.urlopen(onnx_url, context=myssl).read()
TypeError: urlopen() got an unexpected keyword argument 'context'

[root@d1dae57a567d paddleprogram]# visualdl --logdir=scratch_log --port=8080
Traceback (most recent call last):
  File "/usr/bin/visualdl", line 29, in <module>
    import visualdl.server.graph as vdl_graph
  File "/usr/lib64/python2.7/site-packages/visualdl/server/graph.py", line 23, in <module>
    from . import onnx
  File "/usr/lib64/python2.7/site-packages/visualdl/server/onnx/__init__.py", line 8, in <module>
    from .onnx_pb2 import ModelProto
  File "/usr/lib64/python2.7/site-packages/visualdl/server/onnx/onnx_pb2.py", line 213, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

**Comment by leochen86** [comment]
<img width="637" alt="757780215e776baf2fce9661c34d5481" src="https://user-images.githubusercontent.com/34496954/44523716-77230f80-a70d-11e8-8621-d17faa796943.png">

**Comment by oraoto** [comment]
paddlepaddle使用的protobuf版本比visualdl需要的旧，安装新版即可`pip install protobuf==3.5.1`，会提示可能不兼容，实际没有影响。

**Comment by leochen86** [comment]
你好，请问一定要3.5.1的protobuf版本吗，我今天试过更新到3.6.1,结果还是一模一样的错误信息，请问是否一定要3.5.1版本的protobuf？

**Comment by oraoto** [comment]
@leochen86 上面有两个错误，第一个是urlopen的，第二个是profobuf的，安装3.6.1后还有第二个错误吗？

**Comment by leochen86** [comment]
更新成3.6.1以后，错误依旧，没有任何变化，两条命令都是和原来一模一样的错误

**Comment by leochen86** [comment]
[图片]

**Comment by leochen86** [comment]
![Uploading e836036b44fcc0c8631a05090359bc91.PNG…]()

**Comment by nickyfantasy** [comment]
@leochen86 我刚在mac用了paddle 0.14.0的镜像，运行pip install visualdl 再 visualdl --logdir=scratch_log --port=8080  是有相同错误，可是pip install --upgrade protobuf 以后就没有这问题，是不是你有安装其他的protobuf？ 你可以重新docker pull 最新的paddle版本试试还有没有这问题？

**Comment by leochen86** [comment]
你好，的确如你所说，更新protobuf之后visualdl能够成功启动了，但是vdl_create_scratch_log命令还是不行，此外，我看说明里面只有一个scalar的代码示例，哪里可以看到展现神经网络权重参数的代码示例？

Successfully installed protobuf-3.6.1
[root@d1dae57a567d paddleprogram]# visualdl --logdir=scratch_log --port=8080
[INFO 2018-08-24 02:16:34,770 visualdl:310]  port=8080
 * Serving Flask app "visualdl" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO 2018-08-24 02:16:34,778 _internal.py:88]  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)


[root@d1dae57a567d paddleprogram]# vdl_create_scratch_log
[WARNING 2018-08-24 02:16:58,896 vdl_create_scratch_log:221] download ONNX file from https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/mnist_model.onnx?raw=true
Traceback (most recent call last):
  File "/usr/bin/vdl_create_scratch_log", line 228, in <module>
    download_onnx()
  File "/usr/bin/vdl_create_scratch_log", line 222, in download_onnx
    onnx_model = ur.urlopen(onnx_url, context=myssl).read()
TypeError: urlopen() got an unexpected keyword argument 'context'

**Comment by nickyfantasy** [comment]
@leochen86 我查了一下，TypeError: urlopen() got an unexpected keyword argument 'context' 好像是某一python版本的问题。不过urlopen()只是为了下载ONNX file展示而已，我相信scratch_log其实已经创建了，运行visualdl --logdir=scratch_log --port=8080应该看到data了。如果你想用graph来看onnx file, 直接下载 https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/mnist_model.onnx?raw=true，运行visualdl --logdir=scratch_log -m [path to onnx file] --port=8080 就好

**Comment by leochen86** [comment]
好的，感谢，我另外还提了一个issue的，关于histogram的，辛苦帮忙也解惑一下

**Comment by leochen86** [comment]
@nickyfantasy 按照你的说明，的确可以正确浏览visualdl的所有演示效果了，感谢
