### ISSUE TITLE
如何可以正确地通过visualdl histograms展示出神经网络某一层的参数

### ISSUE THREAD

**Issue by leochen86** [PaddlePaddle/VisualDL#492]
你好，我的代码如下所示，但是发现visualdl展现的histograms似乎不是很直观,尤其是对histogram的第二个参数的意义不是很理解，它与参数维度以及展示的图片之间的关系是什么？
with logger.mode("train") as writer:
    param1_histgram=writer.histogram("param1",6)

模型结构如下图，其中要展现的时第一层的参数，也就是12个参数值（输入特征为度=2，输出节点6个）
<img width="645" alt="0b8dd643f201605bc8d5b61f5041ab37" src="https://user-images.githubusercontent.com/34496954/44578351-068bf980-a7c6-11e8-84f8-52c8ad7a6703.png">
实际某次epcho结束后获取到的网络参数值
<img width="519" alt="d12ef427194675b9f50f4f801fb471db" src="https://user-images.githubusercontent.com/34496954/44578307-e825fe00-a7c5-11e8-907b-c1832732678a.png">

visualdl展示结果如图
<img width="425" alt="6673a42c6ee142ea248a7f6c122b985a" src="https://user-images.githubusercontent.com/34496954/44578218-a6955300-a7c5-11e8-8c2d-eb2d314f053e.png">

从图中我无法直观地理解出途中的图如何与参数管理起来，以及与histogram的第二个参数的关系是什么

**Comment by leochen86** [comment]
当我代码里面param1_histgram=writer.histogram("param1",6)这样写，运行程序不会出错，但是如果写100就会报如下错误，因此感觉第二个参数很重要，但是不知道什么含义，与对应网络层的参数个数关系什么，图中又如果将网络参数与图中节点对应起来?

例如，当写成param1_histgram=writer.histogram("param1",100)时，会报如下错误，其中蓝色框时当时给它的输入，而红色框是报错信息，而这样的错误在param1_histgram=writer.histogram("param1",6)或者12或者10都不会出现
<img width="637" alt="92cf45c9665e33ac6f0215204f474875" src="https://user-images.githubusercontent.com/34496954/44578919-63d47a80-a7c7-11e8-90df-eb92b66f4f19.png">

**Comment by Superjomn** [comment]
@jacquesqiao 这个你有经验，可以帮答下么，或者给个例子

**Comment by nickyfantasy** [comment]
@leochen86 谢谢你的提问。writer.histogram("param1",6) 在这个参数里6的意思是创建多少个bucket.

譬如说你的data是 [0.5, 1.1, 1.3, 2.2, 2.9, 2.99] ， 创建3个bucket，每个bucket就大概是[0-1], [1-2], [2-3], 然后把对应的data放到bucket里，所以histogram呈现的是第一个bucket有1个，第二个bucket有2个，第三个有3个

代码里面 histogram.h 有一个检查是一定要 数值大于bucket size， 所以如果你只有12个数值,  如果分成超过12个就会报错

**Comment by nickyfantasy** [comment]
我们的histogram文档确实不清楚，我会多加histogram的例子和api解释

**Comment by leochen86** [comment]
@nickyfantasy 你好，感谢你的回答，不过我还是有点不清楚,bucket与data大小的关系是什么，例如如果我明确知道某一层的data长度是12，那么histogram的第二个参数应该怎么设置呢？
另外“譬如说你的data是 [0.5, 1.1, 1.3, 2.2, 2.9, 2.99] ， 创建3个bucket，每个bucket就大概是[0-1], [1-2], [2-3], 然后把对应的data放到bucket里，所以histogram呈现的是第一个bucket有1个，第二个bucket有2个，第三个有3个”，这段里面histogram的呈现于bucket的关系是什么？为什么创建3个bucket，每一个bucket里面的数据量会不一样？如果可以的话，能否用图形化的方式解答一下

**Comment by nickyfantasy** [comment]
@leochen86 histogram柱状图的意思就是把data分类放在bucket里，因为训练的data应该是接近中间平均值的较多，训练越多期望得到的图是越圆滑，有点像正态分布的意思。

[0.5, 1.1, 1.3, 2.2, 2.9, 2.99]  这个例子 0.5放到第一个bucket[0-1]，1.1, 1.3放到第二个[1-2]，2.2, 2.9, 2.9放到第二个[2-3], 如果你只有12个data,那可以试试分4-6个bucket吧

**Comment by leochen86** [comment]
@nickyfantasy bucket我明白了，那么bucket的位置和数量在图上是如何对应的，能够画个示意图吗

**Comment by PeterPanZH** [comment]
close inactive issue.
