### ISSUE TITLE
python: can't open file 'visualdl\..\visualDL': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by djbyrne** [PaddlePaddle/VisualDL#493]
I have tried to run the example code. I am able to add the loggers to my code and it compiles. However when I run visualdl --logdir ./random_log --port 8080 i receive the following error.

python: can't open file 'visualdl\..\visualDL': [Errno 2] No such file or directory

I am running this on Windows 7 and python 3.6

Any help would be appreciated.

**Comment by oraoto** [comment]
I can reproduce this problem in Windows 10 cmd.exe and python 3.6, but it works fine in PowerShell.

@djbyrne Please run the command in PowerShell. Currently the visualdl.bat script doesn't work in cmd.exe.

**Comment by djbyrne** [comment]
Thanks @oraoto ill try that!

**Comment by oraoto** [comment]
A quickfix is to modify the visualdl.bat:

```
@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
python %~dp0\visualdl %*
```

I don't think it's a good solution. We should utilize setuptools to generate the proper executable and remove visualdl.bat entirely.

**Comment by djbyrne** [comment]
Running the command in PowerShell fixed it for me, thank you! Will also try modifying the .bat file
