### ISSUE TITLE
Can't use with pytorch 0.4.1

### ISSUE THREAD

**Issue by HotaekHan** [PaddlePaddle/VisualDL#504]
import torch
from visualdl import LogWriter
...
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

How can I handle this?
I have also installed from source following guide. then I have no error like that. However I can't see anything from web browser in case.

Thanks

**Comment by ryusaeba** [comment]
trace

**Comment by PeterPanZH** [comment]
close outdated issue.
