### ISSUE TITLE
No ONNX model graph displayed, unless there is other logs

### ISSUE THREAD

**Issue by jiayiliu** [PaddlePaddle/VisualDL#505]
VisualDL renders an empty page if only onnx model is specified without additional logs

The same command:
`visualdl -t 0.0.0.0 -p 8888 -m alexnet.onnx  --logdir log`
creates nothing if log dir is empty.

Wish this is a minor issue to be fixed.

**Comment by yxchng** [comment]
Have you solved the problem? @jiayiliu

**Comment by jiayiliu** [comment]
@yxchng I just dumped some other information to the log and the graph will be generated.  I think there might be an if condition mistakenly ignore the output if log is empty.  I didn't check the details.

**Comment by Wsine** [comment]
@jiayiliu I confirm that there is still such issue. how about we reopen it and wait for response from developer?

Btw, it's not easy to create log with other framework besides Paddle.

**Comment by jiayiliu** [comment]
Hi @Wsine 
I used tf to simply add some summary to the log.  It will fix you problem, hopefully.

**Comment by PeterPanZH** [comment]
VisualDL 2.0 will solve this problem.
