### ISSUE TITLE
windows命令行下启动visualdl报错

### ISSUE THREAD

**Issue by nepeplwu** [PaddlePaddle/VisualDL#514]
windows下安装了visualdl后，启动visualdl，提示"python: can't open file 'visualdl\..\visualDL: [Errno 2] No such file or directory'"

**Comment by nepeplwu** [comment]
已解决

**Comment by xinxinbingzi** [comment]
如何解决的，我也报错(null): can't open file 'D:\Program': [Errno 2] No such file or directory
