### ISSUE TITLE
Windows上使用VisualDL出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#520]
# 环境
1. Windows 10 专业版
2. Python 3.5

# 问题
在执行dome的程序时出错，错误如下：
```
PS C:\Users\666\Desktop> python vdl_scratch.py
Traceback (most recent call last):
  File "vdl_scratch.py", line 24, in <module>
    from visualdl import ROOT, LogWriter
  File "C:\Python35\lib\site-packages\visualdl\__init__.py", line 20, in <module>
    from .python.storage import *  # noqa: F401,F403
  File "C:\Python35\lib\site-packages\visualdl\python\storage.py", line 18, in <module>
    from visualdl import core
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by varunarora** [comment]
Interesting, perhaps someone who has worked on the Windows install needs to look at this

**Comment by oraoto** [comment]
@yeyupiaoling 使用的VisualDL是哪一个版本呢？从pypi安装的吗？

**Comment by yeyupiaoling** [comment]
@oraoto 我刚刚使用pip安装的。

**Comment by oraoto** [comment]
试了Win 10 + Python 3.6，出现同样的问题，可能是pypi上的1.2.1的wheel有问题。

可以先安装1.2.0版本: ` pip install  visualdl==1.2.0`，或者在[这里](https://ci.appveyor.com/project/oraoto/visualdl-windows-build/builds/21081354/job/1mvhtc4vf0cagkly/artifacts)下载最新的版本。

**Comment by yeyupiaoling** [comment]
成功了，谢谢。

**Comment by oraoto** [comment]
问题出现在protobuf使用了zlib动态链接了zlib.dll，但是wheel里没有打包zlib.dll：

![image](https://user-images.githubusercontent.com/24709398/50209543-046e2c00-03af-11e9-9c3a-c0b247f83c8b.png)

**Comment by ShenYuhan** [comment]
> zlib

那么请问在windows中应该如何打包呢？用python setup bdist_wheel打的包依然会报这个错
