### ISSUE TITLE
VisualDL visualizes the plots with some delay

### ISSUE THREAD

**Issue by nbro** [PaddlePaddle/VisualDL#524]
I first started the VisualDL server using the command: `visualDL --logdir ./log --port 8080`. Then I ran my PyTorch program. I went to the URL `http://0.0.0.0:8080/ `, but I only saw empty plots. Then I forced my PyTorch program to stop. I also stopped the visual DL server. I restarted it, and I went to the same URL and now I can see the plots. Why can't I see the plots in real-time?

**Comment by nbro** [comment]
Actually, after a while, it starts to display something. More or less, in my case, when the second epoch starts (but when exactly?).

Meanwhile, I see that VisualDL is outputting some error messages:

```
[ERROR 2019-01-05 19:48:07,791 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/logic/sdk.cc:85] 
<traceback object at 0x110f0c508>
```


```
...
[ERROR 2019-01-05 19:48:09,794 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/logic/sdk.cc:85] 
<traceback object at 0x110f0af08>
[ERROR 2019-01-05 19:48:11,797 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/logic/sdk.cc:85] 
<traceback object at 0x110f0a748>
[ERROR 2019-01-05 19:48:13,799 visualDL:59] server temporary error, will retry latter.
...
```
or

```
...
[libprotobuf FATAL /Users/nepepl/Desktop/VisualDL/build/third_party/install/protobuf/include/google/protobuf/repeated_field.h:1522] CHECK failed: (index) < (current_size_): 
[ERROR 2019-01-05 19:50:26,833 lib.py:380] Unexpected error: <class 'RuntimeError'>
CHECK failed: (index) < (current_size_): 
<traceback object at 0x110f16348>
...
```

Right now, I am just plotting scalars in line plots.

**Comment by nepeplwu** [comment]
hi, nbro, the frequency of data refresh in webpage you can sense depends on two factors, the first is the frequency of data exchange at webpage and server(which is per 15s now), the second is the frequency of data being written to log file(which can control by the sync_cycle parameter). The reason for limiting refresh frequency is that frequent refresh results in high performance costs, especially when logging data is large

**Comment by liupgd** [comment]
I hope the flush time can be setted by user. Some time, 15s is tooooooo long.  I thought my installation was wrong. I checked it over and over. I only found that the flush time is fixed at 15s. What a bad design....

**Comment by PeterPanZH** [comment]
> I hope the flush time can be setted by user. Some time, 15s is tooooooo long. I thought my installation was wrong. I checked it over and over. I only found that the flush time is fixed at 15s. What a bad design....

Manually flush will be added in next few commits. User setting of flush time may impact backend performance. We will evaluate it later. Thanks for your suggestion.

**Comment by PeterPanZH** [comment]
We will discuss it in #613
