### ISSUE TITLE
Some of the issues or comments are not in English and this limits the immediate usefulness of them

### ISSUE THREAD

**Issue by nbro** [PaddlePaddle/VisualDL#525]
I suggest to encourage users to write in English. Maybe you can write a warning in the README (or something like that).

**Comment by yeyupiaoling** [comment]
@nbro But it will be more convenient for us to use Chinese.

**Comment by nbro** [comment]
@yeyupiaoling English is also not my native language. I am aware of the fact that English can be considered, nowadays, the "standard" language in science/tech. It is very unlikely that you will not need to learn English, if you decide to pursue a career in a scientific field.

**Comment by yeyupiaoling** [comment]
@nbro You're right. So I try my best to use English. But often I don't get the results I want.
