### ISSUE TITLE
Are there any examples of how to use LogReader?

### ISSUE THREAD

**Issue by nbro** [PaddlePaddle/VisualDL#526]
Please, have a look at https://nbro.github.io/blogging/2019/01/06/an-example-of-how-to-use-visualdl-with-pytorch/, which is a blog post which (also) explains how to use VisualDL with PyTorch.

**Comment by nepeplwu** [comment]
Hi, nbro, thank you for your feedback. In our design, the user only needs to use the LogWriter record data, and then use webpage to view the data. Users do not need to use LogReader. We would like to know about your scenario of using LogReader

**Comment by nbro** [comment]
@nepeplwu I may need to use LogReader, because the VisualDL plots may not be high-quality when I export them or they may not have the right names on the axes; in that case, I may want to read the data from the logging files and plot it with another tool. To solve this problem, maybe you could provide more sophisticated charts, e.g. whose name can be changed.

**Comment by nepeplwu** [comment]
@nbro , can you provide an example with a screenshot about "they may not have the right names on the axes" ?

**Comment by nbro** [comment]
@nepeplwu In general, you may want to change the name of the axes or the title of the chart, after you have performed your experiments, but, at that time, you either use `LogReader` and another plotting tool, or you re-run your experiments.

**Comment by nepeplwu** [comment]
@nbro , here is an example of using logReader. I hope it works for you
https://github.com/PaddlePaddle/VisualDL/wiki/example-of-LogReader

**Comment by nbro** [comment]
@nepeplwu You did not read my blog post that I linked you to above. I figured out how to use `LogReader`, and, in that blog post, I show an example of how to use it.

**Comment by nepeplwu** [comment]
@nbro , I'm a little confused, so the purpose of this post is to help others understand how to use LogReader, rather than want to know how to use LogReader?

**Comment by nbro** [comment]
@nepeplwu When I opened this issue, I did not know how to use `LogReader`. Meanwhile, I figured it out, and I edited my original post above to include the link to an article that I wrote about the topic.
