### ISSUE TITLE
在使用VisualDL保存的histogram图，如何分析呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#527]
学生使用定义参数
```python
param_name = fluid.default_startup_program().global_block().all_parameters()[0].name
```
然后使用获取参数
```python
param = exe.run(program=fluid.default_main_program(),
                            feed=feeder.feed(data),
                            fetch_list=[param_name])
```
最后使用以下方式保存参数
```python
histogram.add_record(train_step, param.flatten())
```

最后经过训练得到的图像是：
![image](https://user-images.githubusercontent.com/26297768/50744436-2f38fb00-125e-11e9-9186-066fbe91afa7.png)

得到这个图像之后，我应该如何分析呢？能从这个图像中知道什么的？当图像出现那些情况对于的又是那种情况呢？

**Comment by nepeplwu** [comment]
histogram主要用来记录参数分布的变化趋势，有这么几个方面可以分析下：
1. 参数是否有训练到（从上图来看，参数的分布一直在变化，说明参数确实在学习中）
2. 参数是否出现异常值，如极大的正值或者极大的负值
3. 参数主要分布在哪个区间，是否符合预期（举个例子，当你在Loss中加了正则化项之后，你要验证参数是不是符合预期，可以通过这个查看参数是不是符合正则化之后的性质，从而来判断代码是否实现正确）

**Comment by yeyupiaoling** [comment]
@nepeplwu 好的，谢谢你的回答，我终于明白了。
