### ISSUE TITLE
Images not shown 

### ISSUE THREAD

**Issue by findmyway** [PaddlePaddle/VisualDL#531]
The following code snippet works well with v1.0.0

```python
from visualdl import *
logdir = "tmp"
logger = LogWriter(logdir, sync_cycle=100)

# mark the components with 'train' label.
with logger.mode("train"):
    image_input = logger.image("images/input", 1)
import numpy as np
for _ in range(100):
    image_input.start_sampling()
    image_input.add_sample([28, 28], np.random.rand(28*28) * 255)
    image_input.finish_sampling()
```
![image](https://user-images.githubusercontent.com/5612003/52915198-e61fa080-330b-11e9-9623-6d1656d70710.png)

However, with v1.2.1 the image is missing in the front end.
![image](https://user-images.githubusercontent.com/5612003/52915236-24b55b00-330c-11e9-867b-fe70c2f9aff3.png)

I'm pretty sure that data is saved to the log dir correctly by using `LogReader`.

Ref #529

**Comment by linshuliang** [comment]
Your code works well in the current version.
