### ISSUE TITLE
Pytorch "TypeError: add_record(): incompatible function arguments" while training the model

### ISSUE THREAD

**Issue by AndreiChirap** [PaddlePaddle/VisualDL#533]
TypeError: add_record(): incompatible function arguments. The following argument types are supported:
    1. (self: visualdl.core.HistogramWriter__float, arg0: int, arg1: List[float])

Here is the code :
###############################################################################
 # histogram
        weight_list = net.conv1.weight.view(6*3*5*5,-1)
        
        histogram0.add_record(train_step,weight_list)**<<<<------ here occurs the problem**

        # image
        image1.start_sampling()
        image1.add_sample([96, 25], net.conv2.weight.view(16 * 6 * 5 * 5, -1))**<<<<------ and here** 

        image1.finish_sampling()

        image2.start_sampling()
        image2.add_sample([18, 25], net.conv1.weight.view(6 * 3 * 5 * 5, -1))**<<<<------ and here** 
        image2.finish_sampling()

#################################################################################
also a similar problem occurs  for  "image1.add_sample([96, 25], net.conv2.weight.view(16 * 6 * 5 * 5, -1))"

Does anyone know what should I do ?

**Comment by idea-launch-lab** [comment]
Same issue while re-creating pytorch demo from: 
https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/pytorch/pytorch_cifar10.py

running in Anaconda with python 2.7
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-85-32d3be1e7871> in <module>()
     25         # histogram
     26         weight_list = net.conv1.weight.view(6 * 3 * 5 * 5, -1)
---> 27         histogram0.add_record(train_step, weight_list)
     28 
     29         # image

TypeError: add_record(): incompatible function arguments. The following argument types are supported:
    1. (self: visualdl.core.HistogramWriter__float, arg0: int, arg1: List[float]) -> None

Invoked with: <visualdl.core.HistogramWriter__float object at 0x124880378>, 0, tensor([[ 0.1016],
        [-0.0310],
        [-0.0746],
        :
```

**Comment by AndreiChirap** [comment]
Try to convert form tensor to numpy, this trick worked for me

**Comment by MBasarte** [comment]
Hey! This is what I did to get it working but I'm not completely sure if it's correct:


        weight_list = net.conv1.weight.view(6*3*5*5, -1)
        histogram0.add_record(train_step, weight_list.detach().numpy())

        # image
        image1.start_sampling()
        image1.add_sample([96, 25], net.conv2.weight.view(16*6*5*5, -1).detach().numpy())
        image1.finish_sampling()

        image2.start_sampling()
        image2.add_sample([18, 25], net.conv1.weight.view(6*3*5*5, -1).detach().numpy())
        image2.finish_sampling()


        train_step += 1

        # print statistics
        running_loss += loss.data.item()

I hope it helps! And if something it's wrong please tell me and i'll try another aproach!
