### ISSUE TITLE
VisualDL graph支持Paddle fluid保存的模型可视化展示？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#534]
我在文档看到的：http://paddlepaddle.org/documentation/docs/zh/1.3/release_note.html#visualdl

是直接显示吗？不需要转换成onnx？

**Comment by nepeplwu** [comment]
是的，1.3.0版本已经可以直接支持paddle模型的展示了，使用方法为：
1. 在paddle代码中，调用fluid.io.save_inference_model()接口保存模型
2. 在启动命令中，使用 --model_pb [paddle_model_dir] 加载paddle模型

**Comment by yeyupiaoling** [comment]
@nepeplwu 好的，谢谢。

**Comment by yxchng** [comment]
--model_pb does not work. is this a bug?

**Comment by yeyupiaoling** [comment]
@yxchng You can use this commad:
```
visualdl -logdir you_log_path/ -m you_infer_model_path/
```

**Comment by yxchng** [comment]
@yeyupiaoling It does not work. I think the problem is similar to this https://github.com/PaddlePaddle/VisualDL/issues/505 and the log I got is https://github.com/PaddlePaddle/VisualDL/issues/538
