### ISSUE TITLE
No pip support for python3.7

### ISSUE THREAD

**Issue by v587su** [PaddlePaddle/VisualDL#536]
I have to rename the file to install.

**Comment by v587su** [comment]
Rename doesn't work.
Python version mismatch: module was compiled for version 3.6, while the interpreter is running version 3.7.

**Comment by nepeplwu** [comment]
@v587su ,thank you for your attention. We just released the VisualDL for python3.7

**Comment by PiotrFaj** [comment]
Hej,
Marku sytuacja na chwilę obecną wygląda następująco:
- z dostarczonych dysków wy separowano pliki odpowiedzialne za wirtaulene
maszyny oraz przekonwertowane pliki tak, aby może utworzyć tymczasowe
środowisko.
- czasochłonność polega na dobraniu sprzetu w taki sposób, aby móc
udzwignośc wszystkie maszyny w tym samym czasie.
Ja szacuje, że do końca tygodnia (jak przy wstępnych założeniach)
środowisko testowe będzie uruchomione.
Później jeszcze potrzebuje czas na analizę tego co znajduje sie na
poszczególnych maszynach oraz co znajduje sie na zabezpieczonych dyskach.

Pozdrawiam
Piotr Faj

**Comment by nepeplwu** [comment]
@v587su , visualdl supported python3.7 now , you can install it via pip.
