### ISSUE TITLE
Error trying to visualize fluid model

### ISSUE THREAD

**Issue by yxchng** [PaddlePaddle/VisualDL#538]
I got the following error trying to visualize fluid model

> 
> [INFO 2019-03-30 19:59:18,456 visualdl:336]  port=8040
>  * Serving Flask app "visualdl" (lazy loading)
>  * Environment: production
>    WARNING: Do not use the development server in a production environment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> [INFO 2019-03-30 19:59:18,477 _internal.py:97]  * Running on http://0.0.0.0:8040/ (Press CTRL+C to quit)
> [INFO 2019-03-30 19:59:25,379 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:25] "GET / HTTP/1.1" 302 -
> [INFO 2019-03-30 19:59:25,402 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:25] "GET /static/index.html HTTP/1.1" 304 -
> [INFO 2019-03-30 19:59:25,544 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:25] "GET /static/manifest.6522bbde709d082003dd.js HTTP/1.1" 304 -
> [INFO 2019-03-30 19:59:25,544 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:25] "GET /static/index.6522bbde709d082003dd.js HTTP/1.1" 304 -
> [INFO 2019-03-30 19:59:25,545 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:25] "GET /static/vendor.be5992587b9a973e91dc.js HTTP/1.1" 304 -
> [INFO 2019-03-30 19:59:26,247 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:26] "GET /data/language HTTP/1.1" 200 -
> [WARNING 2019-03-30 19:59:26,248 lib.py:388] update cache /data/runs
> [WARNING 2019-03-30 19:59:26,248 lib.py:388] update cache /data/plugin/scalars/tags
> [WARNING 2019-03-30 19:59:26,249 lib.py:388] update cache /data/plugin/histograms/tags
> [INFO 2019-03-30 19:59:26,250 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:26] "GET /data/runs HTTP/1.1" 200 -
> [ERROR 2019-03-30 19:59:26,252 lib.py:380] Unexpected error: <class 'RuntimeError'>
> [/work/VisualDL/visualdl/utils/filesystem.h:63]
> <traceback object at 0x110dc8e88>
> [ERROR 2019-03-30 19:59:26,252 lib.py:380] Unexpected error: <class 'RuntimeError'>
> [/work/VisualDL/visualdl/utils/filesystem.h:63]
> <traceback object at 0x110dc8f08>
> [INFO 2019-03-30 19:59:26,374 _internal.py:97] 127.0.0.1 - - [30/Mar/2019 19:59:26] "GET /static/assets/ic_logo.85c8de4b2220e0bd16608970db5ffe61.svg HTTP/1.1" 200 -
> [ERROR 2019-03-30 19:59:28,257 lib.py:380] Unexpected error: <class 'RuntimeError'>
> [/work/VisualDL/visualdl/utils/filesystem.h:63]
> <traceback object at 0x110dc8dc8>
> [ERROR 2019-03-30 19:59:28,258 lib.py:380] Unexpected error: <class 'RuntimeError'>
> [/work/VisualDL/visualdl/utils/filesystem.h:63]
> <traceback object at 0x110dc8d88>

**Comment by nepeplwu** [comment]
@yxchng , what is the version of visualdl you installed?
