### ISSUE TITLE
Import Error: cannot import name 'LogWriter'

### ISSUE THREAD

**Issue by khinmaunghtay4ah** [PaddlePaddle/VisualDL#540]
When I try to import 
`from visualdl import LogWriter`,  I got the following import error. 

`Traceback (most recent call last):
  File "visualdl.py", line 4, in <module>
    from visualdl import LogWriter
  File "C:\Program Files (x86)\kmh\Lib\site-packages\chestxray\input\visualdl.py", line 4, in <module>
    from visualdl import LogWriter
ImportError: cannot import name 'LogWriter'`

I am running the code on Windows 10, python 3.6.6 with virtual environment.

**Comment by nepeplwu** [comment]
@kmh4ah , This is because your test file name is `visualdl.py`, which causes the Python interpreter to use your test file first when looking for the visualdl module, so you cannot find the LogWriter. Try using another name as the test file name (eg test.py)

**Comment by khinmaunghtay4ah** [comment]
Thank your @nepeplwu . 
Error has been solved.
