### ISSUE TITLE
node names in model graph not match the setting of  name attributes by paddle api

### ISSUE THREAD

**Issue by LeLiu** [PaddlePaddle/VisualDL#543]
when using visaldl to display a paddlepaddle model,  the node names are automatic numbers like 'conv2d_0', 'conv2d_1' ... ,  not the values named by python code.

**Comment by linshuliang** [comment]
The graph component will not read the values name in the python code. 

As a matter of fact,  the node names in the graph are given according to the name of paddle op. 

Take 'conv2d_0' and 'conv2d_1' for example,  'conv2d_0'  is the first conv2d op of the paddle model, and 'conv2d_1' is the second conv2d op of the paddle model.
