### ISSUE TITLE
不联网编译visualDL

### ISSUE THREAD

**Issue by yxfGrace** [PaddlePaddle/VisualDL#544]
请问visualDL是否可以在不联网情况下通过python setup.py bdist_wheel编译？
一些外部依赖库是否可以提前下载好？

**Comment by linshuliang** [comment]
必须联网，因为 npm 会根据 frontend/package.json 下载相应的依赖。
执行
```shell
python setup.py bdist_wheel
```
不联网，npm 会因下载不了依赖而报错。
