### ISSUE TITLE
Segmentation fault using dict

### ISSUE THREAD

**Issue by sh0416** [PaddlePaddle/VisualDL#548]
```
logger = LogWriter('log', sync_cycle=10)
with logger.mode("train"):
    logger_dict = dict()
    logger_dict['train_acc'] = logger.scalar("scalars/train_acc")
    logger_dict['train_norm'] = logger.scalar("scalars/train_norm")
    logger_dict['train_loss'] = logger.scalar("scalars/train_loss")
```
I got segmentation fault

```
logger = LogWriter('log', sync_cycle=10)
with logger.mode("train"):
    a = logger.scalar("scalars/train_acc")
    b = logger.scalar("scalars/train_norm")
    c = logger.scalar("scalars/train_loss")
```
It works,

Is there any suggestion to use dict structure for scalar instance?

Thanks,

**Comment by linshuliang** [comment]
from visualdl import LogWriter
logger = LogWriter('log', sync_cycle=10)
with logger.mode("train"):
    logger_dict = dict()
    logger_dict['train_acc'] = logger.scalar("scalars/train_acc")
    logger_dict['train_norm'] = logger.scalar("scalars/train_norm")
    logger_dict['train_loss'] = logger.scalar("scalars/train_loss")

this program works, no segmentation fault occur.

**Comment by linshuliang** [comment]
```python
from visualdl import LogWriter
logger = LogWriter('log', sync_cycle=10)
with logger.mode("train"):
    logger_dict = dict()
    logger_dict['train_acc'] = logger.scalar("scalars/train_acc")
    logger_dict['train_norm'] = logger.scalar("scalars/train_norm")
    logger_dict['train_loss'] = logger.scalar("scalars/train_loss")
```

this program works, no segmentation fault occurs.

**Comment by sh0416** [comment]
@linshuliang 
I figure out what is wrong. logdir directory already has scalar term. Is there any graceful warning for this situation?
