### ISSUE TITLE
Visualdl cannt start in windows

### ISSUE THREAD

**Issue by xinxinbingzi** [PaddlePaddle/VisualDL#551]
(vdl) C:\Users\x0714>visualdl --logdir ./vdllog --host 127.0.0.1 --port 8989
python: can't open file 'D:\Program': [Errno 2] No such file or directory

**Comment by linshuliang** [comment]
In Windows system,  the directory path `--logdir` must be designated in full name, such as 'C:\Users\x0714\vdllog'.

**Comment by linshuliang** [comment]
我在 win10 上运行[demo程序](https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/component/scalar-demo.py)，生成了日志文件夹 `log`。之后执行命令: 

```
visualdl --logdir D:\visualdl\log --host 127.0.0.1 --port 8088
```

就能在 chrome 浏览器中查看visualdl 显示的图表。

**Comment by linshuliang** [comment]
请问你是在 anaconda 环境下运行的程序吗？

你遇到的问题，初步预判是路径设置的bug。你重建一个 conda env，

```
conda create --name visualdl_env python=3.6
conda activate visualdl_env
pip install visualdl
```

重新运行一次程序，看是否还会出现同样的问题？

**Comment by leehownash** [comment]
python "D:\Program Files\Python36\Scripts\visualdl" --logdir=test_log/ --port=8080

then it will work
