### ISSUE TITLE
visualDL如何查看网络结构graph？报错：malloc_error_break

### ISSUE THREAD

**Issue by my777777** [PaddlePaddle/VisualDL#554]
按照READEME.md的Quick Start安装visualDL，无法查看graph
依次运行以下命令：

> pip install --upgrade visualdl
> vdl_create_scratch_log
> visualdl --logdir=scratch_log -m scratch_log/mnist_model.onnx

在浏览器中点击『GRAPHS』后出现error，信息如下：

> Python(6095,0x700007183000) malloc: *** error for object 0x7fce77307718: pointer being freed was not allocated
> *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6

版本信息如下：
Mac: 10.13
Python: 2.7.16
visualDL: 1.3.0

**Comment by songyouwei** [comment]
I met the same issue.

**Comment by linshuliang** [comment]
是在 chrome 浏览器打开页面吗？

**Comment by linshuliang** [comment]
protobuf 版本太高，会导致graph无法显示。
重装 protobuf，可以解决这个问题：
```
pip install protobuf==3.6.1
```

**Comment by PeterPanZH** [comment]
VisualDL 2.0 will integrate netron as model visualization tool.
