### ISSUE TITLE
使用VisuslDL查看网络结构时gurphs显示空白

### ISSUE THREAD

**Issue by tianjie491** [PaddlePaddle/VisualDL#557]
在windows上使用VisuslDL查看网络结构时gurphs显示空白，查看metrics时没有问题。模型保存是按visualdl指南上保存的，应该没有问题啊
![图片](https://user-images.githubusercontent.com/48859246/62599748-a3846b80-b91f-11e9-9b9f-b0069b4aabbd.png)
这是为什么，怎么解决？

**Comment by tianjie491** [comment]
浏览器用的火狐，用ie打不开，不知道是什么原因

**Comment by tianjie491** [comment]
删除log文件夹后报RuntimeError: [D:\VisualDL\visualdl/utils/filesystem.h:63]

**Comment by linshuliang** [comment]
protobuf 版本太高，会导致graph无法显示。
重装 protobuf，可以解决这个问题：
```
pip install protobuf==3.6.1
```

由于 visualDL 开发使用了 Google 的 protobuf，因此建议使用 chrome 浏览器。
