### ISSUE TITLE
VisualDL 无法可视化计算图

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/VisualDL#559]
按照文档也无法可视化计算图, 并且会出现如下错误, 接着自动退出
[ERROR 2019-08-25 17:25:09,300 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/logic/sdk.cc:85]
<traceback object at 0x10cd07c30>
[ERROR 2019-08-25 17:25:11,305 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/logic/sdk.cc:85]
<traceback object at 0x10cd07c80>
[ERROR 2019-08-25 17:25:13,311 visualdl:60] server temporary error, will retry latter.
[INFO 2019-08-25 17:25:13,312 _internal.py:122] 127.0.0.1 - - [25/Aug/2019 17:25:13] "GET /data/plugin/histograms/tags HTTP/1.1" 200 -
[INFO 2019-08-25 17:25:14,563 _internal.py:122] 127.0.0.1 - - [25/Aug/2019 17:25:14] "GET /data/plugin/scalars/scalars?run=train&tag=scratch%2Fscalar HTTP/1.1" 200 -
[INFO 2019-08-25 17:25:15,343 _internal.py:122] 127.0.0.1 - - [25/Aug/2019 17:25:15] "GET /data/plugin/scalars/scalars?run=train&tag=scratch%2Fscalar HTTP/1.1" 200 -
[INFO 2019-08-25 17:25:15,899 _internal.py:122] 127.0.0.1 - - [25/Aug/2019 17:25:15] "GET /data/plugin/scalars/scalars?run=train&tag=scratch%2Fscalar HTTP/1.1" 200 -
[WARNING 2019-08-25 17:25:17,216 lib.py:388] update cache /data/plugin/images/tags
[ERROR 2019-08-25 17:25:17,217 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/logic/sdk.cc:85]
<traceback object at 0x10cd1de60>
[WARNING 2019-08-25 17:25:17,219 lib.py:388] update cache /data/plugin/audio/tags
[ERROR 2019-08-25 17:25:17,220 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/logic/sdk.cc:85]
<traceback object at 0x10cd21dc0>
[WARNING 2019-08-25 17:25:17,222 lib.py:388] update cache /data/plugin/texts/tags
[ERROR 2019-08-25 17:25:17,223 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/logic/sdk.cc:85]
<traceback object at 0x10cd24fa0>
python3.7(33729,0x70000f46f000) malloc: *** error for object 0x7febb2851708: pointer being freed was not allocated
python3.7(33729,0x70000f46f000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    33729 abort      visualdl --logdir=random_log/ --port=8080 -m ./inference_model

**Comment by linshuliang** [comment]
protobuf 版本太高，会导致graph无法显示。
重装 protobuf，可以解决这个问题：
```
pip install protobuf==3.6.1
```

**Comment by ghost** [comment]
可行, 谢谢
