### ISSUE TITLE
How to plot neural network structure using VisualDL

### ISSUE THREAD

**Issue by CBD88** [PaddlePaddle/VisualDL#566]
Where i can find the sample program to visualize neural network structure like mention in home page.
"To display the paddle model, all you have to do is:
call the fluid.io.save_inference_model()interface to save paddle model
use visualdl --model_pb [paddle_model_dir] to load paddle model in command line "

**Comment by PeterPanZH** [comment]
VisualDL 2.0 beta now support visualize neural network structure. Please refer to [Graphs](https://github.com/PaddlePaddle/VisualDL/tree/develop/docs/components#Graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6) for more infomation.
