### ISSUE TITLE
使用VisualDL保存模型结构时，下载下来图片不完整

### ISSUE THREAD

**Issue by PointCloudNiphon** [PaddlePaddle/VisualDL#567]
使用VisualDL保存模型结构时，下载下来图片不完整，最右侧缺失

**Comment by PointCloudNiphon** [comment]
![image](https://user-images.githubusercontent.com/37015371/70328821-efff9980-1874-11ea-88b4-35f2f3ff8748.png)

**Comment by PeterPanZH** [comment]
请使用VisualDL 2.0。如果还有问题请reopen。
