### ISSUE TITLE
存在某一个曲线图有时候刷不出来

### ISSUE THREAD

**Issue by chliang** [PaddlePaddle/VisualDL#568]
![image](https://user-images.githubusercontent.com/1207569/71551904-253e7800-2a2c-11ea-9bea-17b943447a2e.png)

**Comment by linshuliang** [comment]
您好，我们已跟进了这个issue。

**Comment by gxpzy** [comment]
请问这个问题是否已经解决了？

**Comment by ZeyuChen** [comment]
VisualDL 2.0已经可以解决这一问题，欢迎使用。
