### ISSUE TITLE
网络结构可视化

### ISSUE THREAD

**Issue by gxpzy** [PaddlePaddle/VisualDL#569]
1. 在官网看到的神经网络结构的可视化中发现加法操作显示了两个分支，如图所示
![84@(T0HFWX{M45Z{IG(}AW8](https://user-images.githubusercontent.com/17157193/72682946-c5f4f480-3b0d-11ea-9ce9-6310cca2e53b.png)
自己写的时候进行可视化并没有显示分支，整个网络就是一条线下来了，每次都要点了看输入是哪个
2. 卷积操作可视化时加法操作也显示出来了，而上图中的加法似乎是包含在了卷积块中
![0X8 L$ {Q0TC61VHN2PMP09](https://user-images.githubusercontent.com/17157193/72682998-68ad7300-3b0e-11ea-9e2c-4cf4ca4fe3de.png)
网络仅定义了一个卷积操作，但加法操作也独立显示出来了

**Comment by PeterPanZH** [comment]
VisualDL 2.0将使用netron作为网络结构可视化工具，请期待。
