### ISSUE TITLE
when i'm going to visualize the "__model__"file,i got this error

### ISSUE THREAD

**Issue by shaqing** [PaddlePaddle/VisualDL#580]
when i use the command "visualdl --m [model_dir]", i met this error.

visualdl: error: the following arguments are required: --logdir

how can i figure out it, i need help, thank you!

**Comment by ShenYuhan** [comment]
You can use VisualDL>=2.0.0b6 to visualize model construction.
`pip install visualdl==2.0.0b6 -U`
And:
`visualdl --model ${MODEL_FILE_PATH}`
See [graph](https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README.md#graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6) for more information.
