### ISSUE TITLE
Con't visual graphs in ai studio.

### ISSUE THREAD

**Issue by TanTingyi** [PaddlePaddle/VisualDL#603]
I followed this tutorial  [https://aistudio.baidu.com/aistudio/projectdetail/34655?qq-pf-to=pcqq.group](url) . But con't visual graphs.

**Comment by PeterPanZH** [comment]
related to ai studio. someone will contact you later.

**Comment by PeterPanZH** [comment]
@TanTingyi Please refer to https://aistudio.baidu.com/aistudio/projectdetail/325476 for VisualDL in AI Studio. If fails again, please reopen this issue. Thanks.
