### ISSUE TITLE
官方实例都不能运行

### ISSUE THREAD

**Issue by Gs-Zhang** [PaddlePaddle/VisualDL#610]
(paddle) gszhang@gszhang-TM1613:~$ visualdl --logdir=./log --port=8081 --model_pb=/home/gszhang/Code/paddlepaddle/NLP/paddle_lenet_5_model
[INFO 2020-03-28 14:13:02,702 visualdl:336]  port=8081
 * Serving Flask app "visualdl" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO 2020-03-28 14:13:02,705 _internal.py:113]  * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
[INFO 2020-03-28 14:13:09,337 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:09] "GET / HTTP/1.1" 302 -
[INFO 2020-03-28 14:13:09,346 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:09] "GET /static/index.html HTTP/1.1" 200 -
[INFO 2020-03-28 14:13:09,390 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:09] "GET /static/vendor.b1c57cda17102ce039c3.js HTTP/1.1" 200 -
[INFO 2020-03-28 14:13:09,395 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:09] "GET /static/manifest.55f888f6ce9bc7495353.js HTTP/1.1" 200 -
[INFO 2020-03-28 14:13:09,396 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:09] "GET /static/index.55f888f6ce9bc7495353.js HTTP/1.1" 200 -
[INFO 2020-03-28 14:13:10,873 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:10] "GET /data/language HTTP/1.1" 200 -
[WARNING 2020-03-28 14:13:10,874 lib.py:388] update cache /data/runs
[ERROR 2020-03-28 14:13:10,874 app.py:1891] Exception on /data/runs [GET]
Traceback (most recent call last):
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gszhang/miniconda3/envs/paddle/bin/visualdl", line 172, in runs
    data = cache_get('/data/runs', lib.get_modes, log_reader)
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/visualdl/server/lib.py", line 389, in _handler
    data = func(*args, **kwargs)
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/visualdl/server/lib.py", line 33, in get_modes
    return storage.modes()
  File "/home/gszhang/miniconda3/envs/paddle/lib/python3.7/site-packages/visualdl/python/storage.py", line 83, in modes
    return self.reader.modes()
RuntimeError: [/work/VisualDL/visualdl/utils/filesystem.h:63] 
[INFO 2020-03-28 14:13:10,876 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:10] "GET /data/runs HTTP/1.1" 500 -
[WARNING 2020-03-28 14:13:10,997 lib.py:388] update cache /data/plugin/scalars/tags
[ERROR 2020-03-28 14:13:10,998 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x7fb2a8759eb0>
[WARNING 2020-03-28 14:13:10,999 lib.py:388] update cache /data/plugin/histograms/tags
[ERROR 2020-03-28 14:13:11,000 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x7fb2a8f8ae60>
[INFO 2020-03-28 14:13:11,058 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:11] "GET /static/favicon.png HTTP/1.1" 404 -
[ERROR 2020-03-28 14:13:12,999 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x7fb2a8759d20>
[ERROR 2020-03-28 14:13:13,003 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x7fb2a8759370>
[ERROR 2020-03-28 14:13:15,002 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x7fb2a8759eb0>
[ERROR 2020-03-28 14:13:15,006 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x7fb2a8f8ae60>
[ERROR 2020-03-28 14:13:17,003 visualdl:60] server temporary error, will retry latter.
[INFO 2020-03-28 14:13:17,004 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:17] "GET /data/plugin/scalars/tags HTTP/1.1" 200 -
[ERROR 2020-03-28 14:13:17,007 visualdl:60] server temporary error, will retry latter.
[INFO 2020-03-28 14:13:17,009 _internal.py:113] 127.0.0.1 - - [28/Mar/2020 14:13:17] "GET /data/plugin/histograms/tags HTTP/1.1" 200 -

**Comment by Gs-Zhang** [comment]
![2020-03-28 14-19-23 的屏幕截图](https://user-images.githubusercontent.com/48624777/77816642-336d6480-70ff-11ea-9afa-e95eed614658.png)

**Comment by Gs-Zhang** [comment]
Graphy那个

**Comment by ShenYuhan** [comment]
您说的是哪个demo，我这边试一下

**Comment by ArtyZe** [comment]
@ShenYuhan 
me too

**Comment by ArtyZe** [comment]
@Gs-Zhang 
兄弟，我昨天试了一下，这个创建scratch log的操作在linux下ok，但是windows下即使anaconda都不可以，所以不用想了。
然后如果你是想看graph的话，不用创建scratch log，--log_dir随便选一个即可，--model_pb选择你的模型所在路径，也就是__model__及各层参数那个，之后在界面中选择上面一层的graph即可看到。
@ShenYuhan 
顺便真的想对baidu 的开发者们提个建议，issue回复快一些吧，文档写好一点吧。。。虽然他们也确实做了很不错的工作

**Comment by ShenYuhan** [comment]
@ArtyZe 谢谢理解，我们正在重整vdl架构和文档，对issue的处理也会加速

**Comment by ShenYuhan** [comment]
手动将url调整为“http://0.0.0.0:8040/static/index.html#/graphs”，就能看到网络结构了

**Comment by ShenYuhan** [comment]
目前最新版的VisualDL(>=2.0.0b6)已经支持graph，比旧版更加方便易用，具体信息可以参照[graph](https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README.md#graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6)
