### ISSUE TITLE
网页无法显示scalar

### ISSUE THREAD

**Issue by ly7969** [PaddlePaddle/VisualDL#625]
终端运行命令：visualdl --logdir log/train log/val --host 127.0.0.1 --port 8040
然后在网页访问：http://127.0.0.1:8040

网页显示
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

终端提示以下错误：
[INFO 2020-05-15 15:41:24,458 app.py:378]  port=8040
 * Serving Flask app "visualdl.server.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO 2020-05-15 15:41:24,466 _internal.py:113]  * Running on http://127.0.0.1:8040/ (Press CTRL+C to quit)
[INFO 2020-05-15 15:41:28,662 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET / HTTP/1.1" 302 -
[INFO 2020-05-15 15:41:28,663 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /app/index HTTP/1.1" 304 -
[INFO 2020-05-15 15:41:28,689 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /images/logo.svg HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,690 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/bl1SMb5wxFN0g1Bw6hp0j/pages/_app.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,690 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/bl1SMb5wxFN0g1Bw6hp0j/pages/index.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,690 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/runtime/webpack-e11a110ee50f7ffb1cf3.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,691 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/chunks/framework.eb23ff06184ceee71586.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,691 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/chunks/a29ae703.feaf6e1ffb23af153342.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,692 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/chunks/commons.87f9d77eb1da6a75ea66.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,692 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/chunks/95d3061e023a9816f1009bcec638f54ca824fd41.0c2f7bb5fcc2019d84b4.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,693 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/chunks/ee61c61705b6900d9121f8417047d4d8539639ac.fe540fc7026ba6ea9682.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,693 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/chunks/339aab58c38ceac7b172c987250f7f5853a35297.4d13e898664a267b4253.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,694 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/runtime/main-0bf04a70616fb4169f46.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,694 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/bl1SMb5wxFN0g1Bw6hp0j/_buildManifest.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,695 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /_next/static/bl1SMb5wxFN0g1Bw6hp0j/_ssgManifest.js HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,695 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /style/fonts/vdl-icon.ttf HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,698 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /style/fonts/vdl-icon.woff HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:28,702 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:28] "GET /style/fonts/vdl-icon.svg HTTP/1.1" 404 -
[INFO 2020-05-15 15:41:30,341 _internal.py:113] 127.0.0.1 - - [15/May/2020 15:41:30] "GET /scalars HTTP/1.1" 404 -

**Comment by PeterPanZH** [comment]
请问是通过pip安装的吗？

**Comment by ly7969** [comment]
由于通过pip install --upgrade visualdl，只能安装1.3版本，所以改为
通过代码方式安装：
git clone https://github.com/PaddlePaddle/VisualDL.git
cd VisualDL
python setup.py bdist_wheel
pip install --upgrade dist/visualdl-*.whl

**Comment by PeterPanZH** [comment]
那这个问题刚刚的提交已经修复了，请更新一下代码再试一次~
另外develop分支还在开发中，可能会有很多问题，欢迎随时反馈，感谢

**Comment by ly7969** [comment]
> 那这个问题刚刚的提交已经修复了，请更新一下代码再试一次~
> 另外develop分支还在开发中，可能会有很多问题，欢迎随时反馈，感谢

运行命令：python setup.py bdist_wheel，提示以下错误

/home/lishi/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '2.0.0-alpha.2' to '2.0.0a2'
  normalized_version,
running bdist_wheel
running build
running build_py
ARG: 
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
471.0 KiB / 471.0 KiB (100 %) 238.2 KiB/s in  1s ETA:  0s
info: latest update on 2020-05-15, rust version 1.45.0-nightly (a74d1862d 2020-05-14)
info: downloading component 'cargo'
  5.0 MiB /   5.0 MiB (100 %) 611.2 KiB/s in  9s ETA:  0s
info: downloading component 'clippy'
  2.0 MiB /   2.0 MiB (100 %) 575.4 KiB/s in  4s ETA:  0s
info: downloading component 'rust-docs'
 12.3 MiB /  12.3 MiB (100 %) 257.6 KiB/s in 40s ETA:  0s
info: downloading component 'rust-std'
 15.7 MiB /  15.7 MiB (100 %) 329.6 KiB/s in  1m  1s ETA:  0s
info: downloading component 'rustc'
 63.6 MiB /  63.6 MiB (100 %) 444.8 KiB/s in  3m 36s ETA:  0s    
info: downloading component 'rustfmt'
  3.4 MiB /   3.4 MiB (100 %) 374.4 KiB/s in 10s ETA:  0s
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
 63.6 MiB /  63.6 MiB (100 %)  19.1 MiB/s in  3s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'nightly'

  nightly installed - rustc 1.45.0-nightly (a74d1862d 2020-05-14)


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable.

To configure your current shell run source $HOME/.cargo/env
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    54  100    54    0     0    101      0 --:--:-- --:--:-- --:--:--   101
100  2341  100  2341    0     0    787      0  0:00:02  0:00:02 --:--:--  1102
Installing Yarn!
> Downloading tarball...

[1/2]: https://yarnpkg.com/latest.tar.gz --> /tmp/yarn.tar.gz.CBC87nkZwQ
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    107      0 --:--:-- --:--:-- --:--:--   107
100    93  100    93    0     0     34      0  0:00:02  0:00:02 --:--:--    50
100   630  100   630    0     0    148      0  0:00:04  0:00:04 --:--:--   462
100 1215k  100 1215k    0     0  48870      0  0:00:25  0:00:25 --:--:-- 45251

[2/2]: https://yarnpkg.com/latest.tar.gz.asc --> /tmp/yarn.tar.gz.CBC87nkZwQ.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    61  100    61    0     0    348      0 --:--:-- --:--:-- --:--:--   348
100    97  100    97    0     0     30      0  0:00:03  0:00:03 --:--:--    49
100   634  100   634    0     0    189      0  0:00:03  0:00:03 --:--:--  619k
100  1028  100  1028    0     0    287      0  0:00:03  0:00:03 --:--:--   287
> Verifying integrity...
gpg: key 86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: Signature made 2020年03月09日 星期一 23时52分13秒 CST using RSA key ID 69475BAA
gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
     Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
> GPG signature looks good
> Extracting to ~/.yarn...
> Adding to $PATH...
> We've added the following to your /home/lishi/.bashrc
> If this isn't the profile of your current shell then please add the following to your correct profile:
   
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

/home/lishi/.yarn/lib/cli.js:46099
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/lishi/.yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
> Yarn was installed, but doesn't seem to be working :(.
Traceback (most recent call last):
  File "setup.py", line 112, in <module>
    entry_points={'console_scripts': ['visualdl=visualdl.server.app:main']})
  File "/home/lishi/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/lishi/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lishi/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/lishi/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lishi/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/lishi/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lishi/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lishi/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lishi/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lishi/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 88, in run
    subprocess.check_call(cmd, env=env)
  File "/home/lishi/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'scripts/build.sh']' returned non-zero exit status 1.

**Comment by PeterPanZH** [comment]
请问nodejs版本是多少？

**Comment by ly7969** [comment]
> 请问nodejs版本是多少？

v4.2.6

**Comment by PeterPanZH** [comment]
编译需要node10以上，建议装个12

**Comment by PeterPanZH** [comment]
刚发了新版，可以使用`pip install visualdl==2.0.0a3`安装
