### ISSUE TITLE
命令行启动VisualDL之后，每次访问VisualDL的页面时命令行都会报错

### ISSUE THREAD

**Issue by tt36999** [PaddlePaddle/VisualDL#645]
![image](https://user-images.githubusercontent.com/12522418/83122769-aa76a780-a106-11ea-81ae-7885c7ab33ae.png)
![image](https://user-images.githubusercontent.com/12522418/83123235-430d2780-a107-11ea-86a0-f46d335a2e3c.png)
![image](https://user-images.githubusercontent.com/12522418/83123498-92ebee80-a107-11ea-9077-c6582161ff7d.png)
![image](https://user-images.githubusercontent.com/12522418/83123511-97180c00-a107-11ea-962f-09768a40ddca.png)

测试了两个环境
Win10, python 3.7.6 上面那张图
Centos8 python 3.6.8 下面的那张图
并且在服务器启动之后，无法读取部分图表，我在logdir的目录中保存了多个图表，但是在DL的页面只能看到一个图表和一个曲线

**Comment by PeterPanZH** [comment]
duplicated with #646
