### ISSUE TITLE
命令行启动VisualDL，打开DL页面之后名两行报错

### ISSUE THREAD

**Issue by tt36999** [PaddlePaddle/VisualDL#646]
![image](https://user-images.githubusercontent.com/12522418/83123882-0857bf00-a108-11ea-9c5d-e4ff08a7167d.png)
![image](https://user-images.githubusercontent.com/12522418/83123898-0e4da000-a108-11ea-95d1-638f69e39b24.png)
![image](https://user-images.githubusercontent.com/12522418/83123962-23c2ca00-a108-11ea-8650-78cf749e55b0.png)
![image](https://user-images.githubusercontent.com/12522418/83124031-3c32e480-a108-11ea-8976-daedcca32cab.png)

测试了两个环境
Win10, python 3.7.6 上面那张图
Centos8 python 3.6.8 下面的那张图
并且在服务器启动之后，无法读取部分图表，我在logdir的目录中保存了多个图表，但是在DL的页面只能看到一个图表和一个曲线

**Comment by linhandev** [comment]
vdl 升2了，或许可以试试

**Comment by PeterPanZH** [comment]
1.x版本已经不再维护，欢迎试用VisualDL 2.0
`pip install --upgrade visualdl==2.0.0b4`

**Comment by tt36999** [comment]
问题解决，非常感谢
