### ISSUE TITLE
请问如何同时显示多次不同训练的scalar curves？

### ISSUE THREAD

**Issue by fantasysee** [PaddlePaddle/VisualDL#653]
VisualDL 一次只能显示一次训练工程文件夹下的 scalar curves 吗？比如说，我有几次设置了不同超参数的训练结果，都记录了scalar，请问应该如何把他们放在同一幅图上呢？

**Comment by fantasysee** [comment]
比如说有好多个打了时间戳的log文件夹，然后每个log文件夹下都包含了mode为train，name为acc的scalar，如何同时显示呢？

**Comment by fantasysee** [comment]
也尝试过这样命令行调用 VisualDL ：visualdl --logdir "2020-05-31_14-32-25, 2020-06-01_21-13-58"  结果无法显示。

**Comment by ShenYuhan** [comment]
您好 有两种方式可以完成您的需求
1 启动命令，空格分割 
```shell
visualdl --logdir dir1 dir2
```
2 指定文件夹为这两个文件夹的父文件夹即可

**Comment by fantasysee** [comment]
感谢您的解答。我发现我在本地安装的VisualDL版本是 1.3.0，与Github上版本不符……怪不得按照Github上的流程走没有奏效。
