### ISSUE TITLE
What is the pourpose of sync_cycle in LogWriter? 

### ISSUE THREAD

**Issue by andreazanetti** [PaddlePaddle/VisualDL#656]
Hi, can anyone clarify what the supposed function of the sync_cycle LogWriter parameter should be?
Looking into the code, I end up here: https://github.com/PaddlePaddle/VisualDL/blob/917c720423d3bfbe580b6e0ec71069efe8fad0a7/visualdl/writer/writer.py#L62 
but from a quick look the **kwargs I was not able to trace it down to the function.

Is it a buffering size or so?
Thank you

**Comment by ShenYuhan** [comment]
`sync_cycle ` is a parameter in version 1.X, means `Specify how often should the system store data into the file system.
        Typically adding a record requires 6 operations.
        System will save the data into the file system once operations count reaches sync_cycle.`.
This parameter has been deleted in version 2.X.

**Comment by andreazanetti** [comment]
thank you, all clear.
