### ISSUE TITLE
graph功能下载图片的问题

### ISSUE THREAD

**Issue by LilyCaiZL** [PaddlePaddle/VisualDL#664]
![N(NS12~VO6DA{EJ8F1N{_W6](https://user-images.githubusercontent.com/40067956/84496925-6d064280-ace0-11ea-9a49-06c5c880b9cb.png)
请问我用graph功能，下载的图片长这个样子，怎么办，png svg都是这样

**Comment by PeterPanZH** [comment]
是个bug，#665 已修复，稍后会发版更新，着急的话可以先编译后使用

**Comment by PeterPanZH** [comment]
Fixed in visualdl 2.0.0.b6
