### ISSUE TITLE
HDFS initialization failed, please check if .hdfscli，cfg exists.

### ISSUE THREAD

**Issue by LWhite027** [PaddlePaddle/VisualDL#668]
from visualdl import LogWriter

if __name__ == '__main__':
    value = [i/1000.0 for i in range(1000)]
    # 初始化一个记录器
    with LogWriter(logdir="./log/scalar_test/train") as writer:
        for step in range(1000):
            # 向记录器添加一个tag为`acc`的数据
            writer.add_scalar(tag="acc", step=step, value=value[step])
            # 向记录器添加一个tag为`loss`的数据
            writer.add_scalar(tag="loss", step=step, value=1/(value[step] + 1))

**Comment by ShenYuhan** [comment]
您好，这只是一个warning，并不影响使用，我们已经修复这个问题，在下个版本中就不再会有错误提示了，

**Comment by ShenYuhan** [comment]
您好，我们在新版本已经优化了此提示，您可以通过以下命令升级：
```shell
pip install visualdl==2.0.0b7 -U
```

**Comment by PeterPanZH** [comment]
fixed in 2.0.0b7
