### ISSUE TITLE
在python脚本中启动出错

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/VisualDL#671]
在python脚本中启动visualdl面板
```
from visualdl.server import app
app.run(logdir='./logs')
```
没有正常启动，版本2.0.0b7，[报错信息](https://github.com/PaddlePaddle/VisualDL/files/4805693/log.txt)

**Comment by PeterPanZH** [comment]
日志中没有看到和visualdl相关的信息，请确定脚本执行到这里了

**Comment by chenwthu** [comment]
注释掉app.run语句后不会报错，似乎是在flask模板渲染过程中出错

**Comment by chenwthu** [comment]
```py
from paddle import fluid
from visualdl.server import app
app.run(logdir='./logs')
```
会出现上述报错信息，vdl不能启动，python意外退出

```py
#from paddle import fluid
from visualdl.server import app
app.run(logdir='./logs')
```
不会出现上述报错信息，但vdl依然不能启动，python意外退出
设置`api_only=True`或`open_browser=True`都不能正常启动

**Comment by ShenYuhan** [comment]
您这边确定指定的logs存在吗，我这里尝试了b7版本。是可以正常执行的，您可以在python脚本环境中单独执行这两句
```python
from visualdl.server import app
app.run("./log", open_broser=True)
```
然后看下结果

**Comment by chenwthu** [comment]
> 您这边确定指定的logs存在吗，我这里尝试了b7版本。是可以正常执行的，您可以在python脚本环境中单独执行这两句
> 
> ```python
> from visualdl.server import app
> app.run("./log", open_broser=True)
> ```
> 
> 然后看下结果

log目录存在，vdl不能启动，提示python意外退出

**Comment by chenwthu** [comment]
在`app.run()`中不使用多进程可以正常启动

**Comment by PeterPanZH** [comment]
意外退出时有什么报错信息吗？怀疑python环境有问题

**Comment by chenwthu** [comment]
> 意外退出时有什么报错信息吗？怀疑python环境有问题

[Crash Report](https://github.com/PaddlePaddle/VisualDL/files/4808455/report.txt)
使用环境macOS 10.15.5 virtualenv python 3.7.7

**Comment by ShenYuhan** [comment]
> 在`app.run()`中不使用多进程可以正常启动

不使用多进程可以正常启动是指？app.run()并没有提供是否使用多进程的选项，您是说自己开启一个子进程执行吗

**Comment by chenwthu** [comment]
> > 在`app.run()`中不使用多进程可以正常启动
> 
> 不使用多进程可以正常启动是指？app.run()并没有提供是否使用多进程的选项，您是说自己开启一个子进程执行吗

在vdl源码中不使用multiprocessing而直接调用`_run()`

**Comment by ShenYuhan** [comment]
我确认一下，您使用run()之后，整个python环境直接退出了？

**Comment by chenwthu** [comment]
> 我确认一下，您使用run()之后，整个python环境直接退出了？

弹出python意外退出的提示，但后续代码能继续执行，看起来没有影响主进程

**Comment by ShenYuhan** [comment]
您方便放下完整的代码和执行的截图吗

**Comment by chenwthu** [comment]
> 您方便放下完整的代码和执行的截图吗

<img width="897" alt="" src="https://user-images.githubusercontent.com/16147671/85218666-eed82900-b3ce-11ea-96ac-7b017c98c4ea.png">

**Comment by ShenYuhan** [comment]
您的flask版本是多少，另外如果直接在python环境中逐条执行脚本，是否直接报错退出？

**Comment by chenwthu** [comment]
> 您的flask版本是多少，另外如果直接在python环境中逐条执行脚本，是否直接报错退出？

Flask==1.1.2

在python环境中执行`app.run()`后打印出`[INFO app.py:119] port=8040`，之后提示python意外退出，但没有退出python shell，按`Ctrl-C`后能回到python shell继续输入

**Comment by ShenYuhan** [comment]
请问您的protobuf的版本是多少呢，
另外您可以按照下面的步骤尝试一下；
 - 1 首先启动时指定logdir为一个不存在的路径，观察是否可以正常启动
 - 2.a 在1可行的情况下，重新打点并重新启动
 - 2.b 在1不可行的情况下，新建一个纯粹的新python环境安装vdl，试下是否还存在这个问题

**Comment by chenwthu** [comment]
> 请问您的protobuf的版本是多少呢，
> 另外您可以按照下面的步骤尝试一下；
> 
> * 1 首先启动时指定logdir为一个不存在的路径，观察是否可以正常启动
> * 2.a 在1可行的情况下，重新打点并重新启动
> * 2.b 在1不可行的情况下，新建一个纯粹的新python环境安装vdl，试下是否还存在这个问题

protobuf==3.12.2
新建环境中无论logdir是否存在都无法正常启动

**Comment by ShenYuhan** [comment]
我这里测试都是可以的，您pip list下，然后把新环境的list贴一下，我再对比下我们有没有不同

**Comment by chenwthu** [comment]
[packages.txt](https://github.com/PaddlePaddle/VisualDL/files/4812364/packages.txt)

**Comment by ShenYuhan** [comment]
您好，之前说的纯净的python环境，是指没有paddlepaddle这些额外包，仅仅安装visualdl和相关依赖的环境，您可以试试

**Comment by chenwthu** [comment]
[packages.txt](https://github.com/PaddlePaddle/VisualDL/files/4812502/packages.txt)
还是不能启动

**Comment by ShenYuhan** [comment]
您确定执行的python环境是这个虚拟环境吗，执行一下
```shell
which python
```
看下

**Comment by chenwthu** [comment]
> 您确定执行的python环境是这个虚拟环境吗，执行一下
> 
> ```shell
> which python
> ```
> 
> 看下

确定，/Users/USER/Library/Caches/pypoetry/virtualenvs/paddlepaddle-venv-lEakuMU9-py3.7/bin/python

**Comment by ShenYuhan** [comment]
要不您给个联系方式，发我邮箱就好 我们用qq或者其他沟通下，交流快捷一些

**Comment by chenwthu** [comment]
应该是操作系统的问题，[Seg Fault on OSX when multiprocessing](https://bugs.python.org/issue37677)
在`if __name__ == '__main__'`中添加`multiprocessing.set_start_method('spawn')`可以解决

**Comment by PeterPanZH** [comment]
赞~ 我怀疑过可能是这个问题，但是没有仔细研究，因为本地macOS+python3.7也没复现
