### ISSUE TITLE
Safari中无法显示折线图

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/VisualDL#674]
<img width="976" alt="" src="https://user-images.githubusercontent.com/16147671/85382855-f2f07c00-b571-11ea-9fab-0dd8d89ffacc.png">
Scalars中能识别到tag但显示为空白

**Comment by PeterPanZH** [comment]
请问Safari版本是多少？可以截个about的图吗？谢谢~

**Comment by chenwthu** [comment]
> 请问Safari版本是多少？可以截个about的图吗？谢谢~

Safari Version 13.1.1 (15609.2.9.1.2)

**Comment by PeterPanZH** [comment]
看起来是Safari的bug，已经做了兼容，下个beta版本会修复。急用的话可以用源码编译~
