### ISSUE TITLE
gragh组件使用错误

### ISSUE THREAD

**Issue by thrkingd** [PaddlePaddle/VisualDL#678]
我在win10下面安装了2.0.0b6的版本，按照使用指南在命令行输入visualdl，在浏览器中打开地址，但是显示的页面上找不到可以上传文件的按键（就是右边的按键栏），是浏览器的问题吗？
(wj) E:\soft\paddlepaddle-models-develop\models\PaddleCV\video>visualdl
HDFS initialization failed, please check if .hdfscli，cfg exists.
[INFO 2020-06-24 21:01:05,662 app.py:141]  port=8040
Model path  should be file path, please check this path.
 * Serving Flask app "visualdl" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO 2020-06-24 21:01:05,895 _internal.py:122]  * Running on http://127.0.0.1:8040/ (Press CTRL+C to quit)
[INFO 2020-06-24 21:01:16,686 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[32mGET / HTTP/1.1[0m" 302 -
[INFO 2020-06-24 21:01:16,689 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[32mGET /app/ HTTP/1.1[0m" 302 -
[INFO 2020-06-24 21:01:16,692 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/zh/index HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,761 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/VkV5mNLxNcjVF_tRLZs-s/pages/_app.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,762 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/VkV5mNLxNcjVF_tRLZs-s/pages/index.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,766 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/runtime/webpack-f537ae805509c7d59efa.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,767 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/framework.eb23ff06184ceee71586.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,769 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/515f8eb7.388918b8a3ecc475f96b.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,771 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/a29ae703.2047696a85fb91efd3d8.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,774 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/commons.01d76da71ade4f434d7e.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,777 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/036863a7b4d7b617d876fd7f16b30df0ae108471.9b424acd63e27c37c623.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,778 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/ea957971bd52f269ed421afb3f779345c2e1688f.6568679670aeddf48908.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,781 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/6cc60951388cb42849c1661502ee2530856c9b25.83c20c0c519f737208af.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,782 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/runtime/main-530fbd703fd0e8399599.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,784 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/chunks/e57067a3f11b035a595429563f75168b38af7e07.4da138427a649f92ddf7.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,794 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[36mGET /app/style/fonts/vdl-icon.ttf HTTP/1.1[0m" 304 -
[INFO 2020-06-24 21:01:16,927 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[36mGET /app/images/logo.svg HTTP/1.1[0m" 304 -
[INFO 2020-06-24 21:01:16,927 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/VkV5mNLxNcjVF_tRLZs-s/_buildManifest.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:16,930 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:16] "[37mGET /app/_next/static/VkV5mNLxNcjVF_tRLZs-s/_ssgManifest.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,083 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/chunks/27.3b8529690cd9e8161f5e.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,084 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/chunks/28.6e990f20aae98019b4b8.js HTTP/1.1[0m" 200 -
[WARNING 2020-06-24 21:01:17,144 lib.py:184] update cache data/components
[INFO 2020-06-24 21:01:17,145 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/api/components HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,169 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/chunks/4a2b6650d9ec546c9ef9eabdc04179a6f12ca9d4.3cc78107035e0118996e.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,170 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/VkV5mNLxNcjVF_tRLZs-s/pages/graphs.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,180 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/chunks/e57067a3f11b035a595429563f75168b38af7e07.4da138427a649f92ddf7.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,183 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/chunks/4a2b6650d9ec546c9ef9eabdc04179a6f12ca9d4.3cc78107035e0118996e.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,184 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/VkV5mNLxNcjVF_tRLZs-s/pages/graphs.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,209 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[36mGET /app/locales/zh/graphs.json HTTP/1.1[0m" 304 -
[INFO 2020-06-24 21:01:17,211 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[36mGET /app/locales/en/graphs.json HTTP/1.1[0m" 304 -
[WARNING 2020-06-24 21:01:17,236 lib.py:184] update cache data/plugin/graphs/graph
[ERROR 2020-06-24 21:01:17,237 api.py:59] Internal server error. Retry later.
[INFO 2020-06-24 21:01:17,239 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/api/graphs/graph HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,253 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/netron/index.html HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,257 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[36mGET /app/images/netron.png HTTP/1.1[0m" 304 -
[INFO 2020-06-24 21:01:17,269 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/netron/style.css HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,270 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/netron/vendors.50373bbbe3043081b4b0.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,272 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/netron/index.50373bbbe3043081b4b0.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,277 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/netron/shim.50373bbbe3043081b4b0.js HTTP/1.1[0m" 200 -
[INFO 2020-06-24 21:01:17,279 _internal.py:122] 127.0.0.1 - - [24/Jun/2020 21:01:17] "[37mGET /app/_next/static/netron/style.50373bbbe3043081b4b0.js HTTP/1.1[0m" 200 -

**Comment by PeterPanZH** [comment]
可以提供下页面截图吗？

**Comment by thrkingd** [comment]
现象的截图：
![批注 2020-06-25 084358](https://user-images.githubusercontent.com/46418649/85641095-2d682f00-b6c0-11ea-8653-e7ed7e87b1ea.jpg)

**Comment by PeterPanZH** [comment]
看起来是浏览器不兼容。查看网络结构只支持chrome浏览器，请用最新版的chrome再试一下。后续会考虑加一个提示~

**Comment by thrkingd** [comment]
换了chrome浏览器确实可以了，希望可以改进一下兼容性

**Comment by PeterPanZH** [comment]
因为Graph功能强依赖浏览器特性，目前只有chrome支持全部功能，safari和firefox支持部分功能。后面会加个提示。
