### ISSUE TITLE
数据加载中，请稍等

### ISSUE THREAD

**Issue by zachary-zheng** [PaddlePaddle/VisualDL#682]
你好！
我的Visualdl 版本2.0.0b4， 
命令行输入以下：visualdl --logdir E:\Python\Pycharm\my work\AI_study\Learning_from_Github\04 paddlepaddle-learn\03 Paddle_hub\peach_clas
s\Finetuning\Fine_tuning_efficientnetb0\fine_tuning_2020-6-27\visualization --port 8080
然后用Google/sougou 浏览器打开http://127.0.0.1:8080/ 一直显示“数据加载中，请稍等”，只有一次在深夜结果能显示出来。后面从来都是显示“数据加载中，请稍等”。请问如何解决，谢谢。

**Comment by PeterPanZH** [comment]
方便提供一下logdir指定的日志吗？

**Comment by zachary-zheng** [comment]
[vdlrecords.1593225272.log](https://github.com/PaddlePaddle/VisualDL/files/4842131/vdlrecords.1593225272.log)
[vdlrecords.1592579246.log](https://github.com/PaddlePaddle/VisualDL/files/4842132/vdlrecords.1592579246.log)
Thanks

**Comment by zachary-zheng** [comment]
原因已查明，问题已解决。我原来路径用了\,转成/就行了。
谢谢。
