### ISSUE TITLE
docker 容器内使用visualdl, board 无图像显示

### ISSUE THREAD

**Issue by wuxlun** [PaddlePaddle/VisualDL#683]
paddle的镜像版本1.8.2
visualdl版本2.0.0b7
容器端口映射 8040：8040
在容器内包含执行：
vdl_create_scratch_log
visualdl --logdir=scratch_log --host=0.0.0.0 
进入http://0.0.0.0:8040/  查看board，出现：
![image](https://user-images.githubusercontent.com/62460490/85939754-98c53180-b94a-11ea-8e60-05fd17baa053.png)
如果在宿主机上直接执行，则会出现正确画面。
求指导如何在容器内操作visualdl, board出现可视化结果

**Comment by PeterPanZH** [comment]
`vdl_create_scratch_log`这个脚本在VisualDL 2.0中已经废弃，其生成的日志VisualDL应该无法读取。请问宿主机也是用这个脚本生成的log吗？

**Comment by wuxlun** [comment]
@PeterPanZH 宿主机也是用这个脚本生成的，但是因为容器不识别这个command，我将生成的文件复制到了容器目录后，再使用的visualdl命令

**Comment by PeterPanZH** [comment]
日志是复制到了容器的`${WORKDIR}/scratch_log`中吗？可以`docker exec`进去看看是不是日志路径不对

**Comment by PeterPanZH** [comment]
方便的话可以把Dockerfile贴一下

**Comment by wuxlun** [comment]
@PeterPanZH 我重新开启了一个新容器，不安装paddledetection,结果这个脚本可以使用，而且board也正常了，这是为什么
![image](https://user-images.githubusercontent.com/62460490/85940521-7d105a00-b94f-11ea-8dd8-6d2755da3d61.png)

**Comment by wuxlun** [comment]
为何两个页面一个有飞桨标志，一个没有

**Comment by PeterPanZH** [comment]
visualdl版本不同。蓝色是2.0，目前处于beta阶段，绿色是1.x，目前已不再维护。

**Comment by wuxlun** [comment]
我在宿主机上的visualdl版本是2.0，为何出现的仍旧是绿色面板

**Comment by wuxlun** [comment]
还有一个问题是，如果我的visualdl的版本是2.0，我应该用什么命令来下载符合这个版本的log示例，已知的错误是如果2.0使用1.x的log示例，飞桨的board会显示无可视化结果展示。

**Comment by ShenYuhan** [comment]
出现vdl1.X版本的原因应该是没删除干净。
现在没有命令提供log下载，您可以参照这里自己试一下运行demo得到log进行测试。
[vdl demo](https://github.com/PaddlePaddle/VisualDL/tree/develop/demo/components)

**Comment by wuxlun** [comment]
@ShenYuhan 按照您的链接，在运行了 scalar_test.py后，成功生成了一个.log文件，但使用visualdl运行这个文件后，飞桨的board显示“服务器发生了一个错误”

**Comment by PeterPanZH** [comment]
请问出现“服务器发生了一个错误”的页面时，您启动visualdl的命令是什么？

**Comment by PeterPanZH** [comment]
运行`python scalar_test.py`后，会在当前目录下生成一个`log`文件夹，请先确认是否生成这个文件夹。如果已生成，请使用`visualdl --logdir ./log`启动。

**Comment by wuxlun** [comment]
@PeterPanZH 您好，生成的log文件夹里的内容是  log/scalar_test/train/vdlrecords.1593348758.log，再无其他文件，执行的命令是 `visualdl --logdir=log/scalar_test/train`   我在win10的anaconda环境，ubuntu16的环境，以及映射端口后的docker容器内均进行了实验，进入飞桨visualdl页面均显示“服务器发生了一个错误”

**Comment by ShenYuhan** [comment]
您可以试试下面两步是否解决问题
1 使用的vdl版本是最新的2.0.0b7，可通过下述命令从查看
```shell
pip show visualdl
```
2 为避免路径输入错误问题，可进入到日志所在路径中使用下述命令打开vdl
```shell
visualdl --logdir .
```

**Comment by KuntaHu** [comment]
您好，我查看我的vdl是2.0.0b7版本，可以成功运行这两步。但是在浏览器中依然打不开vdl。我不知道是不是我的电脑原因MacBook。再就是我使用的是AI Studio里面的PaddleSeg中RemoteSensing模块，train_demo里面将vdl设置为true之后，在best_model文件夹下有一个log可以用于vdl显示。我使用的paddle版本为1.7.2

同时我也采用了scalar_test.py成功生成了log，也试着使用不同的port 和host。都无法成功在浏览器中显示board。还请帮忙解决。谢谢！

**Comment by wuxlun** [comment]
@KuntaHu paddle版本要求是1.8以上

**Comment by wuxlun** [comment]
@ShenYuhan 我按照您给的两个步骤执行，vdl版本为最新，仍然出现以下画面：
![image](https://user-images.githubusercontent.com/62460490/86433579-b40ab500-bd2d-11ea-9160-131eb819c365.png)

**Comment by KuntaHu** [comment]
您好，按照您要求已经升级到1.8, 但是并没有变化，依然无法打开浏览器页面。

**Comment by PeterPanZH** [comment]
> 您好，按照您要求已经升级到1.8, 但是并没有变化，依然无法打开浏览器页面。

打不开的表现是什么？

**Comment by Gjiangtao** [comment]
> @ShenYuhan 我按照您给的两个步骤执行，vdl版本为最新，仍然出现以下画面：
> ![image](https://user-images.githubusercontent.com/62460490/86433579-b40ab500-bd2d-11ea-9160-131eb819c365.png)

我也遇到这个问题了，同时终端报错

> [ERROR 2020-08-30 17:08:22,138 api.py:59] Internal server error. Retry later.

**Comment by Gjiangtao** [comment]
> > 您好，按照您要求已经升级到1.8, 但是并没有变化，依然无法打开浏览器页面。
> 
> 打不开的表现是什么？

表现就是终端报这个错误
> [ERROR 2020-08-30 17:08:22,138 api.py:59] Internal server error. Retry later.

**Comment by leyiweb** [comment]
终端没有报错，容器内curl都不通，无法映射到外部

root@xxxxx:~# curl http://127.0.0.1:8080
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/app">/app</a>.

**Comment by PeterPanZH** [comment]
> 终端没有报错，容器内curl都不通，无法映射到外部
> 
> 
> 
> root@xxxxx:~# curl http://127.0.0.1:8080
> 
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> 
> <title>Redirecting...</title>
> 
> <h1>Redirecting...</h1>
> 
> <p>You should be redirected automatically to target URL: <a href="/app">/app</a>.

@leyiweb curl显示了服务器返回了302，请用浏览器打开
