### ISSUE TITLE
Static "real-time" demo webpage

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#69]
We need an online demo to display some real-time effect, some requirements are as follows:

- quite light-weight and stand large amount visits
   - can the single frontend simulate this effect?
- look like real-time, the components should be updated dynamically.

**Comment by varunarora** [comment]
@Superjomn Is this still a requirement? If so, should be resolved alongside #239

**Comment by Superjomn** [comment]
no, it's not important in the current stage.
