### ISSUE TITLE
Cannot display records inside a symbolic link to a directory

### ISSUE THREAD

**Issue by chenwthu** [PaddlePaddle/VisualDL#702]
If the file tree is as follows, only the ordinary directory shows on the webpage.
```
logs/
|---- ordinary directory/
|     |---- vdlrecords
|---- symlink to a directory@
      |---- vdlrecords
```

**Comment by ShenYuhan** [comment]
You can use `visualdl --logdir .` in `PATH:XXX/XXX/logs`

**Comment by chenwthu** [comment]
Doesn't work. The reason can be that the _followlinks_ option of _os.walk_ is not set to _True_ somewhere in the codes.

**Comment by ShenYuhan** [comment]
Thanks for your suggestions, we will fix it in next version.
