### ISSUE TITLE
Does VisualDL provide C + + interface?

### ISSUE THREAD

**Issue by QinZiwen** [PaddlePaddle/VisualDL#745]
Does VisualDL provide C + + interface?

**Comment by ZeyuChen** [comment]
Currently we only have python interface. 
Which scenario you need C++ interface to visualize deep learning training procedure? It seems most of the framework have python interface.

**Comment by QinZiwen** [comment]
I want to use visual DL in other C + + programs that are not deep learning。

**Comment by ZeyuChen** [comment]
Since VisualDL 2.0 was developed in pure Python, so there is no C++ interface.

**Comment by QinZiwen** [comment]
ok，thanks
