### ISSUE TITLE
数据载入中，请稍等

### ISSUE THREAD

**Issue by fjd330621** [PaddlePaddle/VisualDL#777]
偶尔出现这一种情况
还有就是在document中并没有看到删除已有线条、图像的方法

**Comment by PeterPanZH** [comment]
请问可以提供下您的log吗？

**Comment by PeterPanZH** [comment]
目前无法删除log中已有的数据，如果不想看某个run的数据可以在右边将其取消勾选。

**Comment by fjd330621** [comment]
不好意思，回复迟了，是这一个吗?
![2020-08-31 20-06-14 的屏幕截图](https://user-images.githubusercontent.com/48682599/91718703-82e02100-ebc6-11ea-871a-1c6ede260c26.png)

就是copy的向导中的scalar语句，非常简单，还有就是能显示的时候也有一个问题就是不是常见的走势线，它会左右往返，但照理说我的step是跟随i时刻增加的，每个step只输入了一个值
with LogWriter(logdir="./log/scalar_test/train") as writer:
    writer.add_scalar(tag="acc", step=i, value=loss_value)

**Comment by PeterPanZH** [comment]
麻烦将`./log/scalar_test/train`中的文件打包发一下我看看能不能复现

**Comment by fjd330621** [comment]
[vdlrecords.1598874873.zip](https://github.com/PaddlePaddle/VisualDL/files/5153447/vdlrecords.1598874873.zip)

**Comment by PeterPanZH** [comment]
这边看您的日志都只有一个点

**Comment by fjd330621** [comment]
不好意思，我现在好像理解了 ，with LogWriter(logdir="./log/scalar_test/train") as writer:这个命令应该会重置log？应该放在for 循环的外面？
