### ISSUE TITLE
一个图多条线的时候，出现了一个不存在的tag

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/VisualDL#82]
![image](https://user-images.githubusercontent.com/3048612/34781368-9c638ce2-f660-11e7-938f-b781d30e63f9.png)

**Comment by BingBlog** [comment]
提供下场景，这个我也复现不了~

提问题的时候，可以尝试分析下造成问题的原因吧。这个/loss是一个Tag么？返回值中是否存在 //loss这样的标签？

或者把接口返回的Tag json数据提供下？

**Comment by BingBlog** [comment]
Don't appear again~
