### ISSUE TITLE
显示数据加载中，请稍后

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/VisualDL#825]
[vdlrecords.1600690579.log](https://github.com/PaddlePaddle/VisualDL/files/5255294/vdlrecords.1600690579.log)
附log，麻烦帮忙看下吧～

**Comment by PeterPanZH** [comment]
麻烦提供下您的浏览器版本

**Comment by xiegegege** [comment]
应该不是浏览器的问题，我试了safari和chrome都不行

**Comment by PeterPanZH** [comment]
额，我这边看是可以打开的，所以想确认下。
另外visualdl的版本是多少呢？

**Comment by xiegegege** [comment]
visualdl的版本是2.0.0b4，还有运行时候的日志是：
<img width="960" alt="ef42d063050ddf1abcef28beea33de6d" src="https://user-images.githubusercontent.com/46314656/93767574-ccaeab00-fc4a-11ea-9251-1bfb8530d630.png">

**Comment by PeterPanZH** [comment]
先升级一下visualdl的版本吧，最新版是2.0.4

**Comment by xiegegege** [comment]
我试了最新版～
<img width="966" alt="6f30be10c705e5c486b5d3faee0262b6" src="https://user-images.githubusercontent.com/46314656/93768538-1ea40080-fc4c-11ea-855a-e2ff2c56752c.png">
<img width="840" alt="b419a291ca8d4f27f59d75d9d4b69b5c" src="https://user-images.githubusercontent.com/46314656/93768585-2fed0d00-fc4c-11ea-86b1-7fecbe990636.png">

**Comment by PeterPanZH** [comment]
看了你的命令我知道了。。 `--logdir` 后面请直接跟目录，不要指定到.log文件
`--logdir vdl_dir` 即可

**Comment by xiegegege** [comment]
哦哦，可以了的，多谢啦～
