### ISSUE TITLE
visualdl 

### ISSUE THREAD

**Issue by tangxiaochu123230** [PaddlePaddle/VisualDL#826]
本地python==3.6.8
在tools目录的 powershell windows 输入如下命令
visualdl --logdir=./vdl_dir/scalar/ --port=8080
浏览器中输入http://localhost:8080，打不开啊（aw snap），尝试了chrome和microsoft edge
问下问题在哪

**Comment by PeterPanZH** [comment]
麻烦提供下
1. 控制台是否有报错或日志
2. 打不开是什么现象

**Comment by tangxiaochu123230** [comment]
1控制台不报错
2.在chrome打开
报错
something went wrong while displaying this webpage
Error code: STATUS_INVALID_IMAGE_HASH

**Comment by PeterPanZH** [comment]
浏览器内核问题，请百度解决方案，或者换用firefox试试
