### ISSUE TITLE
need more documentations

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#83]
# Tutorial
- [x] quick start @ChunweiYan
- [ ] introduction for scalar
- [ ] introduction for histogram
- [ ] introduction for image
- [ ] introduction for graph

# Site
- [ ] content of home page
  - [ ] project aims
  - [ ] our advantages
  - [ ] team infomation
- [x] quick start(same with Tutorial)
- demos (with basic documentation those can be transformed to reading-sutible HTML pages)
  - [ ] mxnet demo
  - [ ] pytorch demo
  - [ ] paddle demo
- [x] how to contribute

**Comment by cs2be** [comment]
[@daming-lu] Add comprehensive content (README, Tutorials, Demos) in both English and Chinese to make new users easier to get started
