### ISSUE TITLE
使用指令运行VisualDL后浏览器一片空白

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/VisualDL#834]
Chrome版本：85
操作系统：Win10
Python版本：3.6.10
Paddle版本：1.8
VisualDL版本：2.0.4
下图为项目结构
![image](https://user-images.githubusercontent.com/7108023/95809500-89bf8f00-0d41-11eb-8c8a-9deb5fd38408.png)
我看使用[指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/evaluation_debugging/debug/visualdl_usage.html#graph)说可以通过指令`visualdl --model ./log/model --port 8080`打开模型，或者`visualdl --logdir ./log --port 8080`拖拽模型，但是这两个页面打开都是空白。
chrome浏览器的调试栏打印出以下信息
![image](https://user-images.githubusercontent.com/7108023/95814981-50415080-0d4e-11eb-8bd4-d0e7b07fd095.png)

**Comment by PeterPanZH** [comment]
https://github.com/pallets/flask/issues/1045#issuecomment-42202749
请参考这里，可能是某些软件把windows注册表的默认值修改了。

注册表里找到 HKEY_CLASSES_ROOT 这个表然后把 .css/Content Type 的值改成text/css，把 .js/Content Type 的值改成text/javascript

visualdl将在下一个版本对这种情况做兼容。

**Comment by a2824256** [comment]
已解决，把 .js/Content Type 的值改成text/javascript就没问题了
