### ISSUE TITLE
网页显示界面的问题

### ISSUE THREAD

**Issue by QinZiwen** [PaddlePaddle/VisualDL#836]
网页显示界面的最右边不能滚动，导致选择数据流很难受。如下图，右边整体不能滚动，只有选择数据流下面一点点可以滚动。

![Uploading infoflow 2020-10-15 20-48-31.png…]()

**Comment by QinZiwen** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/15364705/96128727-4ecb8000-0f28-11eb-8408-e14a35106db8.png">

**Comment by PeterPanZH** [comment]
会考虑优化浏览器高度不足时的展现
