### ISSUE TITLE
aistudio训练平台上打开可视化显示空白的，是不是改版了，之前是好的

### ISSUE THREAD

**Issue by cisco08** [PaddlePaddle/VisualDL#841]
https://aistudio.baidu.com/bdvgpu32g/user/209344/1167599/visualdl/index
ai s tu
![image](https://user-images.githubusercontent.com/8415114/98065655-f684ff80-1e8f-11eb-94fe-7746882cafab.png)
![image](https://user-images.githubusercontent.com/8415114/98065679-04d31b80-1e90-11eb-90e3-4d0bc887fb09.png)

**Comment by ShenYuhan** [comment]
您使用的浏览器及版本是？可以尝试重启一下项目看看是否解决

**Comment by YixinKristy** [comment]
> https://aistudio.baidu.com/bdvgpu32g/user/209344/1167599/visualdl/index
> ai s tu
> ![image](https://user-images.githubusercontent.com/8415114/98065655-f684ff80-1e8f-11eb-94fe-7746882cafab.png)
> ![image](https://user-images.githubusercontent.com/8415114/98065679-04d31b80-1e90-11eb-90e3-4d0bc887fb09.png)

麻烦您把环境保持开着的状态，我们这边aistudio的同事会帮您排查下问题

**Comment by cisco08** [comment]
开着的，Chrome版本 75.0.3770.90（正式版本）

**Comment by PeterPanZH** [comment]
> 开着的，Chrome版本 75.0.3770.90（正式版本）

版本有点老，请使用Chrome 79+

**Comment by cisco08** [comment]
升级了，现在正常了，谢谢
版本： 86.0.4240.183（正式版本） (x86_64)
