### ISSUE TITLE
请问关闭visualdl命令之后，再次运行之后不会加载历史log，而只是重新开始

### ISSUE THREAD

**Issue by ShougangShen** [PaddlePaddle/VisualDL#845]
在进行网络训练时，我运行如下命令打开Visualdl工具
`visualdl --logdir log/`
然后，由于某种原因，比如按了 Ctrl + C 结束了该命令。然后重新运行上述命令之后，visualdl可以正常启动，但是发现visualdl无法加载之前的log，也就是重开了之后，面板只显示重新运行命令之后的log，请问有什么方法可以将之前的log重新显示吗？

tensorboard在结束命令，重新运行后会是可以自动将之前的log加载出来。

**Comment by PeterPanZH** [comment]
请问您在训练过程中是如何打日志的？如果训练过程中一直用一个日志文件是会显示全部的，如果训练过程中生成了新的日志文件，那么只会读取最新的日志文件。

**Comment by PeterPanZH** [comment]
@ShenYuhan

**Comment by ShougangShen** [comment]
我是每个step with LogWriter() as writer一下，比如下面这样
`with LogWriter(logdir=os.path.join(cfg.LOG, 'loss/baseline/{}'.format(args.network), cls)) as writer:
    writer.add_scalar(tag='loss/baseline/total_loss', step=step, value=loss)`

可能是这个问题，我改下代码试试。

**Comment by ShougangShen** [comment]
确实是这个问题，感谢 @PeterPanZH 。最后建议可以在使用指南里面添加上这个说明，以区别tensorboard。

**Comment by ShougangShen** [comment]
还有一个问题哈，visualdl好像对 数据为 nan 的表示不是太好呀，如果数据有nan的话，好像会出现 “解析失败”的问题啊，这可能是一个bug呀。
