### ISSUE TITLE
可视化页面空白

### ISSUE THREAD

**Issue by weiwenxiao0** [PaddlePaddle/VisualDL#873]
在AI Studio网页上进行损失函数等可视化，但按照教程打开可视化网页显示空白，是什么原因呢？

**Comment by weiwenxiao0** [comment]
望回复，感谢~

**Comment by PeterPanZH** [comment]
请问浏览器版本多少？

**Comment by weiwenxiao0** [comment]
刚刚进行浏览器的更新，是浏览器版本太低的原因，已经解决，谢谢你~

**Comment by weiwenxiao0** [comment]
> 请问浏览器版本多少？

刚刚进行浏览器的更新，是浏览器版本太低的原因，已经解决，谢谢你~
