### ISSUE TITLE
Logwriter在pycharm中的警告

### ISSUE THREAD

**Issue by foreverseer** [PaddlePaddle/VisualDL#875]
VisualDL/visualdl/writer/writer.py 
LogWriter.add_image函数
注释
        Args:
            tag (string): Data identifier
            img (numpy.ndarray): Image represented by a numpy.array
            step (int): Step of image
            walltime (int): Wall time of image
            dataformats (string): Format of image
第二个参数img的注释需修改为img (np.ndarray)
        Args:
            tag (string): Data identifier
            img (np.ndarray): Image represented by a numpy.array
            step (int): Step of image
            walltime (int): Wall time of image
            dataformats (string): Format of image
因为之前已经进行了import numpy as np
如果此处写numpy.ndarray会在pycharm中报一个警告
“Expected type 'Type[ndarray]', got 'ndarray' instead”

**Comment by PeterPanZH** [comment]
@ShenYuhan look look

**Comment by ShenYuhan** [comment]
多谢意见，明白您意思了，非常诚挚的邀请您可以给我们提个pr来修复此不该出现的warning，不知道有没有兴趣

**Comment by PeterPanZH** [comment]
fixed by #877
