### ISSUE TITLE
material needed by Marketing

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/VisualDL#90]
- demo gif/vedio
  - [x] scalar
  - [x] image
  - [x] histgram
  - [x] graph
  - [x] 没有Visual-DL之前，纯代码滚屏的那种效果，体现一下无法可视化的时候深度学习的状态
  - [x] Graph那个部分，也可以录一个从缩在一点的状态突然散开的效果，做个单独的Gif
  - [ ] easy to use, diff of integrate visualdl to other platform

**Comment by varunarora** [comment]
Is this still a task item or can we close this for now @jacquesqiao?

**Comment by jacquesqiao** [comment]
we can close it now~
