### ISSUE TITLE
Launch an interactive demo online

### ISSUE THREAD

**Issue by Pzoom522** [PaddlePaddle/VisualDL#906]
Hi,

It would be great if the latest version of VisualDL could have an online demo like https://projector.tensorflow.org/, especially for the enhanced embedding visualiser. 

Many thanks!

**Comment by PeterPanZH** [comment]
Thanks for your sugestion. Actually we do have an online demo at [https://www.paddlepaddle.org.cn/paddle/visualdl/demo](https://www.paddlepaddle.org.cn/paddle/visualdl/demo) . @YixinKristy why not put the link into README.md

**Comment by Pzoom522** [comment]
Glad to know! Made https://github.com/PaddlePaddle/VisualDL/pull/907.
