### ISSUE TITLE
使用指令运行VisualDL后浏览器一片空白

### ISSUE THREAD

**Issue by qiuming-93** [PaddlePaddle/VisualDL#911]
Chrome版本：69
操作系统：Win10
Python版本：3.6.4
Paddle版本：1.8.5
VisualDL版本：2.1.0

安装visualDL之后，执行visualdl命令后打开http://localhost:8040页面一篇空白
console报错
Uncaught ReferenceError: globalThis is not defined
    at env.js:1

已经按照下面步骤操作过了
注册表里找到 HKEY_CLASSES_ROOT 这个表然后把 .css/Content Type 的值改成text/css，把 .js/Content Type 的值改成text/javascript
并且重启过服务器了，还是这样一直显示空白

**Comment by PeterPanZH** [comment]
要求Chrome 89+，请升级浏览器之后再试试

**Comment by qiuming-93** [comment]
好的，我把visualdl的版本降下来了，也是可以了，我降到了2.0.4
