### ISSUE TITLE
为什么 一设置 host 为‘。0.0.0.0’,就显示403forbidden

### ISSUE THREAD

**Issue by demo-agui** [PaddlePaddle/VisualDL#933]
![image](https://user-images.githubusercontent.com/78901257/107865005-85e17c00-6e9d-11eb-9b3f-d5b901a5f52f.png)
![image](https://user-images.githubusercontent.com/78901257/107865015-985bb580-6e9d-11eb-86c1-025f56b818ed.png)

**Comment by PeterPanZH** [comment]
0.0.0.0不代表本机，请用浏览器访问127.0.0.1

**Comment by demo-agui** [comment]
> 0.0.0.0不代表本机，请用浏览器访问127.0.0.1

我127.0.0.1，可以进入，但为什么 host 设为这个就进不去了

**Comment by PeterPanZH** [comment]
0.0.0.0 不是一个合法的ip地址，VisualDL使用 0.0.0.0 代表绑定到所有地址。请使用 127.0.0.1 来访问。
