### ISSUE TITLE
所有问题都找遍并修正了，依旧显示这个错误

### ISSUE THREAD

**Issue by demo-agui** [PaddlePaddle/VisualDL#934]
![image](https://user-images.githubusercontent.com/78901257/107878444-c37ded80-6f0d-11eb-8d3f-b2d3852d5d21.png)
![image](https://user-images.githubusercontent.com/78901257/107878462-d85a8100-6f0d-11eb-9cec-ca2996761351.png)

**Comment by PeterPanZH** [comment]
你哪里用到了VisualDL呢？

**Comment by demo-agui** [comment]
> 你哪里用到了VisualDL呢？

我这是flask ，用template来渲染界面的。跟visualdl无关吧

**Comment by ShenYuhan** [comment]
你把"index.html "中那个多余的空格删除试试呢。

这个问题出现在visualdl issue的原因是什么

**Comment by demo-agui** [comment]
> 你把“ index.html”中那个多余的空格删除试试呢。
> 
> 这个问题出现在visualdl问题的原因是什么

把templates文件放到venv下面就好了
