### ISSUE TITLE
aistudio中paddleseg使用VisualDL发生错误

### ISSUE THREAD

**Issue by kingtiger999** [PaddlePaddle/VisualDL#952]
paddle版本2.0.2，paddleseg 版本2.0.0
logdir选择的 paddleseg 中的output文件夹

**Comment by ShenYuhan** [comment]
您好，请问具体报什么错误呢？

**Comment by kingtiger999** [comment]
您好，我是用的paddleseg组件做图像分割，具体操作截图如下，在生成日志文件后选择日志目录并启动VisaulDL，请问是操作错误吗？









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 上午10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/VisualDL] aistudio中paddleseg使用VisualDL发生错误 (#952)





 
您好，请问具体报什么错误呢？

**Comment by ShenYuhan** [comment]
我没看到您的截图

**Comment by kingtiger999** [comment]
您好，截图这次我添加到附件里了，ps:打开模型网络结构没有问题

**Comment by YixinKristy** [comment]
> 您好，截图这次我添加到附件里了，ps:打开模型网络结构没有问题

您好，还是没有看到截图哈

**Comment by kingtiger999** [comment]
您好，请问还有其他邮箱吗，可能github邮箱无法发照片，我可以发到其他邮箱。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/VisualDL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/VisualDL] aistudio中paddleseg使用VisualDL发生错误 (#952)





  
您好，截图这次我添加到附件里了，ps:打开模型网络结构没有问题
  
您好，还是没有看到截图哈

**Comment by kingtiger999** [comment]
您好，我已经解决了，是因为浏览器版本太低的问题，感谢
