### ISSUE TITLE
how can i import raw data?

### ISSUE THREAD

**Issue by sukkyusun** [PaddlePaddle/VisualDL#971]
visualdl support only exporting with png image file?

can i download it to csv file or something raw format

**Comment by YixinKristy** [comment]
<img width="1114" alt="截屏2021-05-26 上午10 14 39" src="https://user-images.githubusercontent.com/48054808/119592543-423ace80-be0b-11eb-9b81-f5aa4a144bb1.png">

Do you mean the data of 'scalar' tab? If so, you can download the data by click the download button here~

**Comment by sukkyusun** [comment]
thanks the button is not avaliable during training,

when training is over ill do it

**Comment by sukkyusun** [comment]
> <img alt="截屏2021-05-26 上午10 14 39" width="1114" src="https://user-images.githubusercontent.com/48054808/119592543-423ace80-be0b-11eb-9b81-f5aa4a144bb1.png">
> 
> Do you mean the data of 'scalar' tab? If so, you can download the data by click the download button here~

![Screenshot from 2021-05-27 10-28-39](https://user-images.githubusercontent.com/27720424/119751656-86df6c00-bed6-11eb-8ac8-f3606054a6d4.png)
i only have download image.. how can i import csv format

**Comment by PeterPanZH** [comment]
please upgrade your visualdl to 2.1.0+
https://github.com/PaddlePaddle/VisualDL/releases/tag/v2.1.0

**Comment by sukkyusun** [comment]
> please upgrade your visualdl to 2.1.0+
> https://github.com/PaddlePaddle/VisualDL/releases/tag/v2.1.0

thx problem solved
