### ISSUE TITLE
suggestions about reloading after delete, and layout

### ISSUE THREAD

**Issue by sndnyang** [PaddlePaddle/VisualDL#978]
1. 我删除某条数据流之后， 出现 Unexpected error: <class 'FileNotFoundError'>  Internal server error. Retry later.   重启visualdl还是比较麻烦， 我既然删除掉那条记录， 自然也是希望visualdl 里能自动删掉
2.  数据流选择那块也太小了， 就显示两条， 翻起来 很容易就错过一条两条的， 上面其他功能区应该没必要这么大， 多留点空间给数据流选择？
3.  数据流 排序不正确， 举例
aaa/mnist/0531
aaa/mnist/0601
bbb/mnist/0601
bbb/mnist/0531
第一层aaa 和 bbb 排序是对的，  但子目录里 是乱序， 我到 aaa/mnist/下 运行visualdl， 顺序也不对
![image](https://user-images.githubusercontent.com/2310591/120550067-632e9100-c3c2-11eb-907f-a5518c3d0346.png)
是我安装的有问题， 还是？

谢谢！ 可能也是用惯了 tensorboard~

**Comment by ShenYuhan** [comment]
感谢您的意见
1. 一般情况下在运行过程中文件突然被删除，我们目前认为是一个非常规操作，因此会报错，您的需求我们会进行讨论，目前还是建议您重启visualdl；
2. 这个交互方案我们会重新评估；
3. 这里我们会修改为按照字典序排序。
欢迎您给予更多宝贵的意见
