### ISSUE TITLE
手机浏览器visualDL：发生错误

### ISSUE THREAD

**Issue by Dreamupers** [PaddlePaddle/VisualDL#987]
![QQ图片20210618111417](https://user-images.githubusercontent.com/49057488/122501138-b80b1200-d026-11eb-8b4d-9794684ce153.jpg)
手机端可以打开但是显示“发生错误”，切换为桌面版网站依然如此。（测试过多个浏览器）

**Comment by ShenYuhan** [comment]
可以提供下你运行的脚本以及生成的日志文件吗，我们复现一下

**Comment by Dreamupers** [comment]
visualdl运行在tmux会话中，python虚拟环境由virtualenvwrapper创建，visualdl 2.2.0
运行脚本：visualdl --logdir ./log --host 0.0.0.0 --port 30001
日志文件在：log/20210617225117/vdlrecords.1623941477.loghrnet
vdlrecords.1623941477.loghrnet：[https://yrqzxh.com/vdlrecords.1623941477.loghrnet](url)

**Comment by ShenYuhan** [comment]
您好，我这里查看您的日志是没有问题的
![image](https://user-images.githubusercontent.com/28444161/122503836-b98b0900-d02b-11eb-997a-32a3f555ae6c.png)
您使用的是什么浏览器呢，可以尝试使用最新版的chrome浏览器查看

**Comment by Dreamupers** [comment]
电脑上没问题，手机浏览器显示发生错误的。

**Comment by PeterPanZH** [comment]
不好意思visualdl并没有针对移动端浏览器做任何适配。理论上来说，Safari for iOS 11+，Chrome for Android 91+，Firefox mobile 89+ 可以打开，其他浏览器会报错。

**Comment by Dreamupers** [comment]
好的，谢谢，手机的Chrome可以打开
