### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/VisualDL#989]
VDL很好用，希望能加入一个这种颜色的标注点，能更好的截图识别曲线
![微信截图_20210621092524](https://user-images.githubusercontent.com/77316774/122695490-13314480-d273-11eb-9612-d509cc35ab04.png)

**Comment by PeterPanZH** [comment]
目前可以在右侧选择数据流中查看图例，或鼠标放在折线图上出现的tooltip中也可以看到对应颜色。
<img width="266" alt="CleanShot 2021-06-21 at 14 02 50@2x" src="https://user-images.githubusercontent.com/3366499/122714110-63230200-d299-11eb-99e1-8bae899fa88b.png">

如果您是指下载保存图片之后的图例，这个已经在计划中了，下个版本会加上。
非常感谢建议~

**Comment by gaorui999** [comment]
对，我需要的是下载保存图片之后的图例的这种，把鼠标放上去再去截图的话太不方便了，也没法放到论文里

**Comment by lazyn1997** [comment]
请问一下下载带图例的功能·实现了吗？
